apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headlamp
  namespace: kube-system
  annotations:
    # nginx.ingress.kubernetes.io/auth-method: 'GET'
    # nginx.ingress.kubernetes.io/auth-url: 'http://authelia.authelia.svc.cluster.local:9091/api/verify'
    # nginx.ingress.kubernetes.io/auth-signin: 'https://auth.${DOMAIN_2}?rm=$request_method'
    # nginx.ingress.kubernetes.io/auth-response-headers: 'Remote-User,Remote-Name,Remote-Groups,Remote-Email'
    cert-manager.io/cluster-issuer: general-le-prod
    cert-manager.io/private-key-rotation-policy: Always
    gatus.home-operations.com/enabled: "false"
spec:
  ingressClassName: "internal"
  rules:
  - host: headlamp.${DOMAIN_2}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: headlamp-frontend
            port:
              number: 80
  tls:
    - hosts:
      - headlamp.${DOMAIN_2}
      secretName: headlamp-tls-0
