apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: it-tools
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/tools/it-tools/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  targetNamespace: it-tools
  postBuild:
    substitute:
      # NAME: it-tools
      GROUP: tools
