apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: peanut
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/observability/peanut/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  targetNamespace: peanut
  postBuild:
    substitute:
      CHART: peanut
      NAME: peanut
      GROUP: observability
      PROT: http
      SVC: peanut
      NAMESPACE: peanut
      PORT: "10688"
