apiVersion: v1
kind: Namespace
metadata:
    name: gatus
    labels:
        pod-security.kubernetes.io/enforce: privileged
        topolvm.io/webhook: ignore
    annotations:
        volsync.backube/privileged-movers: "true"
