apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tauticord
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/media/tauticord/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  targetNamespace: tauticord
  postBuild:
    substitute:
      GROUP: media
