apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fileflows
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/media/fileflows/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  targetNamespace: fileflows
  postBuild:
    substitute:
      GROUP: media
      PATH: "/api/system/version"
