apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dozzle
resources:
  - helm-release.yaml
components:
  - ../../../../components/ns
  - ../../../../components/notifications/discord
