apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ggrequestz
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/tools/ggrequestz/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
