apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: manyfold
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/tools/manyfold/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  targetNamespace: manyfold
  postBuild:
    substitute:
      GROUP: tools
      PATH: "/health"
