apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft-family
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/games/minecraft/minecraft-family/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  targetNamespace: minecraft-family
