apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:vd/S0yjg10wKOaEiGJ9dSbZn00cRu8dpH5SQS19b1+2q3gOfW3RApPOSw5fObGQRItNJ2dXlBpckCfrbuGQn2eFfrr3M/EISsybpLYkYY03ubhrZmCpTgb5ZdC1fS6BaRE4l0L3HVkRLbiUvPThVycH5jR0Rw3/nvmMqFQ==,iv:8OtPxAEgelTK0Zr3iXrY4gi6TfuTswPI5+UNTVc3Wvc=,tag:N4XTcqxm7dJZVR9oHrToYA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEazByOFhmSTl2QVFRaUFi
            VWNnZENNTGRwWUtuQ0ZwanRmNDVrWXVBNVRvCmF0RS9JcFlkc1dzRzM1bVVKdkJW
            bGRlYy9UYUNiV0I5VllJdExabFdqL0UKLS0tIGFJRDl0amFnSi82aEUwbDY5WStT
            U00yK2wyTndqWmRkTWRyWklnelN1L1UKCsosGWQwGc7C/JgVqOpac9t6MHHR+Uy3
            hwdpL5ooXJtnDVl0fFU5bZQsuRMD1RK2pQfsIvaZPvDgDPmUVGtMbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T13:15:21Z"
    mac: ENC[AES256_GCM,data:7AwaKHy52MH0Hb98akc1fJnTVOpZjHSD/zgOsPWMIaViWc2kGAZOzgt4RpI45fLHPiOCSE6JJ5rZ8s140GH3dUfKo9wzdPna5pU9K3WkhO2g0+3rT3jL0SKGjhdoy9C0gxa48x0Z439t3A5L8r+deFX9mx59o514yCiBtEv0UYg=,iv:0KcnZcfkgRcmUkIOJs7a0mvuSfvZcVx+yMyfKu/EIoE=,tag:/PExV9ix9mtB4H5oPQnGWA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
