apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:o7AuKEqfEQg8OH4je9ISfs8FEDu2VbZ6wPBhNgVwA9BfiEyjLEe4YkmQ3fSmR2ZGZEwx7xmHvHSGlUtXvo69rzcS32m8fI/Q9He/0Z/9664xHx9pFdhc7mWaegLzGt+2q01j+rYfrMc5Nm/GjwbS+KD7wobBAkyxagdRTw==,iv:B5KdqtAJ1MsBHQ17hRZZSL3C2nzSr8CVxjFgXEd+rhM=,tag:UUqD16rzHhamwv2uYJt61w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZENMSGoyZVhCRWZtNFJS
            Z0tUTVFRdHZsMWFPOFpjRnUvWTk5TFlTVzA4Cjk0QXlzejNHVytad0ZxVHZmdndi
            RmVnZnY2K0p4aGZUODRRd2hmMldLSUEKLS0tIFlQdVVmd2QrbzlqZnFlb3NYbEMx
            WUxYOEJFUllLQ3Ntb3VJemZvRjZIMGMKr3nc/XNOExw/xavB23dCEHuooZfEsDxQ
            SB5I0ZdNUK1UEGDv1fz2mRGtXMdl7ecHcqH/i0bO3STwJJL7YZj4KA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T01:11:58Z"
    mac: ENC[AES256_GCM,data:x8mfUCbwv1a8+U+GwzkQCNcN6AiWrDyDoERLLZZ3qvNVrimCfLeV2fTdFNlYYcDZRC7zjtgaMHtz91G27Uog5UN5ibD8aDbLZ8n8hneOZ0tsQvavYbDrBJ/9oLaI2EQbVWBNZwWPa1wfmA10cr5dzyzwyfxDwklDdwQ/PgxFD1Q=,iv:gBxf+B3h4U5okwAaWtiAAcYnRbb+zQ/6EEGxhEElSVs=,tag:OL0XAoeeGfQRuu1CNSfRdA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
