apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:WnVxjD5hPdlliEkRai0E23BBVjOdqvk/12E3M9W0euK6iyQ/UJpNohV+zXOM+zla+DqDqMc6kDyiToCyDbLWiFx7inqleWjlceitwLKsjFIWa5F0rqyF1yAFhQHU8GZtCOfzLFSNgJhKFW+ngoNvqsQ4KdFySMKPSlgipQ==,iv:tbbDEZ4vBivRAqjla+JmkdQSRxVfFHnVe8cL8C24z6w=,tag:ksYMK7OolVO1uGILMPmbpg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlM2lCNjJuK2c1Nzh6em1w
            UFc2T1JUN1FpVlBFRUttV25IZitWWEx5Z1RjCk1JOWpZWU4wNFRxbmlWLzhkeEhV
            cHEzcUc3WHk2dnhhZTc0enkxdzV6bzQKLS0tIFRhem9QQVlFU1k1K0ZVWmVXd2Er
            RDJTN0tPNE8xdk1wK2UvenF3V3E0WE0KDEu/Di9rQpLXAJBOAjOz8hCF1mOGJpXu
            0Fur7oqOp8FkJSGk8Y/SXyUZCmW87Smw6leyfNmoy4430s1V97un3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T07:54:50Z"
    mac: ENC[AES256_GCM,data:+182R/CSmP7AHP5hrkP1gTZiYiwCH77+oz6E9L0BZ8o3LDvyxlLtOTxUhgIckfUSbK2mKntTLd0aDTRtp8Yrnin8q7Yss6q8WD/7v6s7ikxGjvU00GOejg2/HgouEcWlmp7OUc1vz2YnHAOBVFOtodgMvs5jipeXTnHMbmRl+gE=,iv:P7x6rahdrbZJkBUN1uRiolrKwFKbcDsuhhb3rlVpa9g=,tag:G180tRl6rhFyNdlaXeArNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
