apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:A0JoRDH1qfW6VCDGCScK1lhDKCTlustAP7PlqOVa1G6lJLZePtzFeG0Kn2V542vFP6DaUp3RzOmSa8pW7F7t9/p5h1nUINcmOT9CCrcQET0WlePbb+1JN2u64Uca5PjLCsvs+Z5kCx/QPs3BobEnnIpw5gWPZ5bnlu9U7g==,iv:k1hCdYD6hEu2yyE9G8KQ7RFmEXkPJlawplKDQLxzvQ8=,tag:7ysWPyHSuANzU36nom+e4g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQVg5VS9SS3ZFdm1PSzVP
            dEw0OUMwb25kT0NqMFhvOG8ra3RWTis5UjBzCkIxZUt4NFhoR29ha2pHRVR2Z1Y3
            N2orbkwzM09WUTdnWG5iZzJwQUhyZ0EKLS0tIFVaa3lhZmFFRG9yK1VwOGlhVVVM
            MWt6RDdORk9FUVQ5WlNoaTBmeFdtejgKvFMlSnH08wUB1IBu8vi+5w4sfD4Mxbzp
            OxJ6gAVF3Hqt4S6ocV4sxlx97eNGcysSgtbNoIkkTKZlVt/nMppTag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-18T22:21:39Z"
    mac: ENC[AES256_GCM,data:4lSMb+Z0CfmgVRbTsNRsrMdrnSrpKPM2eK97pQLRVCmZ2WFKt0Kq1k/cU8tHoRRXCaH/myQBnMtlqPFocYadu2GWqswnFMKVtftuE3eqBqc1Xc1IBYd2UbWV1uxzK4cFG4MAVY1VBgUpg+WaKGQIY+EQ0EYmpHp/W3BcWrzdeH0=,iv:NGR9UN2ok6pHSe7Dh/dYGGY0Wi7jyPEBzSqE/9N0x2o=,tag:v4ttVWIujKagNadFdSnUvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
