apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:V0rQGj2Fam8cWK8r2HI3WxgSSxXO9Woj4jF+ilNgLjJuEvYUkLyLX3U5CGFS0Do2/mklQOh2FHyUGu+qUPU4eVU+MHvpC0YVqzsdbTNJ/uUJOSTz7MxwcEbj7hlguA3NJU5P5cs+OIHdFnwr4nyb9USRJgVpPrn2VcypyQ==,iv:tuQ6Cp5e1NcSmutJ/jynsskgXDdcXkFwHHdGulX7/Ws=,tag:tbhZvTP2L0G+YJ8ou5iCCA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUlovRXcrcHVaVEhvK3pP
            empvN00xSHBWamtxdnBmTTZzOEFVWmF0VHpvCnlNWnlhVmVXek8weUs4WmNEVkZv
            VXBvWUFuSXZHbzU3VHQ1bnR3dG0reFUKLS0tIFFBSnk1WjVZN0RUV2RkUHgxNHEr
            eUNNZk0wT0hHcm01ZzMza1JJRHpNZWsKglVfAUNKGEEDaGMwabKmx8S4KZuXRX8u
            gG/DffXW+LINzWTrw1OwNC3Kcc5BMRbl/T8/bS3epE9RBr6V3OvV+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T23:51:10Z"
    mac: ENC[AES256_GCM,data:G6cm2mjJJZBvyS3rxT75VhdSZ+1opkxvJgYh1rTukS1H2ArH/SfoLWqd2T6wTZdBt/76tcEkPOl8yC8qU0WyzTtS+1zVSp0WQe27yfKKh16TPnfRqpKbNvf9z2zpJ+2zDgGRX0HZWChUvsRpkAbPpnUN4cKtI7D8KT0EzBVOfO8=,iv:BDByaP9SO22FcAJdbptzza9CpU70in7hqWsdvFFwIHY=,tag:RgVURTz4bDalO2hQGaNwcw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
