apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:Nv1BxYkrV/hLJuV1ReWX//i3RLx802IrgBLyoZoonrk9CIZjTe5co2aFtQdwByzHp5+XcXEvWNCh9finqtIO5NAG+04pXxTK40h4KpSXz6IUVUFYYBtfHais031MCJsKz7gBSOWwQk0HnAbiKfn+3NMmdZUZYeM6t8c1OA==,iv:ZqFWfr9Ji3iyqwDAkRKU56YSXvxDYj2NCZL8yhniT+8=,tag:y/JfcQH2L+9Zb9Gx8zSGWg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRGRDeldZMm1ZRHNrVUZX
            czNsTm1lbW9raTdKL3c2Q0VtZ2ZBTy9RYXpNCkJwOXFQL1Z1YTRUaHoreVJma1hV
            MGZaK0tnWVIwZTFUZGdobk8raVZ6VE0KLS0tIDEzOEt1Nnl3TEFPajRrbXNJSWFZ
            TFNJTG9ocjhjRCtRQXNJS3NSV2JqZXcK/HxGy6MioldwwjP1lW2PG72uo83P6EZu
            PrWIQ5s4YQXgkFE0O1eeHxrYRKFQYFIuPqZKKt0kKxsVBKsOrmsFrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T18:39:20Z"
    mac: ENC[AES256_GCM,data:bJUcujPswuaFgEk5ZRndHS2FNjUXcU7/+qkyVn7fiWb5T9pybSrCSrhn+kj9O+h3sU3Bz7xJXfX88gBh7OlUZoL4S7pIGBKIb9GkHTsd3JPcOGHJCO/zQYaO69t08ZmAkex7CnbaDNzF7TtQ39H2ixkSnHRQJr1s+mVsLRAfluA=,iv:WCO5YFYsm4YNZTKMOOP6AoJEZKYd2yJEwliHlFaR6MY=,tag:GPJDyKV4V8iQiL1TFVe2dA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
