apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:F7fD2C6IGHxLRN/OE7TRy7lxyGO6T4ZFEwtrQSL+/Xo+/iGcQaUTS3dBPXzAml69w2pmQyaK/M4055M9pIVl3llL5WeEdokZj5/VsfybR2ULh5xn0KMa3Hc0oxDrGSjvvjC2x2PlES7CvzjWxeMy6x+Gwf2RvqXeuJ0WKg==,iv:plcflJUgSrusD1IOucRLwqp7yBADwuSCZudnFTZ3Ytk=,tag:WpQRngvSx4aHZI2nauyoRg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERThoakxCK0FMeWRPYlNQ
            aHoycVRGaHhRV3BSSFRBL0tRTnMxYTNlMEVvCkx2NXhPNzdIODY4ZXh6c1FiUWZ6
            R09HTnJRenI4U29jMFR3c3owQnZ6MEUKLS0tIExhZC82bWNVRjhuWXUrMXlFS0NT
            dm5RVXZrT3paRmd6b1NaNlVNZTgzbFUKLbX3kVusqvVvXtDMJjUVFv7hWuUEPGcC
            GogU9xEebDQc0UCvzDxjQmSn4EtJSmpNlU5ua4dMYrVrbQoDM3snig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T00:32:20Z"
    mac: ENC[AES256_GCM,data:6/+i1Ywpa5zpIPkBWugljDgeT6ve6DuTx/NdSDVIF0jpiqcHaZEMMFNZ+vAjJ7I7v1JqBLz9dNn6KvZshuPUNxyr03SMhLoibB15uP0aU/oI8n23CjNUDzcgJyZjyV2kBf14xOg1YmUGBktzN/ODlwpl+liIVTlZuMwymKYgzpA=,iv:p4UVlsQAkAN0WMZp214q4hgJdQqJjVw8RWXeZqmKjA0=,tag:eKkzRUtz8iSVxjvaiqG4Rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
