apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:eMfmIK8MdnA0Nupsvk6xCjoa9VV/fFtbg0BYz09OXlmBGB+Idgtxd9Djobhwh3+p7E6vrINsQ1yPA7Fd5pHjxdHht33MfVQaamSxklKk8la6C5DZEYmZBTyuBXDfn9Ll+ya81zJejLwxhLZovwpAGNmZJQpdqxWs2YBZJw==,iv:reHp7gBdLOK+0SMsSP6CD0Id4igJuDzw5klvfWNfinI=,tag:FMvBDQkTR/pkhLdmlEFqpQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxc1dhZjV3Q0srRmlwc2ZK
            eHhjdmFRSGxQUjZjSDBQbFBpOWlvaFVIb1JVCmdBdmpjWEd4dHphZDRRL3NURUM4
            c1h4UmNKUEsranp2VWhOQWQ1ajVBaDAKLS0tIDZCOS9ESDFvbWhxRmxZT0FBdUhU
            OGhSWlIyNzg1M0dsOEJtOW5wUDJPbGcKYfmVqi9XXrMTIx9TSuya9tMWAHouaGqk
            xyggyvVVFOOztRtQ9RXt1jd/TuuuNveOHuoW25dvdSn03QQ883ajDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T16:08:29Z"
    mac: ENC[AES256_GCM,data:04xYdfetuuc5gr/hsD0XX0ZimCOyYi3DwvodYGfWO/MVqcL+/KF1R3R6d/OIF9AGICcx7W6tbQqBKXqTifC5Fm9np0VA+q0IetxRmDeJOqb8WE8UkA2HyM6Y5ISQVl8Y9glxVZlORkrJmFrnSstls4MClQyKq+iG+51YhtFz3kQ=,iv:kvnPGxIUyGfOItZPVDbf5BZThEAGSIY6SPXH3/j8FZw=,tag:Y3+tCKfDFEcQCZ7pPoJuRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
