apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:/FhWHjdECw21lVTqhQ+89KF1WEpB5an0nW0mQuQd5aP3wo0jPGS0RDOKOYDibeWrtANSPNQcQRf3u3X1DZa4ZhT/ms4J9IaoKEAHm3EhZ+FimJoqu5pKHMz8oSkVeOZtaKmKxDrXL53XZlh22XdrOTxXjBwnuXw/FyHYjA==,iv:MRudAcr46XpPnpGU39gblWk9Yxvu21fBJJkk5Lu4U0M=,tag:ygM62THa/3jONY7sX1sKFw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSkdwTkQ4WEZEZEhFQjFh
            Vm55NDhjdlNiUGJQYUwvbmg5RVpxZ1JuSVY4CjBCejY2ejZwV0Nxc2tPbU9XRjZP
            UmhSQkVmYVZDVlhGL0gvd2RhL0NoVDAKLS0tIGFWMmdnNlFOVlpsRllvUDlNS0p1
            LzdyaEJYWkRRRnFCSlB0K1pVVWNxWTQK8klO9EsZVIqzNQ1WK6uWh7xfuMSfWUIy
            OT4UgdtWs3AkR30P/yzjCrjMp3s+OT1QFacaWQwZL1qOYS18tLk1Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T21:37:21Z"
    mac: ENC[AES256_GCM,data:qtd1DnTIYe30iw1zwUN6N/EXwJHDxdXfF7hbLmfzhHtk4kabu5QAIcpcY2LQ441CvbvGY+ORaNtx7h2owIYSx7brbqBDEtqhJls9jW6vi2FAw8PNegDeAeJrilYgp8C+3hDjFjx3bk5CAN7gHJhRvyanuqn3bclvx5taVZmyWek=,iv:TWreysA18581hg0DZ0pJuNNlvbsV/ZVXPpEzqY0nBlw=,tag:KCXf+ZclPTHVsjtgYylphQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
