apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:OiJc70+qL8xSX+6Ju6/6ZaZ7uWXzba3//TkuCtRoMXDsxfKHcbHJFBHrVAK5HKQ4jgfYPvY/YHJoPpgXxpiRQmaTTb2GDepuqr37CZv5rKadvLCo0Mf+vboO20b2BeahMS6ksSHpNF+0AsECsb5egA3Z+hKE7KvEeIUOZQ==,iv:A3JKUQCbOGJUb9eL8Y7+wNFWH3qem1H6MXC8SOwVx/g=,tag:TfaMUcqLM1fFjKpbbTHBkA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRmpndVMrNVpXdUlEVUJr
            ZlZDRU55YzdVYzB2NVpJSm5aMFFmY2s3R0dZCmpvWHhBNWZtcFlqUGdtMWFXci9L
            QlJVcHNCTjNucDRSUFMyaUY1YW1heGsKLS0tIE5jTi9QdGEwaENiSG1oWWs3SWlt
            V3pEYlVnU054eCtocXJodVV6azE5VW8KMy5qBznhiiZlEFFR5P0IRDnZD3bSy91c
            +shAXBTRzR3Ok9Iorpcz3bHFl4ZRUVSc4U1H2ndaNMWQnm00PgcadA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T05:18:28Z"
    mac: ENC[AES256_GCM,data:3ZDvlzvu/zy0V8LNSdzYyCrRjFlSZcN8DfObyGRw1tRebf5sxUzuubAJSJHlsQavU1rB8v3h0sNF+ZGEf5ooBbHJ7xJj7lzoEJFfzIBcdiJZXowq1a2SidAndYWLl1USl98/Eg7BDvFV0G0x5b0+fzxNanxbPb/GgTbJS+oFAgc=,iv:x/FmwxjNVPG2xzep6xKJztJHmP5o2uJ/6tzeasBBJcY=,tag:4g+DtpbQAujqb27UkrNUJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
