apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:vWZQqBF0OVDGVV7nYseT80s1L9ea+J9kgC8RA79XDdiFoOYe80cfgXAcyMoDQ7sXgkulZ57t7QgnmivnUreTXXgUoUDbcx6Y9XWN1mLjlFoqDCwet3j54mTXmFORLfyzB5oVCbFkM0sOm/zWmyhnaXDKP45l0JDlkL+zSg==,iv:P9qtUgi2kluBXulpzjTd9PJgZ1TIlP+SBGUUFieaFy0=,tag:oNQYlJoMjXJJAF2xzHvWPg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByamtlVmJxaFFLTkVjRVpN
            K3pTcll2cTc1M3hoemhMSllvdTNxQWhGY3pnClgxRHZmakxzZjlrZ3dmc0lObEpF
            WlZGcC84WmVzalppSTlMYjdwcDgzZFUKLS0tIEpLeEFGVHpwSXkyOTkzVDBPbDdt
            VGVXS1ZoUU82LzZBRkh2NnR4b0R4bXcKj/rVXkZVaEjAX5ykn2xVBUG4fZUutMI3
            Qpg7o81AhpL+8NKsukyzT2Itvab+JJraBbdiENPFG0mDQ07lhX/omA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T16:36:50Z"
    mac: ENC[AES256_GCM,data:Bx5Iir7AMZGn1Qc1bI7viJvIicIlL8IT0vgqe5syEhYZL1NQsrVF1ive+krVk82AIUb9bajDLE6nqwHRpAbMiASj4RPwp/u36f80uxd9q+bFjYxo0UOp3u6lnIsnmP5z7RLWPl2GJAsJAObZaS4cmxuMZNRPK0b3tXIMan8RwwU=,iv:AZuzICfSn9UbkdoNbfHZaHMFiLkSfHJN5/5N1dupTZM=,tag:Sob4Ee1GKR8jIcoGmLqrdw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
