apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:u+QE3FsXI8qVj4tWPtw8scvGCn77sWV79sLjM7Akk2JaGwfMZQtMyangXVE58CgBcb2RQcGWb6lNooLcGyti5g8vOpSOiVjgvyI8jtxrUo07Zeh9H0LgMDJGR8fgDbnLTipRMceQBTRs7X+MNPL6XWVwauVst9jBk5/mmQ==,iv:KNrsaBowMpZfoxM4x78Nwt98RWw8FHYdeVHrnNC7ZPs=,tag:m/6XORtxe0V5recez5iaUw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdms5ZG1wMjkvSzFwSkgy
            blJGRU4zYmFJcjF5ME9oR2RXcHZtNFhJQmhVCjY5RmduNU1iYWJMRWtmWm1oai8z
            SmFTZGQrQWpRTG9CbnMzcm5xeklqb00KLS0tIGdOMStIYytMMzgrVUdoclVNMUtU
            bDBhTWd5QVUrYUtDTkUwalpKRWlUeTQKOO5rPwrFeeeB+Xb3tAXfN3hvCSEvsQkZ
            I/J45neOAMgZ3lVn4jl8U18aIYa9I06s48npfpOmsPmiXTylvoKC9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T21:44:12Z"
    mac: ENC[AES256_GCM,data:BhTYa/pAJ5zr1gDA+zmAhdFEHQESfSrIQvgpzuxecuQoJ3YVTxaSRQRG2UXHjVB1Nx+Bnsj5W07zQBPDM4YAWw2xmfEL+COSxGXmnhE1aIZIb7Xdh8AGvrd6DLYTkTIscFsYxDHSj0sSrfCMJIoZeOxwDvPsFCplZ6u3RD934G0=,iv:mDo6dMn6oUGkz4dRWRgD8oIfqphJz1dimPjfeMkV6ss=,tag:CvuzGndDC3nEGYZiKgtntg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
