apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:JNP/8jmhHEh2e2v4WhJeAySzlN0yBOmOD3KzOsGGTgb9I/h6TDkGAuLjXntlqX0qOMaYZglwVqhW1LbClOx2Vi39VxVaNOzcjmMsMoqnjWGaBpsY2wrARH7Rp/Ap49wa1yzWczJzq89ZgFA2e0RGn7ighEOv+xkJw46RhQ==,iv:sNHD8IddrorlUDvzdwna1u3hi4UGUnjig7yduAHuPfw=,tag:bhfW73J5Od2nGfUEVum6dA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3S053Sm1CcGt1cXJrSjg3
            WlM3S3ZaMkEvc1pvU25SK2JoQ1RsbmVCY1IwCmFMRCtkRVREUDgyQUdOVTMraHJK
            cnc2UjNxanMzN2VIaEZsK09FZzJFSzQKLS0tIGx6RzhkZnJuWHZMSjhpOUYxNEhX
            a3AwK0h2OEhZeTM4dlVxSVZTZXNESmcK85UYod2GzCeQkBcRwYtFxkzRYnNxjHA/
            AWc2YuSzEaR2/M2vL6YHNTniY3TlhraujqCjzxFFWntSWOu6cD/+OQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T01:03:24Z"
    mac: ENC[AES256_GCM,data:ATPKPbxdG3wXINlAsFazgPJO4VgQ8FJ/QhwmroM21DHWXb5TfX7A2Fnt3vDfnYDYseYqn0y2b29HEuJpSLqP/nlDSVeSlhtDiaabQJ0Fg7C91L63dO2BeZPlHchct2t5Ej4UQgoZ+Vq2zSwugTYKpleLogVv1+DW6LVVPj5d/0E=,iv:5gn7v7kHYAi6SGtjt+UwwkMACXfpCWn4t9IfqpbdVj0=,tag:KT6nPmNPyDVtUz/3KdUWdw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
