apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:gQIi/8DzoxiIsXzS+ZQ0DSOhzTC/R/spmMlYodpC4RYt/09iv6XsmflUAUynepAEDYMDqHt+XA3BCyuCvchY5DjgZSZP9VAUqPgiT+1kozUWWiFRd6+jOzGHuil3nMLUUohqrrppzso92KQSWyDdtmj0ahBpf+P3K9L3kg==,iv:W0NfhgWvDFLujaYzZcuUIpIt9WTKWOaHCP6DIgaYKD0=,tag:rGM6b74W+bhEbWOhp7Lz/g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaR3cxaEw0RSt5RFBEK2xJ
            b3RQRGRYbURHeno0YmdCK1pnelBoaG9acmtJClBvU0pyazI3dkhrQkRCSzYwaWdQ
            VFM4WW13RnNRaUliM2htcWxVT0V2UlkKLS0tIC9BeFA2aVRyKzEyblZ3blZmcFZH
            Ty9qbzdDQ3NxckVUV0FHLzV0bUZaa1kKbv+v8peDvDfQZ93mJL6EfTPQTHOy90n7
            8O41PvP5hwft8AurwWdeRW9/054MuRHZh5kg1H1Q5Ay9i7hevJMlrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T20:55:07Z"
    mac: ENC[AES256_GCM,data:wOEtKRyxUa8xTIwrJru89+MrA5QcpANkud4EuDCr8bcne67DZzaaTo5OQEYOOd0Viwybnx47dyx0zp6PK5ZpIuymP/ZItXtr93PDbNtOo9jwpHM1LQRNbQZon4MTD78zU3TjISksMVspd0AVptMWgHC1PaFFjGCrJqIkQD0lnLE=,iv:JGhrkdsTksXIbfuju9IQnJWKpnr8SuerqLDA+J5MvkM=,tag:+kDsblGLcVteA99RFmYzyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
