apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:vkEZcfA5D4wFG1qap3VP/EXv8rIXiXS4IpvT9sGLK1U1hbvZq+3hZjEXu6s2fnJoTpRtaYYw4Sjvhh+Wh+hvsQN5kdAWBbhjdP0hb5QPg7RBa8wwuRDHi3oIwP6mxjNCYU7azkC82+k1xyEQ8idlFUEFgi2v1z2rRtxVmA==,iv:F5sr6knLVlZEtm12KKmXypqbu/Eo0NH3u8zl8kKoeRw=,tag:XPuUzu3mVJVb46DY0QbTxg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidzdQL1ljVGU2MnhMcndw
            eW55SjYrejhDaTllZXBZTmQvcjVRWm1SMEUwCjZ0RzFDWVVPTm0vdDRiZEwxMHBt
            ZDliUGZOeS9KVlZqc0t4UWladFd5SzQKLS0tIG83R0M0SjJBSnNnNzVPOCtNTy9m
            dXhuVnpDWEQwUjlZWFR0ZUlPalBEN2sKMpam6SLV4vTFa7vy8pS7/8RfOstUDBZr
            FajpOHsQJPwZ5WTYGRhNMjRhgmXQlesyzDGlf++e7sMwArxtlY6xAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T04:04:28Z"
    mac: ENC[AES256_GCM,data:avmQ5swwl4PaijAxuLiYQXFHgIK1yXAJLX6ZxqNkcIpUvhBag8Ig8OWRvfk99PPBvEfdCZBTU9zn1KMncicF9iBEwy8x685xWx5L45AVPk6hnHO+z2Wjf7GVDPPFw/UF+7CNaKWly8uXhs3lUU4hlipPKgG2tro5waahUk3da+k=,iv:U+nxcLllvAORfEqWPx+/0T2+tXj9TcAcS2jtmSsSOjc=,tag:CHM5VVF3u2j0cV0tZ3s/jg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
