apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:9m6dE9EHJKszAR715rufdlYgBhR9zmkKY0MPFoiHAcnjCtu0kcU4JfUMnrrVzB2ehr0aNA3PvjiBNobuBKq0M10ERhf5ynz4c1IVb3DUur2PHSHCZFlx7bi3SrGLoenBlLtvvAtbiogRaxW3zqzMgOjlx7cGh8bWAwLK9Q==,iv:qQ+Is6ctFUGLHdVdP3PnJCw1PLd5U98NxZf+8Aca/eA=,tag:JbUZF5/SrLM+6nb9ba/LJQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RHh2TFJkaDY3ampidG03
            Z3JSWTh0Y3IzSEp2N3MrcFlZaUxteW5hVmtJCmlRS0dXMW04c29IUWRYbDlxUVR3
            d3BWYngxdmRHb2VhaTdqU3hGdnovZ2cKLS0tIHFWLzZCeXhob3g3WXBzNDJFWHVE
            NWdFMVY3NFYvTlNlSUF5SVQra2VaU0EKeRzkA6DkNGaYGlH1mFNXmNMug4IJeqyM
            5JrnBUXKnjjmfWVwaDqT4Af80ahiv3Fwvvqp9qoWVbkpePiE5UavCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T04:35:27Z"
    mac: ENC[AES256_GCM,data:AGr4a8PHXpATP7WV8U3JyGjY1K02tu6sTUnZn3onortcqVBbhJwP/gr4INZmvNarD88rhDoRFYq5/O9DLhwwXWWmOBiyxekVww2lvImbHda2y+uL3aB/hIS4729+oJ1TKk5KwycNnsjrPpvvZjA9AIyolxffXw4GjNxFExmpfGw=,iv:DFZo3Q+I+hbqPZngr+M2nFCuWRIo2S8pDeQ+sLDp1Ok=,tag:zunrpnfJPimRPH1rSoVAow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
