apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:GTRMCmBNTtUdJZTkhuxe6VUUbg1yFq3G57wYUCdazuftOrQamf1/0DGxE0RF0uZ/bTU+1Fquk8e4dJ92lP1GfM6oOuAvsNYozG/csOTRDjypSPdneCVJeRaxSxzL6tf47jw+vv/oCWIdxYz+3lt18KpoWZBNAzlG2UHwcw==,iv:k+66wBdrqJXLEiAweKFue1rIEU9rRcDVPg4s35dFI1s=,tag:NlPorDeXfkUv7GNxmsUGFg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWlF5ckpQb2FUWld1TS91
            MktabUhsZUdyTlgvY0p6Z1pNaFRuV2RCWVZFCnFTZE8rQk8xM3dmZXdrajZhNllY
            bTBYeGhYN1NFU1RpM1UwSE5uN2EwSmcKLS0tIDlBcEF3aGM3Mk94eW95REZjd0Ju
            WGp3cE94MEk4c1dCemk5Nks0WmN6VmMKnR5aCgF6nPtD52PHYI2NR9PNg6edthc+
            9c1gdzvP/RXJAnJfFUBpw2o9yKGvW5+lFiB+Awo4BHK0ARxBjDa51g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T12:26:37Z"
    mac: ENC[AES256_GCM,data:+hSClrLN1WanpTiSl2bPVHlrG6nGryjOAHCi3EaiZ8l+H/7r0zLJEheNFA+0gga9TxW6vGJQpYTa9sxrBfndkRk/ct3Om+XMA7ifOL7ec8pscJBirtjVN4tGg0IMhBBAAvwZe/IVNXp74yB5qw0W+IczsvCo02Jga0Bx5+YBdj8=,iv:8ei8vOdYd4k4AIYVyNsD7dqkIzYNHMJ8AyhT1z3gV7s=,tag:7tfjicOngTX4rjzNbg7YaA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
