apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:G1OVsLfm7/dTXhmxJEJwummXADzkjH94/6w/+84kUeFgBjBJ1/9uR3Z3uniXcNuCTYMS7sZAanp9n8EDrODqQGXClk6m5cBknEIaYHuwhOIHgYlo05eCd0mYaRGoGlSeH+KFP1GvFX5gAorcBEj3TS2ND/+RVKN06YTkJg==,iv:MeqMH0KVKY9og2TQ1SITJry13TuZV8q+oFgrl2kbq/0=,tag:ryu0Mk8IKkfEE/CA8rjAJQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArenJPZVdiR0xLM3JGTTEv
            ZGRrU3NQMndzN3NiaTM1d3VLV1lDMU5NUnl3CkNZbGx3UHBVcmxjME40R3A0bUVO
            djU1N0JGbGZYbXFaaFlnbHdwYytLQkUKLS0tIHNIWnR6TkUzaXNMeHJNV0U5MUk5
            d3hSc1lFVlQ0dFArMDZ6bXMwTmkzS2MKcNRkjXW7Uk39SGqVkCJiilOU7a9AzDMU
            939prxbNyl3WQJSM7jrYPNzlsUEiVYQ2pf3dMUe3tvnP71wBuTK2IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T12:46:41Z"
    mac: ENC[AES256_GCM,data:tIymi/zZ5590yAtPd4Xy8fXYOrxYEHayh7BIqc8s2QDuIE9d7qa73a6xh2nxe2JMhAyHsjaOSCFrcuoI3bvdsrW7W9h3XRzLpm33A/IVeWFQCcGqEXgu9Or7d8uQ84qHZ06SNOlgAWhvj7y/RzCmbnV04DgAQWF+94xKa3yLzmE=,iv:0nnyMdQEmLx3gAMp7XuL24UaldqenIV3jiKr8Kwx8aI=,tag:dqpudZu01P8XKYPSoPOOew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
