apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:esHDXrOyFQQ5VZuJ2uFsKKMwolhSaLNVSpMJFyTAEcxCGBZg/4yPNIwIebiUPtKIWL/bvabU8eNh2mWCKqiLLBi1aIFyqrUl8xpG0728tBkhmyojugFTkpYXTUWg9qIcsEBwvLIrpIZCKjc0UmRRT12JrzdN+VFNrw0/iw==,iv:WdkdECnCFY7yGfwds8Jrp/b0392o4B4GKdqUvW3599E=,tag:H6o6g3HfvMNm5gRfiVYPzA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJM1dVeEVwNlFpeTZWemtU
            eHZBR29xcWZJMDl4bC9CUjFvK01JTGpmWEJNCkhpa2hzTlRXelVBQ0FHamVNWEhN
            YStzVk81WitOSDhnSTZXQUsyNzBCRTAKLS0tIEJsaXp5Q0RRekhGSEMrZkE0UEgz
            MlZQeHQ2YllCT01vUERiU3Y3M2xNS0UK+6PsWUsXxxF3NS8ImIXOZV/9laiQpzGH
            Z4SNUUExt7HPbDS90k8JzQKdYr9GNGhfX1wp9/o53UvDbV4+N/46xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T02:21:21Z"
    mac: ENC[AES256_GCM,data:wNE8jw04az47eVkL+dm+8ZWuIcwP0m6YM2fkSjpaFcs4sAqpSPY+0uIvM9ZY80s14QqseIYZx3ce+8bjamvTL6Py4n8GM9p/jq7szf607fX6YqpSkDT8yA+X8JsIbrKksK8BdPNyGRl/WewtIv+HF7Uv4+GVqBTRJtilGe4+FmE=,iv:hjZ7iEgWtf/pwo4CuQdX7LnQXcVjJWjN66m8OEumTsQ=,tag:yJRfdpJghhnUxVHaPqpBBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
