apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:dpD8MxTbD8uLAJRR5uN5gFb+P0kK8RNPzybSGffNO3rCaUjtR/GU1VhP5i4Aca4G3YbH2LwtxALjuAHHbLKph3M9qUxCVnDU1Xxf0xPhI1mhNoZVcEkBV1hi9JXdzYskTgoJq5dSyevinEucwjAOgCTsN3Muu5ofLJqq9g==,iv:IN3HLtY9W5mqSOmG9Nc6FQmr+K37NfGOWCyZKzoJFNc=,tag:QavpFMjc/5dVhKcN1/WEIw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJazl3dXN6QXY1L1QyaFpy
            QkZvbjJOdHQ2TU0veGEvOFR6dlVnNWVsT0FFCnRqTW9BMmZERUdJc0tKL0lkL1FV
            NmFubXp4bFpVcTJTYThTQW9ReGdXZ1UKLS0tIHY5djRSTiszSGpNSDVsMWJ6dXdH
            SHBjZWE5WlZuVDBqL0NicmUyRWVpNnMKmHlkQI+cAz4d8IUQ3gYzbKL3RV54rpd+
            LbDfymX18K3NcRJlpsCt3cosqeSRcz1AULpiRhbzER0NujVNSdIbLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T01:57:38Z"
    mac: ENC[AES256_GCM,data:bLyf4SP/kqXLdZG94JpeoZz+y8ER4miIcMqlPbueN4zsogYGDNsLG8hhJyk5Sv/xX++q/rA9lclOJY/TLNbiyI4ww+sR3Acc4qqoj+0PBaTJjDzdn5aQHswyRu+rC8HbhFkWnt2nQoNCo2ZRDhIXOmkETZ8j6VC52THQvSlZO2M=,iv:+m8W82k6WoYWudqgG0lpF3QZy5TV8mmcza63ZA/+x78=,tag:LbFVu8EyaK6Y/HZ+32pusQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
