apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:8tQzybEQVI04fcz6t4yBQLIHe/1kAfVbKdIfTQq4wFOGeA6xdu1bUV1aMOHWSyhnn27L2I82jr3T0bWW4rdJWfPHjDWXr8uncD+6xGFarRgmOlMfK3uZvoqM+uKhnx3DO3CYG/61injo17jAXGKHDQFyBL5BMRPbNBLXxQ==,iv:hop2Rpx8G+giF/xCUa7pfZH9zZUcFPFujgZz0TlmiUQ=,tag:mwvRrnlkfMJqMy7Bw/oTkQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUXNOeUdGNzBSN01aL2Vt
            NVhrMjhwb0VMUG9QL08zdDhLdmJWREpTR2tnCklucTVMaTVuQ28xMUdaSnZnenJO
            SW16aWpIZk5NTG1qTHlOSUpMaHYxVEkKLS0tIEhRMHB0Nks3SnB0Y0dSL1JxQ1Mx
            T1pUaWFyWGNRNm1paGlOdDdZSUZRcncKBiyBnio87hLXnF9oN7tzu6PGZ6KN4113
            jTcnIdF2hmpDB0VvE9ff7YCPuaYUQg/2DpHapA+QEcsjkMGnYyihNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T08:52:17Z"
    mac: ENC[AES256_GCM,data:9JCK1tb+0RCnAO4FC62OZqlw4EsZ2hCpZiEYNgBqYjCUiQDe0f1F3OYbIu2EHSy5zCb/MpJcX/u+IjV+Kx/r/0JbBQulUM42w3XXI8b1g8iODgOhcXqqHT5A8k79Bynvk5YmSTKFQP1BrRdICsTnWNnGaNyoBzGvKWWwmRgfrQU=,iv:x/uWR1jUBejn/JG4M82Z3i3YF65hotAUfP48tGkuG3Q=,tag:gsmhz7cuuMUlgUnAOLKmUg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
