apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:gvmLf78AEc8pBdyRA0TAdn9q8JXk7B3Se7w0GVmfK5J9PNm34y1WmlW/fRgEP9AuyRCKmIYpa/NHpkyC/TAtQ24EeZ7YvhAt1NQqTDVmYcATSGWWs73I3LsxRarrQSQzbjgKxIurwlnl8L8dOycWUvEMC9qtmY6PhgOQGw==,iv:p1/pL5iWJDWRTFGZBKXjLmxF/LznzgZ7+MC/58YQe7w=,tag:f62mS4u2ig+sxqbyKK8bJQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUCsxbzQ2TlZ3VWtIK2Z3
            Y0U2WnJicFZjWXEwOFZESXBFZlhSczF2UVJFCkVnU3JrWU82QjArem5tT09MS3kw
            NVNFazRHQjZkcnpNUTNZNk1jZlZoZE0KLS0tIEVpQmZkbTVJQ24reldRaFpmN0Q1
            Y0l5OUk5ZERDaENtakljcnFqeXp5VzAKvikeqjamYFGFGk+Wn6y6adZPyD+N7hw3
            4K30x+IwXYzf67DkZldBsMh8x/kzV1SdtDaSxq08XFSPXvVjrZ2TBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T03:29:57Z"
    mac: ENC[AES256_GCM,data:pKEZZKVJMuOxaKal/OeUp98ixJShmiuofzwVM/MpaGpNuEh2ka3+3Tw9gklDx407scZmTWKUTnWie8GzPTWaqT44n+y1SM0YM08Lzj//Njd7EVqG2ylOXXyQ/mXFWySF5lUr/l2nA+vqpZnHEWiTTYXB1CHM0LUHXXaRqVgVu3A=,iv:TRJMIclcMndoHVsQEgQm2fqfZ44i79w6WNRTnMOuN80=,tag:RqlVVp2ok0VJ98esd0IPMQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
