apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:IS0ehvUqKUnOI5rQt+QZ8OEBlLaiFAUDUZouttN/kax+peMcHkPVDO06BPD03IXExyIuk650ALphbtvR2IN2pZKlignGPOfy0fSX+uZuGKRbl6b2PDm5nnaZKBrnd/V39FMZl9DYhcuY57pYaNMy0hb4sUOl19CR2TARTw==,iv:SO2nDSZ5fqJSgJvN3bxuTOaUYGKQEcZJFno54GaJSHs=,tag:/oXwoEyY3KORSY3Rwn6DnQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbEJpUWx5dWE1d3ZRYnJW
            eFNsdUo1RUVERk1KVjVOeWViSm8ybnY0b0VjCjZGU1VzaDlIdmU3NTBRNXdnZlFq
            aGdhWll0cUtlVEg2VGNNWWdsRXlnZU0KLS0tIGZ6TmNQQ1dqNElzKzd3czRUN3RE
            elpBTTlQYUJETG4zMmRXcXVvVzRkTTgKODj2Ht8CVgLr9guClnP2Fsyiof8+Sb6Y
            wQ6CXl0EdcEw5VaVDR91fmB5BB9tHSxmezvg91K8u8MPzAjhMmVHOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T04:46:51Z"
    mac: ENC[AES256_GCM,data:Z6BF43HIijRbRXs751Qg9no+yu52q08iU2XhENIIrJyVPLczs8XozRMfyK7Psdj4GQ1mM7tYLWzqKYvfsfQT/Zs7d9QoNlkaUmSLzWTUPRr7+T9vXcCum4kgC8T9p4SP1Qc+/yMeQhGWu32b/WAl1glqHI1LRRmJsvBlK+Bi+rE=,iv:2gSnMSeUlpuveHtgzn/jvw6wMFtxN7YVH9+TDFgYAhM=,tag:BPoSKyGXzqmelrMCR4MebQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
