apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:XqWmnp5vDAKabf/wgyrQOEHno583wlFZUxC0k1IbAhAMQgWTik+xuxGgl+beWVRBNLuu7YagV2SjfhzrO36GGziBuJchPeFmSKtV1ogUt0yPpZqqwa469DtDOI9os+Bw2IA58u8wPFTs0zMwhqxfiEvz88iiIUnnMGrayA==,iv:s3d+DzlHFhqsUF8wJPS1wNAlqsB/E9bt9UgxwdlCrLU=,tag:GbR9wWqLKXae0jevpITiyA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWM3NmNm5EY2FWcitPdWgv
            VGllT2xsc21BNU1VN0pwcHFIQXFBeSs2Q0ZnCnR6dkNMQm44Z0Z4ckZiWkdZT3VU
            cGlMSlJCUDJuMG9TcG5TNVVDcTlSWVkKLS0tIE1ZUmcrUVlYR2NyaFpNcnZ2R2E5
            VGE0TUVnaDIranlSRWYzWjFTQXIwbjQKD0gxi6YQm3/olaO8n6Obe1KyxQYLtg8D
            YWqVRiCCOS5O1DfKLrmj9hFWPIFTX14g3n9nj+/Np1Nk4wvcJYGdpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T03:07:03Z"
    mac: ENC[AES256_GCM,data:rVLonYT2s7dS/sVLQvGUMVUgTdK/NWxkOGGBC/BiDL1GevU4tYp18U9hGXgQGrhevjfN6QPSxFDJJ1dXCtV2BXU3RnaDYSvBuvQra3zVGOErfDwoezl0v7YutD/8J2EriLLKkhDjcryEDWyq4OZXrdWmHBTly4r0Tu7ovPt8Hy8=,iv:wXnff4YqPlpnTLFO2OAffy9/1JY5UV+zxcuXef098Ts=,tag:eoPu9YcTUTn/iwQsNLJHvA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
