apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:lGcoMgjLQOwpV9sny7I5oH3u4LePXbOYRL3Uau4wcx6/jioi1gcfwP0re71YYEaCmLi4I83dlfeKBaZMoD0hLdWfx+mdhv8+mbOHnBfb/b9Z2znYZQ7qVNhBGYtoaSjkV0iPYXs1X3iQxWTQ0pluvhqf2SRKjItpla3Lxg==,iv:r2jWoieECbJC8PQke6ho+jLWog+yEZ3MnByQqycHrvQ=,tag:ZfnLFiCnVDlyvXI+oGoSAA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Rm0vZWhOMUFMb1NlcUZP
            TnZya1NtaXNFMkIwMEFBeFBESTRUSFlGdmlzCkhRY0lYbzV1NFh5MXVBZ1IzTElF
            ZHZHUjc4MHF2ZnNrTGlVdFJhQUJEYTQKLS0tIE4wOUlnZHFnMEFqRE1JeU5BOXZE
            UFNnWjVHU0hoVm9EKzZDQXk1aGhRcXcKx1cPd8RhuON3PH8e6KM45V3D8gLDQJ5a
            bBhYiq3Hxyri5J4ejrzqAMAGAROkPBx9NaTPza8DQ+PvbFABZZyeBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T20:48:11Z"
    mac: ENC[AES256_GCM,data:LQnUqOJNtbYbufL3K2AzkbhyOUS2W2/zqq8CTvlTMkgsNiGzkhC2O4MLmQZjwBJgMFkzXpEIJsRFhPEAoOebSVX83o1knO1TeTnYSEt0YetDCoR1lNRsEVKPv9BhrjjKYb2UZp+oQTTNnYcA4lSd5e+uPkAo054V8Hyibj55YKY=,iv:hvNJpqnKPoHrtN1PimbduCahhxtBmPHdgzv+ePl8xlI=,tag:Iii7BtmzX7t1Wz4bM9Ihnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
