apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:AeaedwenS0tzYlhfM7eA+ELZiDfLJJqP2a8b/BfO/4gFqWSDt6Dp6GT86td90/PSGwoifyPLOCFRMTd6+iJWa3X0LlckPz6ofhwp1hSq68hAvKHsIf/N2l042dKKCRXSIBIRfIxELUIxR7NFnA4ei6QYWcLAK5ZhZCOd5g==,iv:3HPiQsEebDcDeyxi0GsPi8td9IQIaCWrg1Ab0PLiakI=,tag:GK+lwpWQZP7RYNKi5D2Lyg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPT3RXSTAwZ04xeU5ESG9O
            Um5wRnhCb1habTNVUmw1NElNLzdqT3BBWTBzCnpWRWRzTVRORWllRTYvVE14T2s4
            andwV1ZvR201azltN2FQcG56R0IrWGMKLS0tIDJ0NUEvdkE1blVYU2FLUDlORWgz
            RFBsVFFITENMTzhOV3RsZGFBOVowN1EKPiNDhEp+dRrKUSiaN6UwJQhXkpMe0AKP
            b6TeVS2VctBxC48SKi5uE/2HwSi1KpvnC98tRzBMt+98ZyD6zx5k3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T13:02:18Z"
    mac: ENC[AES256_GCM,data:WAqEPhaiDbOPZ6lxLcdh0IvPJoLpjXBFslPwNjiLbkFdWh636ZvwE5KVZtlhJpefNC/1KfiIFBnG4uPdTsHTOarZfwavV64sU0QDh/o0KgsHXJxrStccQKSrAwKUOs1m3B0n5KJD5LDc0HG5FNGd2qiL+PvPvoowdD1b7DU/Q4k=,iv:a85VdkJZEoR98cO9/P0sCpsABCf38t+lgJZ5QOz5vpg=,tag:TVx1b07odvWDgyhHGazBiA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
