apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:W4Wdbw0Mpeec/Z7C1ngSO78baKqnoolvetJznsYYXcMZBny6Isk4KqE07TmroD0Rfwi2s1RQQkBJH21I86j8cow/Scu3pjWmh0CKk6rKoIvPxRneLOW1gaa+6VbistoMwcQuOKXSGYypEK2NKwPmIPLqg4DU/B4LZlVdJg==,iv:jRRnPbyLezXdxxsRJl9UfwfPCKCU0OAykrDrMqwEhqs=,tag:+aoQK88jtEkgHLcs6p2wCA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bzU0UTN2YzQwdkFadHBT
            VHB2UlB2ZTdOaFluQmdWTUFOYkwwb1MzQ2lFCm9ERy9YNVpBd1BSNm1vcElSQmgv
            d2JTOTNUc1pVK0dKOEo4b3YyU0NSYjAKLS0tIFRlU1hCVFRoTkVuZ1N1TElPdFhR
            M3J1bUwwZmk1MkRXeUtrTE82a3VRaDAKg5/HpI5yMHMxKcYRWFLzvaL+cCT+OMYa
            I9NFGC2ewmNlq9ipwinyfbofnTREZGAJk+k3049zm0DrwAsWkcyH0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T18:52:13Z"
    mac: ENC[AES256_GCM,data:f4g6unHXn1QaDtOzgmQH3uuB4jjloJlg41DDSmfejXDuc3KBfYJtzv7U5sPnBjtnZ8Vjiz84vlOw8R4JHJpBsdu+YyqiBTkUenOMjN9geuz9lmRDrJr4NqRm66tHDWeydD8te1MfOFkX29vr0e/NVyEmWEwIYBLWi0TVMW9PZeg=,iv:WzjcgEtOfM0ubWLqI31rEXEIHRnkeLlvMB55OFEV5Xs=,tag:mMt0EavgWjNc0xNs8hK7nA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
