apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:0qppajFoxE1dx8ey6oVA5r1z5vPGRp0g0RvZ4ZjHpI7Il2gi6O+xTy/2SZJ27eN2U/y6Df8na2zK3zx5h/uDwt4jVzXIl961nBhS9lVw6Vig/MBaxrAMh+fT4jtXxXhkltASE99UlIgcfKQAq3Z7H8ZZSewdO0OcY0JUNw==,iv:osL/WtW6RuaAwQ9J5Y9qwHNKWIl9M/L2mZvFOCF4JMk=,tag:QpF0mELGl7DaGIKsmkgbNw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMzk3Z2doSW9Ja3BhM0Vq
            S1d0WjFDS3JwSlRRT2lMNmMxMTFXRmFnUnhVClBndU5KWFdKczNLV29RSldVZlBn
            dUJlLzBBbUV4Vll6a055SEVramdJc2cKLS0tIG8vTm12czZJbys0SzBwYldSOVFt
            TnhJZjlaR3hteVdWWkFGN3JSelJHM2MKDY8GZNgQiV0r1wG1wGZ+LRhEQHi5lcn8
            xm/NuXO9PpUgoTROs5oUrrDwkP1XN9x1rvV0K4VnuOYtnUUmOWq8lA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T03:24:24Z"
    mac: ENC[AES256_GCM,data:o949IIA+1GoSLX1fUPxQ0n3OagjfvBGFHu3IvEQ7M6YJcFOh4lHSEHQJRLSjCNiLP+gEPDUBrXfux2h4K5lp30efsCyNWUnaWbqgnfpkOZl4krGa+qefh2paMLh9ieXfC5GPRNp6olP1M7aw7QZPepVv3AsjtbTa0d8v2qSOhtc=,iv:4oX+3dKRC2JjbgaMOI1ypyiw0dOq4T1fejgE/nGtgSk=,tag:xbABCzHjo9IgLpZMcFoNKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
