apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:HuZqGaX/qN0zHkpzr9lcXaET0qp26/toF52ZvCmbPd+BC/AaL3b/c1QZm58PKAvmQkdINqW5fEe7cE6Ne9pf+3pW451g+n23jVRYzxejGRZX2TvhzF58Z/Not/LjGH2YuRpsbWZ0Opck3SxMQQzrDsvSzM1tENOpeMbU8Q==,iv:7xEj/JSlCY/cz+cUEn7re7uNYb0sUNOzSfIB8cKaayM=,tag:2PmyLLtLYJqWt4mEnie7ZA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4S2NxLzFLcWJnalZJYjNl
            Z2VwSEt3NWk3YVNTV2ZrajZXakphVHJsVEdVCm5MNElQdjhRd0MyaWNzWVdJYll2
            RGlzdG1wZkxUY3pwa1o5QU1zN0k1djgKLS0tIG45S09YTHJaYlhYdVp2MDZUbGtK
            ajVESDY1RUY4OWg4QmJQa2oyUllGd2cKJmuenfH4RJffo8kQgM9mHcIc4O6CnFu3
            0o01Q/h5TsD9cTcPp9dVHjkiMLWxl/RdzqV5LWcMOnbXyC3pZMpkWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T02:30:19Z"
    mac: ENC[AES256_GCM,data:/EZFZ1Hg9CyFVxbRU/dKlc/hyyegJN9cUWiJqMO8iROO10+NPfYz0Abx/uMH5RKoEuX5GC6pynyGXDUpHsx2gGK0HpXeEjJa1weWvZbq03n0ZFCxy3MmcAtxLAM90hzFqnjLlrXPakZoqN4tXK2CXwQVX2LeuzIWdElRfw3r94A=,iv:R/islFphCGI96Q9m8UQCuuLacT8bkaG/5htzS8xRgSc=,tag:qFsW4x40IC0OWY0n0R21UA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
