apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:JiLaN+lXiwXJvhUEPAKD8z/VKqMHUD5s01urspdT7oKEp/90xOwBrdJYRWuM/P3sAhl8BiBuslnL7H34Btft6hjhIxyJ7IF7d15M6D91+6xw2JU+CdnXQyCghm2WZPbFpH9Nzs668BtPqz9gvN2Zg0uCO1c0TLIWosRHqQ==,iv:1cTrfqpj1SU/43SMN2z4lhuBRolpVMRVX//ibDBst5o=,tag:ixZxb+GWXr+YFjq/yNu2cQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cXJpT3ZCVzFqbzBHWGcy
            dkVPRnU4a1E3ZGQ5d1dxZlNnWkFmY09SL3lBCjhOODFidVFyY1V5ZWJrMG9OQkI4
            eEpGeW1DNUpaTFVHeFY3NU0rYmlXOFEKLS0tIEQ3WXE1NTk0NDdIa0JPZzhPSkdJ
            Y0NXRkNNMmlIUm1qcXRmdWlvK3lkUmMKKVN7GdzOW0YfzAlyTvHAVtJXQ1+83GCx
            F8dC7wPCRysM/NJ4NyYuQVzv6tGreGJ9ri2286cpI+IEHVuQoR8e+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T21:40:45Z"
    mac: ENC[AES256_GCM,data:Er4KRMZTTdoQ4KooToR2jAH4otMuHU7Uf1/e3YwHAHjvUzO4fQoSi3EEQsbKIN5qCYDp9mAQAsVBuE0DW13Sye4B4+WM4y/pegALxPznYe4h/W+sx+dsXoEI08UpR7Z/mYu20xpbNC//6X3e/STn0efv7/lscIt7/s31P97OWAE=,iv:SHrGPdgbsoaV6F7bKYyDXAG63is9bFto6iJUS8w6n2M=,tag:pW70pz7xxnF7F/YMsCOQ2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
