apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:cC19ejaPGIsKOgO+iTI9IxdWja465yKwifSocqSQTCMh+BV7+31eNlFuvLA6RQaoa8VrQ5SQgSlwNjlrUDl8W1FaPHEQlF8tYE3PXA4u8ZBq5/H7pKFuVoREoLhShs9PdLIXTE9mRqLkROi+F+eoEpYSLFn7ackmnwIlJg==,iv:HGObVxCoMzsdQNbwasIXsNT1HMOOQLHnJKjKd4rrdlU=,tag:ENryI5S0lq0fHy9bOjomoQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdE5GaFdPZCtkQmNvWFpQ
            TFh3b0U3TDZ6U21SSmxPR2VsSmE3Nkcvbnc0Cnh6S3h2NHI3UHhWUms3SmcyaTg5
            bzloM2RZQXFtd0ZkdGdJWFVSTkdOSTQKLS0tIDQ4K3JiL0FYT0RIU1VmRzRoSmhU
            V1JycmQ4OWZNWGhHSDZ4WldGSG5kVlUKrJMfwTkDKkcJiKSg2nNtfTIdTQXVAxyL
            I16Vt7jbe2JpwRKNNLFMzAn+ODZBOwGOBiRPHdlhCeVqmnmJ20cROg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T04:21:55Z"
    mac: ENC[AES256_GCM,data:QGKX947r3uu8HQxbw+GOpTmVuUePTQoL32JP7+lLvyKyJisVKZzo9kuxterAU3VPlo3soWbYm+bCR0ayLxs2FHd+VcmXumqhdlFzJn7ERkjC+rYuc6G1eaMvuxRaQo7ACv36x8zKppnXU4ocWNqZh0R92i4xsD+lVkF061/7ADw=,iv:tAhYT9eOi8f1S+zsNSFnzHdjqt7LUnv/anvbQr/Lb40=,tag:dmnfHI9rGW4SeCUFL+brJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
