apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:FZE86N5pVSnc2qKM5DA8uzg/9r5mS+Xse9WQuxMwe372DWVu0iej4fKn+2KBYwrreCUtR+dGelWdTqYv+QhzOt5rJk0H6YLH3UUQtUB/m++zrCNlV+c40FI/kN9se7WTieTM97egF/frBNAgyDvi007iBiEA6xw/pZqVIw==,iv:jobh8MAvarQ53t48crYOu6aPzpV7YjMn/Cu2hnJYmYE=,tag:j3hzKOLpzjLB2/Gf+Nle9Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNlhmdmNkTUg3VStTQW9M
            RklsdVJ6WWl6Yk4xa2RVbm0wcFNTS1NJYWdJCmJpTktxeVNaVnhGUXpaTVRIdlQx
            dWRnOWZhQjhQc0hvTFgydmR5NEw4NlkKLS0tIGpyZm9hV200MUR6bUF3VE52T2dS
            UjR3VVN4Q2pqQm5aQVpGeng3WkEreVEKbxltfqWXHgj/675Mfk7qZrySldDcJkKm
            Qgg26cm5UKkFBoytevJ9WZNJj0zkcEYy3+CUsyBxX24UOCZYMeax4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T19:48:07Z"
    mac: ENC[AES256_GCM,data:Bu+Kx3GUKQHQx20znxtyaivpoC+871l8iuMymVMFfwcdyJiO1YR+R/t2jOgLEWh7L5sRXY+GXGQC7Y3TydDmWDZI5V5NeuWUPmgbf6KoumDCrEHMMnJcxPOdftLKmvVikFsUMMP/mEulTVBCcrz+JayifZP+JbAEa18tULitVoY=,iv:WNW478YBaXwJKo+4dN4ln5cTJxKlmhkgiphyT+H002k=,tag:tnddFZPXw7H4nMYfmzMEvA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
