apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:LXUXaaAqhTT0LJ1fhe3lHfgIONW4kfbN2FissKR/rsFj7NXGLxqLiY0FC4+l/JzXn34pZFUTIJd4f5S35WPDGIJralj4Vii0VZxpAtPvIWBoU+s+q7ouW6ZNS7Ekvpi6kgbiO9TGPODKl677F3OI75mgr/MwORnyl3GtYg==,iv:AciWu/PHztVj881O/U6362kvf61J8bTot3m+B3YHSlA=,tag:Qlh/OE2UtySq1JF3k9yDkg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWTJ0N3dVdkk0aXFyVndz
            Ui81dzNZa0xOS3FFYk1iNUd2cGdOQ21zM1FFCnp3Nmkyd1hCeElhOGpKeWlkWU1n
            U3Z6d3RWV29JdXhhYXlyZkpYUHYzVTgKLS0tIFBkRHQyUG5DTDNENlJzTGk5a2pN
            eGFYNW1hWVJ2UitVMXdySjMzcWpkdzAKoCR6aTzy4cVqX7276Er7pDFU9CzRPBUR
            iSfw61u5E+523dtVmZBhSnE5LwNmdIHp1FJ7f2WQsLdNmvxuG7BvWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T12:49:07Z"
    mac: ENC[AES256_GCM,data:3vS/4eYk78ADmp+l3WHhdjIMb0OT2RzBrv0+j281m3FXVGUCOPzOEsVA9k+Zd0OXGyXD6ExVIgzGmWgsCpYT2YqZsAlwX9BhJR6+IKp3QZsBY7yMArQbdVpdjDy0Hkr26K7ooVqd4aHBmIkkFoS65NfaPS17x69/YcR5ZCU1Lcs=,iv:1tHuBsPYP2ThhsbX+Kt2GBDnouR6QNZl3OxCFOlgLaA=,tag:dSH/Co+WRyDAgJ1o4AeO5g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
