apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:K+SDSFp+n/pug54cl41EarAtDoHqPvsnSIV1/w5GRoWlXlEdlU66PwUe2RmRgV5m8i0F4zbiz7jTCUZGhjJz4aNbLWpYQdeQIn2tHeWsJtv2FtS+CgumuGPaOlg2JHirEZl5xTcsUylqQ6jrJ/xUVWU4H41kJOP5AgxDow==,iv:pnpJLy8osxn3gOGdjo4wOHPn86K3IFW35jqHTqc+WGA=,tag:47iSAfuyH48O2C7Ib4dr2A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQ21QSkRiM0QwQ1VjTXhN
            SWdPTVZ1dkxKLzFvMmRkbFJxWXhDVGlJTFJBClV4NjlTUmladzFYcVdTdzFUa1Uy
            K0tSMEpvNGcvT3pWR1VxUURQK3JCbHcKLS0tIHh3MElvWndqNDdjTDNXSkcwSm83
            anllU0pSY2UyNENYWWZrdERGQkErTmMKDBOjSfCvJmPWvQOg0GQZ7YhlIIuyQfqj
            xSsc2pKTG8Re3ifoamDfHxKh/2wr8N4rWEhCm4pcXK5aeyYD1hYk5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T03:42:00Z"
    mac: ENC[AES256_GCM,data:9DqNej20YHDGWCj595dLUICAmk1/KI9lT0Len6QiToIiGk6ML4U3vIsHu/zT/EQPMvwUa5ox+bp9OHCXgP4zeg0+t0ToipIgebOZP0/K8FItEODIxD0Zx8SaHubCBOzSFQK05KZJZkoEf/pzEIH1QUa1OAyksI50RZ/6Vozw1qI=,iv:tMkSxptmK9rsNVUhTZrPhO4d2hRW6brzYo77g0vPW+M=,tag:+9OoThubxt50k4b6x5OS7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
