apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:LowZwLeXzMTfYd5YOHYKiuc4Pt6px9EtdNU1GLj60x1CGXH08rZ+7DUbmXFtWTcTxH2NjCAWlCwNOWn6Yc2Zf2N5pJJ51OsX8lybF5niuvkskvmQKvanC/FOXxCwG1Uqnqs5mZYS0jrCq0d3ZGztouUt83xdFVdjtcvdVg==,iv:3iDa2xjB9AfXiXSa+wMVqrkLbibd4zCoJZBKKe9+liA=,tag:2PkxehKQm9SBVb0e1CFS9w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVTFUZVZDcnUvdGwxd1Ro
            djcyRFhvbkY1WFhjREV1S0c2cEo4Y29OL1N3CndpZVdHb1RhUmZ4SDZ3ODZyeTBI
            RHR2RU5sRGZLcElWZU4wZkUzcUsxRm8KLS0tIEF5N1hETzFtZWhhMkE5VHQweEZy
            VVBEaTZRSHBJL0ZRZmFvVTdkVnJLR28KZvS9k4bWV3KCw3BVIdLkfPIvAZvW3TmL
            AxZQvGFK+0fFx/IT6HnBJzGDQQpSsFINknPxRAOWiHjhMsIrUGG3ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T02:16:18Z"
    mac: ENC[AES256_GCM,data:DWri35PbphEIsA0sHEq3g4hnhqCI8U2r1U2jjj4XRRGgRnlgFc38ITfaofRWO43wrxLwm9OMohBM4PeCHzv+nJ1H7Y3ckL8Ku9ocBfjoQ5tauny2Zv9xr7l1JPohwXjS4XUmuPnQVGxIhxdQFCmzyuAICF9ZtlB8LGPv6X0tqdI=,iv:L5oPtVgNGCiH9MYowhFPycG+2I2/2K6t9cO80BCqTI4=,tag:qct9fKtBcdV3PFStJXwMlA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
