apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:k35uCVq0d4EcGtKk9ERcaBLzou+Sub/jbQV0w2ZXOF41LUzCf1Zv2GwpEgaIiClij9mKp57rE7W8XrlunWvvs5wXA8j3ZN3BM3zDpRFofosAjclLpxqIXx1kECR0CRQHNfDuAuieP8Uj8BHWPaN0ZFUNlXt0qMZvVHa8NQ==,iv:1FzYiYe7202UXAVXXbhp/25yGjjMHLHhyCQyStdGDvc=,tag:lKaL8c6x6/LOD1UFma2LRw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYnlxM1A2QlRMTUxYN1pn
            RWo3ODF6dnM2NHVaWFJCMkNlVGhLR09hM1J3Ckg5K0V3N1dzZjh3SWtpWjdwcmNZ
            LzdmTVZOR0s0RXlnSjE1Z25oMkFDeVEKLS0tIHUwQXlrSFBCNDdkUnRRZFdnOXV0
            QzhuYzdUNnJPQUl5L1NUc0NnNUFJRGsK1erKql3XBDYMhL0T1I+GWlVDLzxA+ucd
            YeD9aD/dfSrvT67vKNpRXpe8GkAltmg7xLqED5/qe34cxYtFSgz+8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T04:06:21Z"
    mac: ENC[AES256_GCM,data:d3Rd7hBgGc2QvR1d2cHay0WssruCYzTUQp3tUjUKhXDWrOWom1OeVjDgQ3IIYBCZmzvieZueJzYQTjQo8EpWvfQUWm1Edzn8xc0PjaSeiSDD1UF9bKIlS0BQdQAAtdXDEzyQhf1hjsYtWWQ9xdjtV1P85JUbtGMHXRvKLd7djU0=,iv:7zk3EU0h5fQa7zR6WvsL64zi1m61Uh9xZE2uYv+Lo/8=,tag:G9uU9ymL5LsXux5XUPnDKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
