apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:iObZheEeJ+0fHlUgKjVK/fpUR2Ipwp5Iwy8X3fGRJ0EzFUHUNXoqCo3BJbH+sTlKBpTG/mAv5b2UodgKxY0PTkuWgN4VsWQ2T5RfMF8SwOzzYKStjAWXbc1tD6XrSx0WWtuenXjlTyhgYPfodR5s/AtjfR/YpsffqTBtIA==,iv:4dzVRk8m4f8vp2U0yXbhRcgYPR6KqnzeiYzzQnimRns=,tag:FgjtBwA7T5uA7A5UZ+1DDQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZ203NTJxZGNydUQzaVI1
            ZGpFSnd6REN1ZnNOSGc2alM1bDVzVEtoQlNnCm82Wkdrc1VOWDcwYS9kZzJvVnZl
            dVdXTmhmYWtjQUJGSkFqRHB3Y3VVam8KLS0tIEtoNnFpWGRBaFNQeUJjT0NPY0dk
            QUMrQlZSYnRuTGpXa1o1S2tuSkVLMVUKyMdN1JSQZLZYzp4VvF/XDyNORYIkCbZ3
            nQ6gF9cayQJFmn8CZG1THBTepmur0m+Nys/slmt4v8DzPtU4fSVe0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T18:01:54Z"
    mac: ENC[AES256_GCM,data:VglwwjXlU6G7X75hIgCheQVXU4d+sEnzoo64fll6y1M/8YCuYZgoBlt2wrI30AwS/6JZ5DQNtXbkGJm23PvHZV698IUykTfvHc6lZ/6Bays+YsqT7oE8t33DQ0lLKEyxQvA/tz93sSPWth+SRS1wOMDx46+7P9rFsY29dbCnzzE=,iv:qG7GNsHu7r4WuhywocuMAkNsAjEjMRpAvZTRmLq54KQ=,tag:lvZFbX1GFa8zp6puIOEbLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
