apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:DUkC18RzCUwQBCUHxRfYnbXZ5QM+/lfrsr85dMidK8BtZLc//c7wu6xpIpuut9jG/gE5MQlnVR1BxVceuDvCOz5kR18O7h11l9HnpCcsKqN+JURZWOffcUushlLm6ape4rLpncdzK6yALvABCCmDMN/7kPzfa1WyQveHdg==,iv:+hRckfTbDU1T/T4r1XDojzhSEtLuVABPmG7VKT0SPb8=,tag:vk0t6RQz3tebJHL/zsfZRQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVi9UQmNBakVNcWlld1px
            KytzZkFZQTczbWRIV3lsdWJ5emhsTnJnZ1FrCkRYWGVzUWJrOUE2NjlyMlZZYUNy
            RkRCMzg2NG5CQTlYbVFmUE45VE80MFEKLS0tIFl6SWkyM3Fzb0F2M2hLYzJLaE1T
            Nm9lZmNvNDl3YnVidFdzVlQvaVhHaWsK/P+o//RxsCuILdxqNOrAt7yoTqBsXaiD
            YpwM1L3Sd05nFKZe7aHGGsi1vw4sFUt3jH7hdFV+SwbJMtXP0g4X2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T04:01:23Z"
    mac: ENC[AES256_GCM,data:MYHGjz+cjMFzu88t+9laMUegalvQE/deKdJ38c9z2DyjpTXQBPlG3IFlBqbT0zay84i/utpUs8uMT55mu1DiRICqf9xBp5xQB0eGG2wfFwzd6AJiWPtY2RBqoPZ8r0zDzQR8GjhVtBOBwg28DEZnv9Yjh5Y45fYMKukDl3jOkkY=,iv:j0duRyxIEhNpNvoHbCCyjfzc6RIx00VYQeii5PNO5wA=,tag:zJE+RD2u52G7HjF+WCNGKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
