apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:lY/IpLq9H9UTzJwh+le5kNm0+3F5B3VNYg9wn2AQ24MFj/IeKB09dS8hKuGFnDiDQk4Jou0Zc/Ggvq5p4XnJaBFXU28S7MhvWYne5GdIYrD6U0k731vZsKiCb/iZzPbdG0Ul/W/ichqsekr+/PO/fJHLyOFO9U9XwqzrcA==,iv:WzN9r7nd3koS1fSoz4Cy5TZ5IwlBFNO/a2CR30hQwPI=,tag:nVGUI2WTBFeO5JfWSNBveA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZ2lpY2l6ZWtBRklvZlZu
            UmU5c3B6RjZoaHJwN3FRQytxT0txQ2IzaTFBCldZQjlVa0s3dGVtWlpEZnduL0pL
            QjBpcEgxWEJ2Q0hyTjBJZFVWcmkzWWsKLS0tIElna0JsT3Z4ZkpxdlJ0b2RUaFM5
            SVhSRWYwL0QwRU5sUkdYN2lDdVBLWEUK+aM0kdoke3bTfqVSno6JszCCpN9HWKqa
            xHBN/pxpWvY5Ki7euo9ma5WHCi8RgCFSXfcfN6BPC9hFoA7SGo/vMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T19:12:37Z"
    mac: ENC[AES256_GCM,data:D0jgMzatpYs+EszOSvq1rG0xo1nICfpY+pF64mCsULEOI3KAwh4OJCDqF1YEbjY6pQmhj1mwd8BHoiuxJ9LIReAC256jzcyA8/hfPYc9XQJ+vu2Y82dmb8u2ougept8sUG3Z4NCSWQW238RbJB2XvatoCDPv0UiV6ogGzPZQCMw=,iv:0Y6OlruX8dUAlJxqWMLCXMsbKtHeunZWMBh/Qmva8cU=,tag:TLutNVEi7tsr0fWoQoqeBg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
