apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/auth/vaultwarden/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  targetNamespace: vaultwarden
  postBuild:
    substitute:
      GROUP: auth
