apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:LonxG4nLLTfRZe1rd4pYDMjRno5xtjMQDxaXXxXy3a8=,iv:NO4alpjzhb/RabRq3Cw9SC0sZt6U9s1BqFz6QmLn0uA=,tag:+twTD5cAQiplFcCNlyITaQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SUpIM2tIQnNKa3dxdHRi
            ejBvdjFmMHpaK3Q5T1M1OWJ3bUcvWk9FTnpVCkFwUXd6ai8xbG9QbURmWlMvcmUv
            TXNNbmhManlwUkxlMUJGY3RzeWxZeDAKLS0tIGkvTnZYVHRLU0VzODlTYURkZkZo
            NDFqbGwyeW9sTlppaGZ1c210Q1RXV2MKD9wmnz9rzwZGQLD3dXWvFR8MBg5j2T7S
            vvUUpVK9mmzgjNjqT2ad2ywcdABRQZ9JxJJOTPyMfh0bJ116a2LzMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T05:18:28Z"
    mac: ENC[AES256_GCM,data:KMGKIYnKT8IWzy0W0Mfnl79gkAv+b553y9RzDBVt1+oJ/CnKD5pUQrVafvWe84i9RRwJZf/DWSJnVrFLD20o0/jeQSehvcORT1rxMoVyddtmy5OeuZDXJIA9bVtiDXQFhC+6qikZSlW4dkNjHTaRDEe207hucbNJaf5UrGRaEoY=,iv:pR0E2aI7XNmMdL4cchXF5nsV/80SmzhAcUJ7Ynw3v2E=,tag:wQKkN/ZIFHEzw8Ze8EcdwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
