apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:7wVUTgWtivkfp1zj2/AOENg5vjb35cLhTOUJT5SI5kk=,iv:I31Y+wsZPiz5/DL+KiToQXwsGUsr8JG1c11jZcnmJbo=,tag:unbWj5nwzuU45F5BrekGjg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UVRsM1JnUDM5Ui9KM0o1
            S0x0MkNUZDQ1VGllNnJPQmpEci9mK3pwOFhZCjV4ZEhucE1XL1VsejAzY0RLQjRX
            TmxhbGg3ckFUajlvWS9xL3dodlh2OFkKLS0tIEFrdldGMEMvcjBHdkZLS1NuaW9N
            Nm0zR3N1Z2dxRXRkMHFRdGlBVk9XSG8KDRph8Dsng+ZEQ2PFLnXwwLff/dyvsaZi
            GnNRf4w6A5Tb+z4kjwqYLiZXX7iAujVeIUmrMRSTtdlONnHjY5TysQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-18T22:21:39Z"
    mac: ENC[AES256_GCM,data:emVqXz1ol+XY7OIBwvdq65pJAwEVKPZIjFGdMYcVndVTXX0sN/akEOAaU/XfA2pTJIjWABHVXundrNIGtH79p1PeXyzNA45FVpvND60RTz7+8rZUz/2Rej074VFeB8Y6cFSURKprC8YVTN/HHQSkzfXSGkxg6iITYNxIbWzbgIc=,iv:/KtMzo65bazDjHBH23ShbbD9UBpeK4g4lNIgKOi7hXg=,tag:c1P2fTvFiuj1lyQfrgj6Lw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
