apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:NmdExNAn465nz5rgUwC4xjYiN73K2a3GtPkHc7ezpw4=,iv:srNOYoz1UnqrEESYcB1SAPkmUiICwvSlxxyNlp1LVCg=,tag:Nd/8pJnDg7vvqqHD7L9eVQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaUUzL0xVQzVvQmtxYmp0
            ZDYxVXNJbnd6ZUZRMm9tWUNPaEc2TXZxUlJvClRjUkpCek1JWS9tRHI4RVFQSGtN
            NzVpQkxOQXNmMjRXMERvaGJYUjA0T2cKLS0tIG9ibG85ZGlqSENvN3R2NkNTNmo5
            QStBNWxxcllmd3ZTb0lISU1RYndZbjAKAYDv/+c3jNuyVm490uztQC025BXSk/wt
            4Mw18/EYoEt+WH1miK8Orq1nnvVF2PKfm/m8glXvIEGecJH3GvUekg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T07:54:50Z"
    mac: ENC[AES256_GCM,data:FzAbEqWIso3Z5jG4IQHRiC3faP8MRELxlwuAfjw9Lbesgb7oYxbH+u8VwVzd82nF75L7MCInRDUGREIgpFScG57CD1e7isj6JGmrLcBY1lrYcqSlVmqonOsuXw0/eFnxCr6CeY4IZz39zPkx9TEA6I0cJO4oewaMOMyQVJ2/jLc=,iv:s2evEmUVdtW86tRGw7xanTXNigpC3TZpGwPkMf+ceY4=,tag:p1VuwH9Nd93izawbjglpkg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
