apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:3HReVu1hkIxzCOHM+1lgQb0swZ03xMl4K5qQ5uC4Q5k=,iv:jCq60C9xt2MYdbOVdHL7Gk7zPTpT8EOHDGm+07IC2PE=,tag:tHi3LXl47Xn920dfoLcPig==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWFY3VU5JdTUzR3I5Ri9B
            U1lPci92ZFBVbGthWUIvbkEzOVQ1UHd1eGxVCkc1VEFxb3FETmVPK05FMkZ3QzNt
            TGNmYUk3a1pwWkJOb1dTd0tmQVBWOEkKLS0tIFloWFN1bG5HcE8vQmpjOE5QQ0xV
            Qkd3OXY4WGNmRjF6QTd3bGVtWkJ5VUUK7wcrzB8TYrlEtWlv52Gk4yBcVXNuXAZs
            z82F1mOn1BdRUQc2HHCumgzhNfEsnlM/BTGUtPcB9SuPkSCuJKJxHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T03:07:03Z"
    mac: ENC[AES256_GCM,data:DLnJs9ZrszV41FMNV/dgqJYAwsv1T3LK0lWb6/fRvdBx7UM9Fv8mKP4INFQf6oEBqpjyrUMCOkRWaSXle07Xxdb+Kc2zc65XrvhCUqFOg8EdVVhXXIMpxZDU3N7Uz6PsHvadKp8PAJNTiGVi75IwzFtyn0uIl4EA+1cZqUeKGWA=,iv:Q3EnuNuP/pb6oaPriNbTGuKwU2Mr3MW8b4930MY/Xz8=,tag:NHCyPHpWau559TQW3IcoTA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
