apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:MWYW0fqI/yuK2ucdk/jMc4SeXipnLSCSxlXz9ckO7VA=,iv:h7fdRQvS9h7iBfTtJ0p50BaZC9rVJuzHsL0wI3eJjEk=,tag:Iw6iogdD5vcyn/YA+dy5Wg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWmxiY09aOE85V3J3c0RK
            MENjb25ta0d2dG1ZbFQ2MHk0LzNPbjQ2M3pVCmtYTDM1Q3BiQVUvNE5XWFFWNU1p
            aU9sUzJuVUxhcXlzSVVGLzB2WFZ3NzgKLS0tIC9YNFRqNThTSHViSDFQKzFEN1N2
            eGh1dFRCMkRUdmxtRVNkQzV1aUdFVlkKm0g9dBxXA1XdFCC024MKCZs7Mh9AmDse
            6xr7edesA/xqYFKwGlDlfZqBbGlLDbo4pjE/234oTVbkswCT0EBf4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T16:08:29Z"
    mac: ENC[AES256_GCM,data:3IkN7q27WQ4XhYtWtZPTW0bHtK+XMv0DbfCW8PPmjhQXx7I5510cQj30hrFjehESelc0wXe+PzhA4J1PBDk5K1jlP6sQxdWj/a7UxG2F0utnu8p0jpe2Wl/bgXFV9GR2vXisUbNXQMPl1599xGSyDqypF4LmK83s+bF8LLGoGCE=,iv:fdARybSKLhyWaa8ALZypl86D6eD1v7QH+bU9F3iXfy4=,tag:UKpINfieWQQgWCs/NC5B0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
