apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Uf5JhAsv5+nPKyAgnaKtYovgk0jE+ZIMInT8A7Em7Ak=,iv:lfXN/JXjEx+F/jHRy7xHTv8rQb9IHRF+JokEjoj+V6o=,tag:jIy+94tBFHwiOUXn8uzxzw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYXByeXM1L0dXdTA3RTBQ
            ZDl1WG53YnNqZTA1cFFzSlN5Mmh4SktuSGljCmFhMnFSaFlMaDZFeXlGa2dqQlFh
            RUFXQnhPSjhEQ211U1hVbUFOSTJGZDAKLS0tIGNPT1V1dW1DT3BBNlYwK21uUXVF
            MVVITlk1Tm4xcUpzZXJPZE0zKzBqMXMKZI+UEqsroDlCgQBaufnfjR1YmJ8Ng9du
            PZDs8KrWWYpoYzrjvSjpra/+C/r5TUyF3+ZG2ym51KNQI6k2+NNHkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T23:51:10Z"
    mac: ENC[AES256_GCM,data:Izj/76ZCrKhWWAMsNf2HmD97w9KnrLVBGARgu0PbNQhY4D8W7CRMu5fLRncGC7Egj6BBf3iBzkH0AglM55Ya9yb0JOY0YDGN67SN4IZqaSmhos9T0HFL/Y6p7QuZ48BdlP4jD39tYRzTIV2r84yVnPoneEUnbCb6ibO1QxD/kE4=,iv:5e4izdRBr2hik5kvaN6fkiKy0rTZ5hyp4bDzSZ/Zhus=,tag:OLIHmWnU7RFjuyzF+Wvu1g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
