apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:8s/uGzs1Hrkbe5qmiQ4IBQYHQhCbSMWtvgQdecYSsUo=,iv:mI0oPVzSpYL5RTU3oQTXFstZd0jR7NYNriAul9v2i0w=,tag:YTNfTFEKniiOxH8olRFO9g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dTQ4UDRleSttQnVQMmtL
            MUp3aWcxaUd4UkxnMTRWV0Qzem5EdnZUb0djCmE0bi8wZVJnZmpwMmgybUlFYzFY
            NjhHdW5udHhPUVB1UGJXWmNCMjhUOUUKLS0tIFdPY3k5bC84WlJ1aEs3bVd0QjQ3
            RU1Wa3ltaXMrc2RhNWd0YjlNanlFSjQKZdubsk8UtjoP5f+63LvcyhcT5EN/LBJU
            +f8fsNp8ZpU9RvepP/rtjF84owOWuUNwNA6JuXztN+8ohNT5ihMsKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T04:21:55Z"
    mac: ENC[AES256_GCM,data:tAQyG/+fygU3xFlO4VTQOPiSK1NoFeTIzroyCNrk75VcFR7YJeSVBP+wWFxMDJhWDxjnEMNgdwOh8APKri4+wfIHaYgqVOfDC058EnNkyZwBl6xISRzWdMT1vwp+5/0IlYJP7yC5lW73sFdP7Cfwrp+eXgCXIcx/Gh1f+7eqIhk=,iv:kSvdNGfscJX6pRXUwz29c6u8WE+V/dA3AZB17Wi/0sI=,tag:ntCuTXj871u3GQ6hfFxEVg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
