apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:4imyb9lHRckSYAlEEdvhnBme8V0oW3u8r0R/oRAPyq8=,iv:GPsFu1erumb+/G8zcgYFa3fxLXMieWYuZt/aErgUSTU=,tag:aF6ivB6E/8B0XGRK3suutA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWnhHM3JINFVYWmc1M3N5
            dGNGcFVEdTQzbUpSTXM0S1c4NWJZZGV3OFZZCnRobHY0U2lHUkZIaDRtNWJ5UUw3
            VzNmaTdNcytZQkxXM1lOM0hJQ2xHeHcKLS0tIEVwQXMzYWprdXRXc0FmZHRXanlo
            d0Z2VkljdldBemFxTHArSVd3Y1dleFEKRvJ9BsT6Fld+Kd+5/aW1R0HfAnb/6wc3
            CDm3wH/LUm0hYJPJlsCoFfEuI4CRO440WX0B9bE+5M6ccbp/VXqJrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T01:11:58Z"
    mac: ENC[AES256_GCM,data:t3wDwn2bES6UFaWgUHvG7D+WmVemIM1OCrOajUPX+DNbYteyZ3y+zdg80B7joqdd2AoBYNudCYbgBiMbpO3Z8mpsS38g/LEDm9dbZCU9wuC8gmR4Txu5YCfMZpvNd51fPexZb9vUxOa/WauuZxNwm6g/rsqYfGy+/sVyf+6UAks=,iv:7JQPOsp5U6JMyMgWoq5Iq8exjLI2gNtw0mGBJMLAsoo=,tag:slByqRgaVQXbNtQBbG2BOw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
