apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:nBpAAMtufHp7+lFDzQvi2oaLWXZU+dpBm0tXVYs+mK0=,iv:kicNpir+MzU2+Y2UNp6yhFtfUT2fd/v7YfCuin11Vro=,tag:maUpFidun4BmrsuxKRuDhA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxa3JxOXhFM1RjaThuckF1
            eHdOWmxSWFMvTEJLRkc0dmQwWEMyeU85YUVzCnhDTHJkd09lSVQzNS9JR0ViNU5F
            NVhHb3ZWZWJRNkM4T0MvTXFlWC8wekEKLS0tIE4yUUExaUlET2pMOHB0ZW9rN1g4
            aDBNK3FjSmVkNHllM2g1d0kyN2Y0MGMKmL4WZXZ82dTw5CVNHIlHorcbhTZqQrSF
            3fJtReWvVZB76MmHsmpStMm2K6AFKCKRMBDUMkCsKEUBs6s/QSobQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T12:49:07Z"
    mac: ENC[AES256_GCM,data:o1Oj8W5BsHgYsT5ubLqL7Nv1Dp1NNRtlOXLrflB2I4hjUpwvfVyn4pIAuaZyqfeKfYhS0S0D6ozcSHnpgF1tV7S5a6p6Su5oROB4efm01aqw8draoBRB8JGpWSsKygCUAIvViDcwoiX00o/tqzqQrco4+bYif9LdYhayvLGo8Hs=,iv:o/dVe8yQ/XUghnisqSffiH1qIYlYHJAqJLVBebCFFo8=,tag:DT+xyqBlA+rK8BpZkMKxiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
