apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:+6A9atYajSsCg5GBgLVtAyXrGglQuZlaAY2094xdGag=,iv:dCepT0o9JZ/J9ZNprexuiFsLi7rgOCIzW11nsXWur+c=,tag:Q778Z0eGdAKDL8xysxTGsA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRWliY0FyVDN0cFFxZ003
            cGpjbEZGcW9uUTNtZzNjK2wzYko1NWU2VzJNCk1SVlNJcmtPL05ybXB3VExpSDhS
            anZBZkFQZUJ6QXNvczhPSFdZVE9SRVkKLS0tIDNYZ0xNY1BPWWszbUxSeThaN2Er
            WHVWMGk0MWd5WG8wSUZtbEpPWDNwRG8KYr66vhhiRM9KlmLt+qJj9ECBfPo8ZhhM
            4m9Qlv6DDrvl26pThAFZdWec5TFvYaR2ORE86sOzFf9jwio5oLgrXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T20:55:07Z"
    mac: ENC[AES256_GCM,data:/wFVTbedHDPuNAZzI6AhHR9OWZHa+8HSixN60crhii2RvtthtHUY82+XaZv3NFXhJhu9bWhWlWengEuQ0/mDrUgyxrsKrOoGmdemHhc2wrJVbvF6vV7X90qFELfK8kfQz/nAK3ope/uZdb7IGjshQ43WzukqnPHVrzvT3eDMkjs=,iv:zV6thrMjiMjH/7qh1f7xikxFjKwTX1ShOju+LwfVRSs=,tag:I21lNs73F5gqWkoMNaDO8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
