apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:sS7cOBI9n2z5iTYgxW6ynBPmaUhC+i0dphg77ovolXs=,iv:IdRRAHUCJMRy5CcY/1TmlXS0tRTMX/wpPaojvosDQ7c=,tag:eNg/bkGNog+wpE7P3zoGEw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYW5MUWRkUkFMUkxGMXI0
            V2pnU3JucFdUcCtiYU1iMUxGWEowV0JXVmhjClVzR1RPbi9VYklodElxd2ZMTjR2
            ZWMwL25ubDJRaUY4MWtEYm1JanU0TXcKLS0tIHJzUHlWbHRaQVlBWW9oa0pWUi9y
            K1dYdTBTM3RXZFZSMGdMdXZ6bG9iem8K6Y/eTGZZ4Q2b+gpzvn9HCDSsztuO2899
            DeiNLom1ke58YAoOTae4YkQGZEVweck76RtP8x/AoRMDI7D6M1iYkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T18:52:13Z"
    mac: ENC[AES256_GCM,data:YV5XKJ9TAdOjDKjyA++cqX6k7xKgpR4nB2w46OHPJe8HY/UuJwQs2nPEh8+ZVYtxJ2oNMIC80bypRBY1RmmldIF4JWn0t57d1LqLGOd2I+aGoqbPmCprFSEzG5p8Ta0K9hTLUiRaT0ZHPKE6LAQ1yxRn3kQaB4KF72ESAmM9Ttc=,iv:FRV1XcOSRJmdCqtW5bMjjoajHKFyKu/kxcB3mUbbAD8=,tag:5Y0I7wpVVD1IEz2WWXIIEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
