apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:mA+XbyQzHQANsJJcx5e/tS0ezBM/pDbM21Z0O3Ic0vg=,iv:vD71DHV4M7vaMbwhzpxyBAnmcqgw4OnrSRpjxFnH6os=,tag:0wGE/+yizaprnfInKxbnzg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1eWI0VFpXT283ekh6ZFhN
            V1M0NDkzdlN1Q2o2eDRQby9BUnVKSWRIZnd3CkNUbGYzaDkrYTdOWUtCeEdvM0lm
            R2h3OThmWG5jd09FamZqeUZORUl4N1EKLS0tIFk0K0ttbFZxV0pxNzVEY0NQMUVm
            eVVCaHJ3NmpqSWExOTRWcmdnUWwzRGsKn7XSAhSAMWQa7c+j5Q3a/IVRi3vkiXdA
            RyF6xkmO6WXs8OiG/l6jbBbR2Ubmr9dm9LcqklOAm2KV7q7Cd5H1zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T04:04:28Z"
    mac: ENC[AES256_GCM,data:B9w2IlfEAj6cKzMECRzlRtGRrmYJWulS+6qqpjqdd+2fiTTbg/YQ1JBGVYFdwL/xvxLliPs8GJVOOgImMKmaOU1OuB7sIbJOZcnNcjlRcXu/vI0If5SL6fAiOuMR+mfZSPVaBGBeBGYxhSBo8gMF1jW3uRLGQz/3a5Xe5UK1jEQ=,iv:qoyHYHWlReUI0aXP7hqmXYLJGbl+gYHDuBNhsDqYQoQ=,tag:dDf1dR9YnmkE5PucFMp3Sw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
