apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:VqX9XsVSXqNgaqwNlzxPYuiomao2feA2gmQJ4gQW6Ps=,iv:acSRRKLBJhmq/pPco7b3On8NHi1PID2tBXC0ujdDgAk=,tag:txzD6c02GHa0yExPUAjwXg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VVRIdnZRQ2VQUS92cXBE
            M0NHYkJkRlJCOVNIK1AyN3VoQkY4NzJERVVnCmlsZG5McHJQZUhMNUpYMy9wdlJs
            a1ZZWXVWclloZHU4endFeGl6TUdZUG8KLS0tIE9Ec1pVZUJVby8zOERNZmgyZHNH
            Q29nYzZaalZxNk5HUHVwVDZtRXBtREUKObiT45KeCGVya6Ejg49taw6wv7Lo1j6K
            Xs21WKX6K1N3b0XYcO/622JiSyehv03sCr1iJTvHb2rAiW+BUXRz3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T03:24:24Z"
    mac: ENC[AES256_GCM,data:yZXfu+wRWxokAqNRulYmKIIi146Is1SplNohqKwTBEstFGMYMUEU9KZjckb2d8cTM8wLCHg0y2V1WvBXQKoAXEg+Vug/Nn/VI0t0Mp+59/+B1K4F+OfqOh4UXomSspghIJGcIfO86bxJQYG5FEAbBhDI0ha3kqk/eWeJ2aP5HlQ=,iv:eSWtDoumiHtnhPAvv8lELCioXLrepOBR7bhdF34/EaI=,tag:Sl0DI18yJ/7KOJ6/lYIWlQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
