apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:2BmtSGkxAmUAQcF05isw1KmQn8WsueUN3tLMWw2l1wY=,iv:1br3Zr/Cz2efXYD4mzBEXJUa/DB5M+RR4sQ+0JCl9ho=,tag:hns3gT3SxrEm9rtBa3eHoQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeXFLcXdrM3d2SmlHSU1K
            MnU1SDgrS2JqeUVCSy9zU3pqMENudUc2Rm5nCnJJTS9XVThIY1VWb09KNGZCZkZh
            UHlmM3hLZWlsd25YTWY4eWZnWWdxTEUKLS0tIHZ4MXpuZE92N3NEclZzRjFGckVB
            OHpxQmJnOTZ3VG5LZDRvN2Y1Wi9KSkUKH0E7S9XtIN89j7Av5jXSpYsTNgp0STnS
            VDmTtC03LDF33DXuAQQ7+eU7sS1WX+SZ/bv0wDJaDhEDwX1xLgjuBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T20:48:11Z"
    mac: ENC[AES256_GCM,data:cHzaRF6rGJhMN8IZ+Vx+JESCNyutiJWku+jMEo8Din5I2rBaptxTz3oQdQOBF01xqgZ8uLmbmd41mMzzY09sNUUVY81sdyQ2WOYPelHCxK2VlpAXQjEQDStfQ5jPeeCuvUQ9Uu/OyFDR42IG4FgaGlTRyZ17Hxn95ooHm2dhuOI=,iv:IEDtwD8W+EdpZB1dkemx4ERqxC2XwTDp2RLmHY6Js1U=,tag:gaJ9Rk7NpgHKM8KpUN+88g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
