apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:IkEb3mGTItRlDgh4Qy6SsR2A541MdhD7Sw3lX0UxMK8=,iv:8Y3PWLri4KEmvSwLNdwcTBU0EmEQstNnjb1CyUjkS5I=,tag:/iTp7crYMMzFbcaQKasdJg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVXNtQ1ZrZ0xrQmU3Vkcr
            Wm5wWFRMZ0lqMi9STVB4dkcrcllialNPc2hRCjI3TElRMzRqZ0M0VHpCS2FKcEVR
            R1dnVVhyRS9pOVBhMjUyWERrVTZ5K1EKLS0tIGJndkdQWmEvRFlWN3pBbjU4RTRW
            dUtFNS8xanN0WFc3OFYzS2xyQUh6Z3MKmCJ7wJfSSr8cUnE69PwOzWSQQvCTryRc
            F6DJ+m7VS62Yt8v/urJP8gZrauJ0vFwzz5KgvLJd3ypGmx7tqOzHFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T21:37:21Z"
    mac: ENC[AES256_GCM,data:XzB5gSoi3t53M+yQkGAt7cCrFYygmCLbfCBnDkTvnRMIfq7cfgt/4F0EMwPZrAC6UJq0h6YfREh79WVgn3Dd4Uxvp2aJa0HFzs7S6Bd4KPO35U01YQvvVKHjob/ae/TfKvg1PeY+IYxJIpRUwlZ05ZL1X5rR0pofch31RQ+Tz9w=,iv:YLRm3tO6XWojChgSoOwClwvFifX9DCJknQix97Fiqw4=,tag:BDuEjDXyO2V7rGrhybENKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
