apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:86UMXFHIuNHRjp64th3brtqpaYExjqUCF8ot+cpnVfc=,iv:d45lMAG/BBHMwpqkOxpr/oBKh/xCZcqGd4gXcvc2ITE=,tag:Qe97a2ynoaFJ7L4ru32dJg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydmhDbml5MHllT3FINkJ6
            VVNmUjdBTW5jZGM4TTJsMzNhbnNwY3h6SEZvCkJPa0tlbmtzSjBaNkkycWZZZ3hU
            elJSYjh4MWRLZ3o3TVVWY2dSekpGM2sKLS0tIDBsZWxjSmVjTUhzeUU3T2lzY0I3
            RUFjd0w3T1c4enNLejdOTndkdlNHWDAKkDu+R/a7+ILCqFQLPAJKt5PN4WvEE6mF
            zFn/L9dBBh9KasnJ0uSxPo3bCd/1/emeAwdRuzpKHiW2P1N+FPBQYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T03:29:57Z"
    mac: ENC[AES256_GCM,data:IbdGAD2pGyX8/vXfYxMqox5Sie4KeRLeVDeBPqFkWrP3lwaOvKHYcmnVBzz4w8RBqxGMcDNx8huUVxrXkITmKe9NqSUkS8AxFmUOsAUmjyj0sZmlT+35zK2rN6Vfb5t8fmLULwIb1kDOvXUsrZowGoqzhSfTEec/2C4+IeIskNg=,iv:/FpRkc+a3w51ySHssLUvMRy94uEh+IAVdZYnLp7Y9so=,tag:pz6jciFfG6xsfCtIpzOilw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
