apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:7n7umfV2BjYP3FNDBh8AMkkt8ELfGCs4PA6ZqSV674o=,iv:4Xj5nU4qEzOQAeg41/WNuJIIMZuJo944aCvqD5lX+rw=,tag:1JDC6BUw/yk0/LeyLc9CEg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWUJhS2ViUU1hWVQ0VTZ6
            SHZxWUJWRXc3SlB6N0pRTTU2ZU90MzAwYWd3CkwyYmFBWWsxYTA0VmIxZHVZS0JU
            TEx3Z1B6blIvUzEySDZLaDgxTUpWMVkKLS0tIFZPUzJRdWcwa0g3UTJ0VXFVTWEx
            RGtXeUg1T1lKb09tZmlOYVQvWTRXZGMKB0Q5xli4Wh6zlEl6e2PpG9MMKCeaWP4a
            WSQgQ2QJGK99nKr1Ykrfnml0J7GlTVLRKsfjQnmKrQEOpO2XhyY9XQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T21:40:45Z"
    mac: ENC[AES256_GCM,data:dRcgBDJpQX8u1pC4Ik72aFM0q5PaOfhcEoqtgXDbqU2/41q0BgRF4o91UdtU2pGFVsa6xzBofHB3j4oxoeFxpG9pu8Z2Jzirs5I7+hB4QW75N0ujlq6PIDGqy0UxLeOdqIr5aZDVrk6ylT9dHxK0N0U5MgqViKujRhIHzFugNuQ=,iv:2u8PqD2fjs1++pY1n255z9QgN0XLsM3cP19BEQ7uqWc=,tag:2cXJ3JAy6pJd8KOwuBqSgQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
