apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:AyFiKv2faBl43wqcQn0HdsSv1k2HA0zKB8yJGWk1bGs=,iv:fcGkSQhQ70mrfSzkCN1wYODqm/orokY8U9qOLvWu3z8=,tag:JmaVJnQfmffo5yYzQP2/OA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcTlaNjVUS25qNGRVMnhI
            a1VCRzBxTXh5bFhiUzBqL281emY0RU16ZFJzCmI2TnZGZ0FjSVdGbXFRR0NOdFhJ
            VDRsZG9kZURENEdxeis5MVFaNjQ4ODQKLS0tIEZCeURZQ2hSaTFEY2xsNTE2TWJU
            Nm1ubVpjemdJTnNlYmJUNHZlSklaUWMKT3DgTWUy1wml0zbXlwp8g5l6QoUSF+zw
            f18e1WDq8mtJbbq2/bkgcvejOt/spEBeH1zL9Y2nXir1Xp3Ggw5sSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T04:35:27Z"
    mac: ENC[AES256_GCM,data:nnE7+ia+V3iun98HsVm91tunAg3bUWuCDUX3Idw64jYmwyQOilJGACdvPvt+8FKB/lpAr0m+j/xCVgr6uOhfDxeu/VdPphTm6XjE+9DW5MNKI/RixywQy+EhEVOy1BFgRiUclj2IoFOY3g1LpWG89v+rEkeWvxjRvXlvZS/IH2E=,iv:3VEdEDePzH/d/7WVp8hmDwwtT6yvQRr8sMZeGMCgww0=,tag:3ydp0QmcLprKz8ZUOPcZ9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
