apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:3q3NDUG0/kLBNPxi6bHENVL5eirlQOhsv8VfApsuAS0=,iv:A+d3svrnurDygCIGlkmTfU9CWdUkCCRyceGjW0MNjn4=,tag:HussigdWtJ0NeacLawObGA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZVlTWEtmQmRGVzg2ZnVj
            SDRYeTF3cGM1ZzJWYnBPbDlXWGJ3bnFrUWlZClVzK01OQ1VtT3J5ZUYvRCtXRHYx
            QWsyRUtoSEdoWTZWOGlwMVdBejk3NjgKLS0tIHc4SFdCak1ZTUU2bithUzZ2TzA0
            ZE1pQWN2dU5TQytETjAxRk93aVZwckUK3APpmyGnQFbN4uUOX/oQoXASOxuXbM0z
            lOmDVeYcmKCz+MI/CYB08OPSPs6l/RmaBa0XIzYdXfcnxolBDHGQ7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T01:03:24Z"
    mac: ENC[AES256_GCM,data:BIS9hgSCF6oePfSIABwqGy0PYCshSApc1Z9S95QAmf/xhFwTFlwJ4H4WPBt37yVf/n8YW6L6mw4E+Hbd7GSZFpnzGb3AC7c26p3RY0b3/RYVGSJH4k9fuS0YfKw7i5mdxlwFs79ZQxlimAqTCDMMOyjXiWgTnoRBSpcUXBCJSmc=,iv:NoFdt/28+XBY6N7F4JgeK6EHE1UfdlOvLruvD3CadvU=,tag:PmLlbiJiQCKFW7gR/RCnkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
