apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:WlcmweJ8LBaL//vfRUvRswQcFVMr8u3DyBk6E/uSCEM=,iv:qVJoynJTQKfCSWdqX9hRFa5VX3HMqhoxvd06k1xe43w=,tag:xrvd+NhcRNT2W/PJbZdbuA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMWRybjJvQTdPZXZYalNz
            V0o1d05aUjNYanZSQVRIUEdMT1I0V0hoT0dJCnphb0hmODZ1RUV0YkxHUlhQSHIw
            c3grWElUVXNzNGM3eU5hUGFVWjNoeGsKLS0tIGJ3UGZTbGFORDcrbVJ6bWtJQVlY
            NUdoYll6MVZYaEFweHJ6YjZZMGNvdWsKGNo2RAlOEAOfJ1oZARMPvzAlJrrSphen
            /4sVbEHcTYlnRkC5EpJdWm4j8/B8PslhdP9fi00ZZUJ8OatYuc86Qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T02:21:21Z"
    mac: ENC[AES256_GCM,data:Rk2PjZ2dkcPM04UEoYK8FHIHAuc6TVs5I9jNJm2EaN4bsNwjFJ6Jl98ews+yk98ShTnV/DE+ZBTi3LxoTK/uYnB6VpEr2/CFZ6y5SzrWNmLuHh/zBiOpzEo6k094fFEAVAV1tbr6f7ZCiTnBFUG2/BnllAf6itWNxcCVkTagJ/g=,iv:lJJOF0rswn4O7OTyUeBpW30Uvr/Wlvlyi//9TAYnMj8=,tag:tGKAW8NI2Zy+v22aC603Ng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
