apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:K9WVsY7GvDOOGm5Oi4cfq19N1w6Ah80zzVjFjXkUw+A=,iv:Q/YU3TM5afCwkJhGDD5KbL+YOKMIJel3qQG2E6D9tzE=,tag:c8m3IDK+E96VzOpzRlr9qg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdjJLQm1rVkJMa0toOEhU
            SkMzQTlKREFCNGlrVyszcnBWanFGNm51LzJZCmtVR1R6TU90Qk1jUXRQeEkybDRP
            amZodEdrZkQ2bmZ1RjZyTXNDejN6Q0UKLS0tIEFYczVWcnlwNm8rQ1A1SUFWUjVC
            L1VHeTdkRmxUb2JWbXhHSHpDZUg5QXMK1ic7uJFSZCzQtr+PPBkXmEgADKEcEGOA
            Bz/j1IO47IwUN+5Oy8DyozeE0wuDwGKkuycNhHA9NAk5RSpbdZ/WAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T12:26:37Z"
    mac: ENC[AES256_GCM,data:KMXQBh8VK6/PQacaEiEfoCNqUre2CjcfjBFJo3BwIsm9Bv8pbb7UmBj58iMySH+SOLfU9IkJzvd64meu3MXn5xsjwR06PLWbehLF6pqCavec0L/sTioLew+wreNRKY7quq3WhZ7lb/+8zRPUNRcZ7phX4QqUKGBE+wEB1dyH6C8=,iv:L6u6zPi5l9I/9ALfYFjf8mVQoHjMn6OCRB9UrEVE3Qk=,tag:7UATO5ldgd5y4rx3siM2vA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
