apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:cWKUGAo6y3TkZK7P+/P2trv/zJK9zhCuP4l3gFrVKvg=,iv:Hhi7yPq4sB9RuqHfk8Fjte4C6ZBkI9ai+1ALxwpoFTg=,tag:jf/2/ZAgI4AIT3TFcCamXg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Z2F5WWV1WHd2S2x2RUhv
            c3YrcjFWdjlQQ2lHUnY5dWYwbW1uV2Nlc3hRCkRMRWY1dU92MDd0cVFSemFXSWoy
            dXVGNXltcUJ3R2lDbE1LQi9hV1NMMGMKLS0tIE95ekRrdmw0RkltdTQ4alRDcW1R
            WGtiRG12S0tRVmM1bGw1TW5VaHd6bmMKVkjBLmj1deQ7LUPk0WngFmVtxsyg61EY
            dqRGBT5IXgiLDBuHDuKji0JYkoJ4u+xM+Nc23VUeLVlSmtwZVAkZtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T04:06:21Z"
    mac: ENC[AES256_GCM,data:rgKAWyqhKC9hlTUWnzylQzrj9c1/vdWFkIVHLjiQBbfeM2FrXDQVHDbScXkqefZeTMA1Y2zd/eVksiZ4v9f9OgKDBKnRrma7wN5QhynJ+PDgK5pehMvIJi7Cl8tpY+FZHPX2/7dpVFTTuMFNypi4RIgt1kId0srNa/BkUYSBkRs=,iv:6/r4Rr4KDpcqE96frs6AFoNOjZg6EiTL+tPtzaZgHhc=,tag:7slcO/C2m5VGwgzJpkr6RA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
