apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:0/GdUegdLi0M7M6Vagzwcn1q0bk0yAQIqEn0baECE08=,iv:1c4qxmDsT5BUeZll5095vNc2qsBdOIt5xjCzA+/mq+8=,tag:Fs5U+BPl3HwVjQ2mnqHg1w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBld2p3ZmNmOU80QnNxUFc3
            Q0FBQ0NHNGptWkRwbEhlSjVhQ2RFT0s2RzFRCjl4bGNWR0FWd2U0d0QvcmxHMHFJ
            OFhtaEw1TkZMajREano5UUthV3ZPQm8KLS0tIEYwbHFFYXBFMkhsMGlvZTkyelVE
            NVNkYUQvMkJlcWpOYnBLUHJGa0tFWDgKZDIePXmze+dLb/dOjhV/o463rDmWsNvu
            QOAI7BST4cWwOxj8dlJ/cTnfOQk9z4XflRqnQr+LJCe7mKGl21nF4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T00:32:20Z"
    mac: ENC[AES256_GCM,data:gqSYI1pvvaQaHerIXV1TwFmYViEUdXd8F6FMHvbwa4GXuUQZi1q77JpMUdrS/8HEVUE+2ZFZNWJ9abKRdXdudOP4N7J/8+Fb2FA6IX3nQGDWM3A8aRf9evSHhXWfSQ3ot2ot7o0BjQT8Bl/8Bw5uaS9m04ZJ8H1lTyPfUK8dPxs=,iv:B+hrxPg6Rv0nsSPADHHZZ3Fi9GtmLSwNxPVFn8NztOU=,tag:A78oQHaX3CbSE+Pgx803JA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
