apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:3S/fX+E5bsAqgf2Nf0+Sc72gGfhJfVvlfTKivB2dEGQ=,iv:7WbOsVGSrUffDmnR1skI86zt6ik8pizqwdWSxwIYIqQ=,tag:+v5rpGESSmErVeHvZHGucg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MmtPSUtLaHRRbStZODFJ
            Q0E4TjIyTFBoV2w5REZYQnNoQ2JDdTU4aGl3Ck1QbnZPamhzRGJ6NHQxN2RTUlY1
            NU5BSzRHYXNZb3BGOFZwWTUyWWlScVkKLS0tIERBdWFiU01LcFppbE9jbFEwb1hE
            TTN2aUdVZDR1N3IyNVFDL2FHak1hQ2MKjG7NcGiP0sFWgWF/jKNT0sZcb3gg+wep
            uFUZZtTxJl8Q9GdHJ08EycRTyrBozvUeZ85vH1Ql/+mqliqVun0ZXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T16:36:50Z"
    mac: ENC[AES256_GCM,data:7KYIYBI1Y8sV+isf2t7BRMkxfYfgvSxbGpvL6DXwXIuvLfSyElspX1Iu+aO3+0tdtnI0ijJy8WBdjUu0u6kCNUDruPjichs16kI/rPzKkfrY1S/IKz4Wt7VgVRXuvPP+T0zzWGYQ8nlPpShE8ZGOrD9LC8KsXcp3gLbEgrT9TNA=,iv:vXyGHOHWfVR9/pY0QyU/sHzUAaqTBmsKPoSZEEMrYag=,tag:MP96gj34rN60PTVZ+GFoIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
