apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:awi98Woh/ZXzjqoyq7KzevyFOPAPxfEc3XkQl7Ugc+8=,iv:PPs8HjAQtPkoH/y+I05c5FvfGU1jiZ3lk8wPkcDIxWI=,tag:EEW/jZN93D4VQj0IAohlbw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSTFhc1FwTXphSnJCRzhC
            YlA5Q1BqanJLbGZhTm8vUWJGdGZWYy9UVTBJClB1VlBoYTBPNGVCU3FEa0wxOHNN
            RENQQWFuOTEwUmJaSmN1aDAyT2JPTTAKLS0tIGhUcGFRcUhibjVZVWVScWE3RnRW
            Qzk4ZzF3ZG4vVDl4Wko4b2V0dVV6dlEKGjBFcnp0EEjpgRKMfsOA11ErJNt3ncTV
            eDD0M9dosZDHLSufw25rUFN2TrOZpjRdKLPph6DHsRko6aBI4zKG8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T19:12:37Z"
    mac: ENC[AES256_GCM,data:YDVP5hd7SZgF/rGSjwSImUnd4m62WSEPYS5AnxWfdhizzDR4gLlsJasNXmG2qqqGUbNM2582LqPY8BLocgCklqshExfMRMYRIB4TC8y9/HtnQHdnM6tiTAnvIkOFhTsBOkycB/Gly0ILAypGFGhjhvAmERI2b62iTM/vuiL11Pg=,iv:9asQJfe96zN9nIgLCjSeTCXRoX34r0ZCn/KBll/vOrY=,tag:wFsesh/EpdEdb4UhSAK98g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
