apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:uSIQnagUCHEK0BQuqi6EbISnjKm8dQR4l5+c42iHiHg=,iv:iGUNlguERCNcBCQzg6W7ZHqgwA3pGTymPfoRx9q33HQ=,tag:2QPMpLmsBQ3avFtzW2ECAQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwY3RWbldNbmlpUkdhV3BV
            RUlNL0F2MmdKZzB5aVhoblI5aXI2NUlwSDAwCnhpMSsrNXF3djNvRGwranpWSXpi
            RlJWV29GUnJJL25vb3dRSkZ0SkwzcmMKLS0tIFpUSG1HQlBtdC9GcUtlQVJESjdR
            b3o1UCtxSlNNSFJCK2VOTENURFJvOG8KmcqMqrVLLo2CA7LrX/UprIblEC6K8Vs9
            uAhEONr4rbNJ8e6wQEgmDLwMHJ3DMJkJPgvhZfmpxkiT2KWe1yiPww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T02:16:18Z"
    mac: ENC[AES256_GCM,data:P7aLSFhBi1rXo+sYdbp1/xK2w1goq+ZWV/DEp/c5yI1agRmE5fuA4MtgI7MxMUy2YlLVSDvud5aiImvqcIc/gr2/8xJt0B5t1SSDF2UY7Xq5zatj2UE7z+E2NSgHW1PWX/htIW21k3H0PNbWgS0ONRB1pTT1+qcC4banrGSq8L4=,iv:+1xyxVFRxRQnL2ntC6+5IvqKSt0/jSuA0MWwYW1h4dQ=,tag:vBiFKX8RBA7Si0s/DUlHSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
