apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:4pqqSkBAorY+SwajwPK91sPLoKvgiLf4srvIsqrZ3sM=,iv:PLyve27nCgLr6AsbYfIoxVPTEBNgcWeTYweO/TjMObw=,tag:GaCs6BJWufVMX7okV6vmRQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRHNMWG1zNFMvWXVVelBL
            b0R5WHN5TVVvM1ZxeFlwZUhMTU9DOTN0cGdFClVzNmRtZ0F4TkVWNm9OWjd0bmVv
            MXFMSW1seGM1MitXTnI1UVJYUCt1VHcKLS0tIDU5TzJkVXdKc2JscVNuNWhGNTlx
            WmEyNk82bW9vSm0rQjBiUEIxWkoxQXcKA1WM4SCnxoId1jO255NCjixH0z0OPtXQ
            lzAloJozkBeEeCfFplfgh5CV9nuIon+aQhFI3z/Xq5R8NkK5u+5h+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T04:46:51Z"
    mac: ENC[AES256_GCM,data:EVEpXRZIrcFibDW6t4l869MpTsLmxBZEpLjgKbhWKw+62I+4t3Juv/tEtw+L8bPlo8aE8DVTdm8GnsMaFLSJC2s22eD0TlcuTrgMtwFNJEC+XIbvSoMFvtwqJqpVt59bH5gUpuPIkga2I0yRVBWYEOhcRsU0uYH9uXRqbqW1eE0=,iv:+LkLVCBl/KQu4scqU+UkUSBy/iFuEkl0KptfAMedBQo=,tag:LCPtJv0l1tFGbimWRzLvmQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
