apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:5cA4xRZ59ecEeC0oqzJL8SOx4nRHP7I1T1YSLs1Owp4=,iv:BlXMYYZUTzfoGDGNLui1d6Gt60b01fCqRYCVmyd17dY=,tag:W0ciA+E20emW2ItOYni2Eg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YmNTRHZkRDZQL2tVSWNy
            UTZaeWcwRXNZK3MraEVZMnl1N3ZjRVZoTmdFCnBjNTBqaFNndlhZUFNlalpHc1BG
            ZjZobE9DNFlyMzFrbjR4WkVZQWRkM0UKLS0tIENkTld4UEMrbWYyVTNkNDJJaHY1
            Z2pKOExXb2JDaTFrWVRqVS8vM0tSbWMKjPBhHz6cEiXHhSnv3kzyNcf1Utbi8hlr
            5V5i/0TxJ7WezQ65et/B7J5u4oKfB9Zd8W8uh1cqs5ckc6wy8Ns7Sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T08:52:17Z"
    mac: ENC[AES256_GCM,data:LFEO2syjSz5DTzEDlrqVlCVq+bN1Bls6vdbUaN5vKaJMDKAaa7j/2ydgcvrJ19z4S8NQ/F5GQfiTC6KIEIFzxOF8SlAhGbM0nP7X8w69QV38h4HVltAxWJxoxFdjNudWOk17WV+W7uSfSHYz6HW2uoPmg+rG8xjv7ColETwQlJg=,iv:0HQhFK8t/m71hZNFE/cZ/4FmdtRFR2qwk8NAntCsRac=,tag:zxRfVkgOoUjhpHr5jX6fFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
