apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:aTXysh9X10en9qeF8cPEwBi5FGUYpKAKywFD8FNr7jY=,iv:MP73QKOgnWpTRP0KCSq1+rDB0P4vueGmQKP7MqsqGuQ=,tag:/HQDPqjgAgS3jKxhjDKd9g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGb2pPbm1YdFdoZktNN3Ja
            NGZaTlRrb1Vwam81QVN6V2FxdXkzRzFrcHpFClp0MjdXdFhoOVBaUVVab29WSWtQ
            SWhXa016ZGI1YU1PZ3Iwb1YrV0dITDQKLS0tIHVwb1hKRFA4aXhnYXlaeU0zMHRw
            djBFbFJFUDFWTG1aZEcyOW1XWldpa00KJ7Dt8/wOlKPNZLFt/wVqJcS/rATgq2ez
            VAF1wMx1qUWZwUW4tTEmtc1gj8Exw4lTW0Jbfj8ecqh4bYeY+sGgCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T12:46:41Z"
    mac: ENC[AES256_GCM,data:UvUK6Ts2+n+yeEL/CAoluyYYVvJRN/nA+LSPMz/5UmRuGO6VLVYOuKky2nySWn5mPjSzfCyoPD8cfiSf5sEWIe6vi2RKzwgxLMolvbwUxLrKLoJhOVfxUl2uNFZOVY8QA1u4rMSm8NG+lOG7V7iB4xBG131lYWq/DTvlJrUzAcI=,iv:E5Wfa5pFm0FMneS8okAhYXDBkjCqNTZyMIIbah1d7s0=,tag:GLFUoDaic8F+mcRXFQ4eDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
