apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:0kO4ymjKvXil3CCt/AFvxRc4OxA+SAkbChuQtd2y3Z4=,iv:/ifC8XsuCYxe1xSPCHQcGvT9h+JA0a0xlghsPjMHfBE=,tag:9L7WHFuMGa9fOvtN8gj84w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXellsQVk4R2dEMHNaQitR
            aTlFOXlNTW1KeTNna0hKbFora2IvVXF1V21JClZBazNNNm80Q3NkakNCbEZTbXRl
            U2o2Y1h2bXU1MGR2c21qUjRvdXJ2Q1EKLS0tIE85c2svYWowbGh3bUJlMmZKMk5H
            a1FaQUpvcHZTQktwMmgzdmNua2tFWFkKo66v9yamFYNRsE5cyQRAkh8ZAj2nGDzC
            PhOmvMRCrK7IK8yPYRgh04k32C4T1J2Jh1cUUOhEwlKY86d7XvBvIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T02:30:19Z"
    mac: ENC[AES256_GCM,data:nrZb9ytGjEvM/ANHq6GV1OoxkeoeKdT/lMejMm1yGD+HnnyAbZS5IzCJ5WQr6jKKEz918x3EKYP04YbLP0pQhcUtY3qd9BZSGFdEr+WvgulNupK8itfhxKZ/tSH86Kkt1iurV1Lo+q6UnAxFLxGgpkAOhWr8t2Ss5XV5VZLX87c=,iv:qhKugWHgfo2KXIGegHUmWJ8mZidTycR9TZVZZEr7Fo0=,tag:7HVZKEkLK2+8JYMoantcSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
