apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:UVAjOhKglkz2LGfdtU/UTlzaWNZHzHSATC40daHqBFY=,iv:Zpp6FUZgggZ0OgyQiL3NNlATbIowoenruo4g/exp+Is=,tag:+wVum4iPCleXziaPLSPkJw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubmk5RDJVdTJTQ1ZaenMy
            cjRHalY4TWJSMW5UUWlkRW5NeEJjR25RQ1VRCnJtQSt5S0JCM2F4NURnQWUrbEph
            VVVaWjR1VktuK2t3L0FiSEJnSHptN1EKLS0tIGpNNE1xQnk3cnllUFUyTForRWR4
            S0l0ZmlZN0xMRzlJRm5aUW9CSG9rSUkKfKUahxqx5oT4U6zMg8nzEQBBBknoSwUy
            ZkLZxHNmPiWBU9IwKyNvbZ4iMYc+aNjbjQUBHcg2xXNrz67pW4sheA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T04:01:23Z"
    mac: ENC[AES256_GCM,data:HflJpzWSPrNMYotO7JWCZilTzIgi2ndNIfjA8fAfEh7iIcbKLGO7Hj+ZeQmn+BKw5ib3Ju8lYw2V/ErCBpqNOKVZAw5JkYFvoGSqhhmVEJjnh1h886vhfXQ8NCAvIGxScDjYpGEORoLSbI2KZiDdFrcXqKNyCTNyrshs4/sAvF0=,iv:sTHpvIDVUcP3gem+HqV/hJ6JJVg+fJqlCKg7tjAC9W0=,tag:rRJ6tfVcGkXeOKvFyEahmQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
