apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:TCun74ALdz1WJZr5S1pJ3Kk8Qwo2BlulYiTPi+Abaq0=,iv:1Ku1SCGyq0K5nVS0ewU00/ggI0zJ2b/2jQlhVEcMa2A=,tag:d25fq+YQhyUdQrOqdULHTw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraHZMV0tDT0tMenpoQzV4
            aDlITkpmT3pRZnJtSy9tbFZHNnZFL05MWkVRCkd1SXlUWmlPUllLZk51K1QvMlUr
            cmNITW1nUnozcW9JVndXTFZyclhXajgKLS0tIGMxWGJLcm5UKzZ3R1VVNGJ6TTdQ
            YlBsajhKQml1Ujh0N0xTV2c0Y0hoTk0K/VE87CswO0MW+XRguWKxtUxWIJk9SGYx
            ZOKahNyZH9S1Tr14FMlmI7sxK2Zqk6olWAUnQwYNr35zp+UFxA8qdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T21:44:12Z"
    mac: ENC[AES256_GCM,data:FJ2WZF0UhRo7H3ATh5vFMN9cGbCkB57bCIWWXvMxipUFxOTHskdIGMSK/cTAMVU73ODQ/T9/dZ/r9ZQGN9Wnf/qHp2RUMbsQg2iGqWIPNuhqAkbkhDpl7IUEJveDpCJt4lSnjNrqLNc0XXJNRBLEq0l3CSQ5xe2eMhbyL+18vz4=,iv:sSraOZQ3G5G/aFVgpAdWJvlSlhTGVOg3FzzTKAWHBts=,tag:MVx4PBKSEl0DezsCRTevrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
