apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:A50REqRH4XADr0g5H2jemoR19+r/yf9043i1JIY0EhE=,iv:HJlqO2gr0RSAUPxkzH82jAXICRXGCH5g9ty1lovmkq8=,tag:ol8pePh9GMvWfCxdI60rQQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoL2hQZkxRQUhoUjNSQlBa
            UHNCeXBnUEg0bDk2RHNZQWJ2OFBKOTNJYWk0CklhRjNIN2pTb1YyeDNSRkVkelNE
            d0hBSHo5anYzT0k3NU1aREd3MWZhZ2cKLS0tIDRhK1g4ZHRHclc4SFVzam5JWndr
            R3hOOGxlMXo4YUVMVUJWbHhiUUZ5TzgKpCGuYxI0UfexT9AJcnvtfAg2VXDRU7Z6
            97LvZBNONtg0QwY+AMzzU0gU8FkUfidPL9l56+EmKyhH7zbCixY1QQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T13:02:18Z"
    mac: ENC[AES256_GCM,data:7PF21snFHn6FswsXapoHOFuKStCtPFX9tfWhUHIhCdT9JPuSsgLlPVM0vR5YHGBpbDC/dU7OGweNIjVtjF5gZ+qUZOoOkHZNVHoy72BGodF3mJCEhbR6hCdPYnuhX4VJfvFv4Fuujp4Ct7ve29bLqrJD0CEYOrNQj36oLylGegQ=,iv:baDJG9lyI5WX7lIBm2fqXKWOsqu0cwUO2zt9DkJcIJg=,tag:sMwCfm519Ycn7UKG91k2mw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
