apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:j+KsJ1xXcfltEY6xezM+FDHdjrywOSX31RO+ik4nA9Q=,iv:WSzS6Kz+/zirQ7FeqQnCHxJwxWj04vcYj9rNjf9nCko=,tag:T7hgd4lS0h41JwPtQFSP4g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VEhLaE9WSlVmNnNyMXhk
            T3lpN3Zrei94R1J1RkR3MTg1L0VNMzNZcjJVCmpQRStXYWQ1QzFKdVdRZkZVZ2Vv
            SW5vdjNCaFQza1lua0dHMHN4ckpSYzQKLS0tIEVVUGdpTzRoNlg1ZFNJL0twSGgw
            SVVXQW1CYXdMMWNCZE1hWjFxdEhJczQKHl/UBxF1uhQM4eHrCV8fYB7GOpjhAdQu
            74x4ePyMRd/fMmPifOvsD1GH05iqAK6E1jsQ+UJjHKjRmEcLpsAyxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T01:57:38Z"
    mac: ENC[AES256_GCM,data:bzcjz5VcRI7lrfg0kNOlsnNYG69OXEDGF+7erwvDPC0Hh2VnXNfqvO+H9CsGUemZzkbzrn1BwvyufKnRc6Aju3WhriT53kCX6LZbk3Z4doQ682aFC6Uls23w0hs8htgkWCklm/Wj+6mtpHYRakLTtxB6glBN1YjMvEVwSIAhs+k=,iv:se7B8s2FrWIhU5gqmisfiW98hKcmbYIALvgrEALh45o=,tag:nNZQhIjru3hCgz3m3Ky7Kw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
