apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Kex2st3Mx+Ocp4SOk7LhISIrBhvO+OibV7N3Ycs+eYo=,iv:+RpL8rN4vY6CLRGegw6Js98bQNowv2qlnnHvFXDhUYs=,tag:Mnom2lX0Megmd4Ji4D2/3Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MmZ1bkx3SHJlNjVOanA2
            bElma2t4bFJDOEo0eW5LNllsRUs1d3Bnd3lRCmZnbXV5aXBDM25sb1VzQWpjZi8r
            eUE0dXBKNDI0ZCsxM0NqRExTV2l0cncKLS0tIDZ3eUJ4WWprenZtUDNTNHlSdFRq
            OVNKUW5zV0cyV296REwrZkp0ZGVHQ1UKnEMb4rPRd0Egsdy1gXi83pKji9YF32mx
            ySJgj3QPNgfRJF70fb0KLz7EzbT2p3Lpg26yMoVsgn/8Bm9iKQW8eQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T18:39:20Z"
    mac: ENC[AES256_GCM,data:a1CpNf3hBzwm2Jl0ViuQTEOrFuHVbKYN3s0K03KyoQO8jUMkJwSijccKGBIipLfTPFztT5LvwdvNVGhcIuybo3XwVl0mB7WgzFSZ9SxbmaZXuVts2vCD8ARz7eoQi/HZQ2HBhBblcdA/HTaBwoIttVFwghXCvn/HfZFyUNTs8tY=,iv:2sUAUZU5qMhH1dbU04NBbkwEUW2iEu8XkORgcfSDYuM=,tag:15ey0aiDu6F1mP1azvZTIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
