apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:gQZxD4fiiC3jUIsQAXDnPlWpiJcAxBYLXSfYVkrD7oQ=,iv:kL/18WtD4s1GC++Wjn6yHma6F2n4gpuEnY/lgarl2cE=,tag:aMP+v5SY6nowBuFPurKotA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGc2VMRXFjTUdxWnhhNk1o
            VDZYTUs5YzRnQnh0Tk5Wc3dNMmZlS1lHNHowCk1jSW9vUzhldlpSWVlSSzIwU0l3
            a3FUdE9qNWlESm02VlBEWHA4d29UWmcKLS0tIHZscDhENHdtTE1yaDJWZk5Ia3lw
            M2k0OVE1TVBxR2VUSXcvKzFqUVk5YjAK4F8rNygQ1Vt8+Wf1OIjw0MDbM7Nhd0Lm
            Lgwa9oP0fLIYkEkWsLlbHvXjAbV7K6c1ZJ4eCSMckKwclUgbUWebWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T03:42:00Z"
    mac: ENC[AES256_GCM,data:rJ6VAlg4C0xtUTOwn0wlsuZ1CFNhyPBxzelKqM8Vq0wczx9Mx7m5iZYW7VqJ+xv7kDYucvRrlkWGgLhfWAF92uzO+7rahUUfwjOdQ7eVFh9e2ndS4+GVqtyiGTmglF6hy3SE3L6m4VxZpKrq7iYQnyUwR60zLn6IcNTtTEqCscE=,iv:nXQELpkEykhaVCX3xoPllFOQob/48FQZ9Bziy0o7tcU=,tag:qCB1hd1wg+KLuOX5WXSyVg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
