apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:EOidEQRUFux9QLD6IdOLhkeMHyo+PZzRHYJvjsFvrcc=,iv:WD5Z94XeXKa21e4kF3dO1vtHfJTaQvcrpbmLDBvXWfc=,tag:Y7wNj9VypKD5sZvvMw0zkw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRXFibWN2Nis4VjI3S0lM
            clRadC9ocko4UEpYWXhaWmI2dUJDemJPcnhnCjJGRDdpVWY3b0w1Ung4djdMZXNK
            bUxvRS9nWVYwa29WUVA2dmw0WG4wY28KLS0tIEl6cFB2UURXV3RHTUI5ekpyK2xQ
            eHZwdDlIckRYVlcva25ETW05M3RiQlkKN/oKhCrONu5Tv2qepE8Cg/50NQxG8fT9
            eyRp7EM77Qcft8jLbhJ71ufq+lz1jTmQnBqOXzANHjWsflkIiZDlNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T19:48:07Z"
    mac: ENC[AES256_GCM,data:1vG7+D7DgU1DWpsF+Blluk1mZ6KoSIjf15UMkID/qrfBDrAgFA/i7uVwwO5fJ1KGItgfQR1DknR/+V+xgEP724aVyXBJhHt6glo7/kunyJtzJmFJeyPa2VneK2AqNG/VAXOpaRqiVPr+DfkJn5iExwvjyXcokCuhbbF34+QeagM=,iv:Bu+TDeAOA3N5a9jDz/ExPLvNOOX3TMRfmSu0/QN2A8s=,tag:6K8ET9sgBsuzmKDK3n3Qtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
