apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:l8A/9fzIRhGKYHTkEgxS6SWZM0475aITSQl/b7Ag+5Y=,iv:7G9KTt6wtJIC6XjoUMo49gdn81Y0zzNhbf6tUymSSC0=,tag:yLQqVIvx4q0nfR3fxgY0gg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaWc0YVFrc0p5ejBlZ0gx
            NjBNWWJ3ajZ1WFNwQm1CbjdWbEhoTThRbTI0CmFyOVlTblowcld2VzNtaTVUT1pE
            WmxwalphUzUvR0YvdEF3TTROaXhFdkEKLS0tIGN3OTJnanZvTzRiWWlJOWEvZUp3
            LzFFTjVDV1pEcmQyUHE2WnpiOGNzSlkKvmLiL5/3D1Tj7+95Mb2CLfWaqgDO0qm+
            1Dq98DGNToNzoseUs/RgPwhKiu3Jh0796yiWfXnjrtitmK4OAwmz/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T18:01:54Z"
    mac: ENC[AES256_GCM,data:NxTOGvQxriLXYOy1p80fmKsibW66XWxUc7+0zYDjLfOyQBnFdfex0m1yNcAKGZFijIatZRHFf+uG24LVnTxwuGgL5gri3IRE3WOzKhgKKtYOjZgFjVUDXiI+sTIpNf5TKl2rjEf1LnphJYK4RvYNxhnrs3v9F3AZjtZK+k6YGiA=,iv:67FJTzEeNQIgy6DPWrE0G0McTAq5BcYB/CbtPTqHu3A=,tag:WFm+aiZGwTId10UxMa8LdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
