apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clue-solver
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/projects/clue-solver/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
