apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: theme-park
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/media/theme-park/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  targetNamespace: theme-park
  postBuild:
    substitute:
      GROUP: media
