apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stirling-pdf
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/tools/stirling-pdf/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  targetNamespace: stirling-pdf
  postBuild:
    substitute:
      GROUP: tools
