apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft-lobby
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/games/minecraft/minecraft-lobby/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  targetNamespace: minecraft-lobby
