apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homebox
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/assets/homebox/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  targetNamespace: homebox
  postBuild:
    substitute:
      # NAME: homebox
      GROUP: assets
