apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZZW28lHYZF4MmcwgQBEfhQQeybQXjc948jwenxadiagL7ooN9G4jRnhIBJA7PoMrNnSiQVZwzqU0qElynWXEFw5nMF7oZ6r2p9tsGQO2Elf7lY0tgHzemfGj7m+ch1jcwlp2Ci0kK5csvqhJ9M+AIGwF1hMYMQu9+deRq47UctN6OEqEJPqUkDE51gVO9Me2yG4xLsDGZiKPMAHBanXGoFAX1o95MMNoE6wZzL9w6xu6CnBnMfZloJcpCxxuoYqp2BOqIGvRi+pc45KAtIHi1jUPHNK+TlKQj+Ren4XtyGP3BH3Au4b6M2Yy9ltffv3xb5SD4qCynpxvLhhMfRKEOLovjTawRQIXRCGwa9c6l6Pfxq8hJoh+3GynjEyTOByc,iv:Qc7pWN4i0keLH7PLl1bTw9RGdxZN7FnOJBpP1RzeRi0=,tag:xu1+28gxXALPeyLf+JphDQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:t4cjFYM166hun1W92/LdaBb8m7X8VFy3nqgwbYiU2NyRgUOeyV2GP+DC6jtjkpimQ2OdGNQhC7I9gIkBmCdrY8Yl6SenxObqO5mpDQLBxZ/gQHlKT7mEUNRNxei6UfAfDRWCVk83ba+TzTVjzP/t4rnaUpdfDc/NN2J/eCtz13RljTpLeXw/iCBSS7ngZtilsTUAcRukxj8mveiHb2OWgutL2R32wJYw4c4UBrQTKTRCnU7NJijwE/4fmSmw7XKAu3O85TPn8olhIPQHVQ==,iv:bJTOF2hwKnSAm/NFbuWZgPHKnP5AADZNjzcShQGZ5Po=,tag:WFygfyBLg+2fnHf8i6JFwg==,type:str]
    known_hosts: ENC[AES256_GCM,data:vM9sq1CmEGV5BBqOwxu3sxHXOTxO/P+QN+STztyK/BHVyVjbrllHGmGnjXN8kqk1wizj7n5PIjyz6y7PYjYRh3GteHI6gvZmxJuTX1TSo93MMIXzocaxL9PGiliS1O5VHqLWNWMkMfzKP8GJZEec/0if4+laORfiz0seYVWZrxeYC5yp93SnJoq1WbidnONiG0c46cbCZephMzdSm40pXsRmSqiQ023QWUkX,iv:6ymAlpgqJiCdMMo2ILiCBBPODTzd24rMQZ6YNbRhmhI=,tag:7Gu7+59t3qZETeSklkSkwA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWFpweGx6elZadCtuU1ox
            ckEzSDdkNXdHMUtlKzd4T04vK3RsaG94WWlzCkVXNmNOVzZFa2NVTzg4VTdHQldS
            SHdUZE5lZUIydHRpMG44d2cxMlJVWWMKLS0tIFFyRkFxV2o4Y3FtQ0paT2tJek5S
            SnFXQkM1VTc2YXV1TVlVdDZPVEdqZEUKgGBreLTlV6zqS9Vo+KevQg9Mwpgwp4nJ
            +WF+XD+zCVor+YszVNtrPN7Tp/W34Svf9N76wUt+aiFp02Z6zMhxVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T04:35:27Z"
    mac: ENC[AES256_GCM,data:UrnksW/BOJsKUBe4YJfXQZH3BFL6qLfQ56oTHpJXOgdLpbKWnReDVBDVEdcON9rBSEhD1hkhDrCnbQjZpXhmezfsLB10tQx4AQNSjW9EUHKf46AQlZ9XkN5+rUpXi8jRfXzTqiab84BohIY+GVYIQwBUjaIIx698n50MnPRTwvY=,iv:ysWsHXDqKERIi28f1YJLM92Z7c7+CpKK4dhV8Auw2jY=,tag:M87LQu2UJcnw/UzIZgHYFg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
