apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:NvvVIy7mVfp4922ZwTgbphpzZ9VHdzzyXJHtx4Q24Hf5nPK+15QHa7ObMWWknaTf4J4ydhzr4mCvxOB3GN25e0xRppfYv7NKTwiIfcQigZ1oMCI/tmsLuPm49m+maM3ul5AF0gmKUdx+k2GL4g/RAUSCXT4ZkfDj1wd99FnnjrLI86XCPoJgjfZIjawsRsSGLME+iQaJlmLHNyI/+Lsz/PRJRqUzl7c06pFq7Q4xXvH2crmfkAZoz/XbIC8xxkonMg2WaoqMKjkWXawkbAofaRvZakD9EZ1lq5EAOsuSWBoO0ZlVTYOmyOQZxMx+xgX/6iJb3ZepJFBha8ofQjA99o3ub+kT4YVKAKJ3Hltmay6Rzbzag1MXA/1ujBLmXEmS,iv:Gybq9SbAiTMN19VE5VuC4rxvSvY7KKXMTPISI9tZ/Zg=,tag:0CoqIlNKGj3QhrhogTQOJQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:xt38yS4eXNlf05X2HQeOLoWN8g4AF6J2eC24Na3Ao/F3cotLmMJ2jGWMIz9/gC97ybY1OA+giVmo8GY4grbNSXz/74b94u5HTcGsIQltNtwQ5em9j8GX+A2DLCHtp3ekrEaL30CSSOXmsrRTcYin7kL9EeaoGocYSxvMTvCClEsvEGYNb2weE5pC/LLNv8fnI8PxeLj6gEp9+LBlFQDYIfqNHAI4g0+H679g5V236Rz/1Jx1xrDq0wwaQkI0qBOpBbR/v3CvGF/7cc31hg==,iv:xDjT4cvPREQyWeYwFrOVRzH3DTDOLcyIrtfXoafGtyA=,tag:VBEq4F1oxQtXN748ldBnSg==,type:str]
    known_hosts: ENC[AES256_GCM,data:ezMwdFvv15uTNKGmP70MS/lQByCY1gf+nc0bXDgD/VHr4r6FoxVgVkixjtpl0Cx32cPj8rEjOyChBSmN1R5wT4LgQufBJwjY1swXY7Aep4c5Hy6jYwm7JTG5sIa85++XFgqLJW63ePTYjYDm7D6Ccp6jtDeUdZKnJyiSg83WJgY1ZETpncSERshVrvVVhfcFoo3vItnBQqBWk24WEC+GB59BOSYiAwYt+Tjj,iv:4E4K3UkQ330CwTltZYJu0nID74Yt9X6IBDjoqWEnhWQ=,tag:lXlGK3cVrh9AWhYJ8kvvSw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldldTZ05ZV0tiWUhyRFpD
            bDBZd2Q5STdnaERWTHBuTkg4QWlZVzVtTTBVCktsRmxVaXFWVTN2SkZVRHNNZjIx
            SUhGaGREN0FkV05aaWFtUGhQVjFCVzQKLS0tIEJJZlNxclBIWGU4aHhRc3g1aDI0
            a1lRc3NnZTBmZVV3VkdGREowb1V6amMKC6c8Xz9BKlNN4AqPj1PuiWhc0jHD64Se
            Tjc/3cnhNHMDEL6IT7IKC8IkHWseBl+bi4Wd2xCDxQzg/zSezqyLEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T03:29:57Z"
    mac: ENC[AES256_GCM,data:l9vsEKBMjzfcrWNflxTKo6vYRZbkdtuRc0/5PZSI//9QiwNd1CPdUoOlP3cUO73L5/81b1PUpeZBG5JVdWoOus4b1N7uIzyyUWMvgFsRJVd3vH9/CmfwoTE7yKo67oLDtdv2HgkL9qmhlO2MPeuGNo77UdNcOXCzTlUs5YHgznI=,iv:zY+wOqpAdjuotx1CUu5S1QmEJlWi1fjFEdhuyy/u7fI=,tag:uJJVMtXSoJAFgW4krzASZw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
