apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:l4hBWkh0DpC6NRV4OquVbjZ4QYXYlG3VP3BEXVVOMFuW1IfUbhMU5PL14hewQjKntnfQgoF8SgtBGj1f3Ga+W2x0tm2CbEssoBWl6Lm5Dhi/WLsQ6ZVE3idkWzFj0K2hD7KgnnlOyJM2z1+7xF7u3Zz0J1y7zTwYb7JK27z/9hSrGXVwjkxyTdZjySaHKPZGxWxG41xRhZWbMNUw6DhbRA2dPsdR70q7jKspjX1nAFUYc8wRoCU862i5liOKeStxLWckFX2mJuzE5IWKoQVYcRTEU/G93gFb/3JlCNanH6Y5YolVUZp/25zCt8qkN1SHcz9iikEkpHmmE8F2UMQD/jaApsmLNwbiYlGe5kw5ulLBa79m3LMmJp4udEucPDY5,iv:bJ+xk+Dv3xweTYbGZDvNJaaQdTW/7hFrRQ3C+22ZmuY=,tag:BkG6ToBAWNc1T8odH1PC5A==,type:str]
    identity.pub: ENC[AES256_GCM,data:NKlcx3GWAvSaQ936BpmYmMKPxtQ1WxFdDMJE+9prSzlFN6qmhvvh543g2aEjNlKLpSSZ+xv8ZphoJF7PDD+KM6ljDrI/AOuNX2rs+6YeQt9bSCUS7yhBikfSWeGaz0Cl+6ni0FtU6QwbfeGQmyTEK7u/wDAOhzxto3N52rqurZZngebhzusnp2BFX+U+BODQEsJIzraaHKSric+ng+p4quelDGqEgzqz4MlgzO3/kLaSDTXNepbJKWL1z6GFN/JQWAZ3KOgQzY0saxOJfw==,iv:F/dO/Wg5PjxaywXv5jjnlYun0IfgT8l7+utDVIjjs4Q=,tag:CplQq8Q6C1lMQ7Dt70bYtg==,type:str]
    known_hosts: ENC[AES256_GCM,data:lGgngmWuAmhMY43QqGEyzYcyZVXXKeaPSvPb3SVUvs1iMhlekS3Zem0ps9GiCaJSjgVERyxQB5HT0XgtXGpuGJBI2VAyY5qVL2hSJfGJ4zlF/ulriLWq6WNoGKFdooh57+9u+U8BgWw0YRwiDain3hMF7GJVQlArgPDzVG1mbdRVY7umcgZd8L1kyXRjBdUGCSu8Y8SJWXer/xiPAUtH1vvVs5GBs7FuRihA,iv:2Vbg49IWKE7UeQAm2/g9JWEkqgs6bV51PNfEYNnJLig=,tag:dxBDczgrdIa8vgViUsTrcg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaOEJPOEJMYTdtbDAwRVVq
            S1dIYVc2OStKZ25ZelJwTmFPV2JJM09HRVJBCk13eWRhMGpjR250bHpVcmVKSWVX
            Mk0wQkQwcDhFQTdKTUc1OHIrc25ya0kKLS0tIDdPd2dQU29wS3dpSXNwZVppdCtF
            MmN1ZWVRN3F1aG50b0VvNjRJVkNWaVkK5yBVBBl1BR4ukOIBg5HXXmThS7dgyAVq
            NSilwnB/3czUjNZfPyfZul3VKmqWDpZ1+AcA0YJwH8c+DKsLyaQMrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T20:55:07Z"
    mac: ENC[AES256_GCM,data:N/OmJ7oSN+jx9GPF24BejwKm4hMt9ygS4STSezBUHOEewnZ5/0u1AQq32BdmJY2g5HWN4g0If5TldR9ViWxVk0K37ehEizVr412K2nVvjwjsjzKH1CKruGJU6nFUjVhvv7eFhRoG3ys9V3kab/FDKrVH8/6XF6zEJLvHxJZPUvk=,iv:arb4ewj8yJJju++O5B3hjQZq507ChFyEUs0qKCglxxg=,tag:Ino7ebfsk5oZYaiwPJfrgw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
