apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dfl1nDqF7eAVaNIjESeY5u2++Cn2AHoveufp2YEAaZRMy20JGLDcH9f8b6YCX21nkYTj1eRFYhTadjp6elFn8qJLWp/IaR3/prsY2Ee74qSxqO5zSosaVwcHycffIa1e20SEX9DnH6nQub/ypKivG4xSiOp4bGcjONwd7R4FidmriAYi1ZrogTIUyZSaqQmlM9vJ3wYtvGeeVMqodyP7oHuwhWZrxMgRsznQ2Jy0WKj97gTIKckxANl7ETJT4O7j7aRoVegXLxpVnGylXc0Nz+KapsZNDMjtz7c6jrKzlN/ypBVKxQxiQdLPj5NvGpnIJeQWay0qZAZhhX7QWKl4KkVhfRYnBW5Lhz3oW09/j+3muVNz/mRXyjI/MBtFz67O,iv:S87nWnH+cNOlykCC1mI/QlF6CI1WSvBnBTnm3mUd2q4=,tag:Z5HluIbgcVjbbOf3D2+Dpw==,type:str]
    identity.pub: ENC[AES256_GCM,data:AknoLe3k4SoGg9EtREH56IrLux1NnKnEuIVP7mnnXDly2a0/pWcsB7KD3EZRoBAMTbaNmvOCe8qgwK3YA1RIXyXTqWkIVq/aESwf/vX55oLkfCNiE3jWv1WGuUKXUwPpyf2kWaRG+e2jvFB7PNrzhi3S/10u29xzY1w/Tsdl5y7vyBZ/qH+F4Q21D0pCLv4BFccQylN1d2H62xBhrYfaAD5q7BcJYx7HU4edPCM32+8m6R3M+kD7HvvsRPRtSncPwcqX5TP5Xa/9HoWBCQ==,iv:/8Hddr0LSTbTetDyAlxASslm4qILZah9iSL6D+UqLu4=,tag:NGpAtgkjeZHiLQ6RkmCGlQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:zD3JnK4hQZIdz5vbNriHF9tSioTzUYsFRUez9dFVGUDMhCorOgkhWDK9G8rB5K3INV/thbvsLpSJvgG6bfm4VrTI0MDmHb6ACjjO+N+IwnorIVL60IjadQEOycY6KZFgPyWrKCIg2BfKon08KRcS4olewFZsz/OKVZVl/FPJVibaYlaqHvp7n75/bnIxF7YOq6Ja33EJ2SWedHMpGLQJ+GZ0SfPsqjeE2EaS,iv:CdF4s7cnjyRxfG1tZbeJsnymkx9jDNJwYVDj2pRQogY=,tag:c7Qk2ZJ4XQKFdpETn9C+rQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQXRLaytQeW1LTmhUU29w
            OU9LblA1T0RSQU53TUV3U3lwejdwT3JYZGlZClk2Y3FDYUJLSjFqY09tUE5XK0xz
            NWUyQ3FZejQwbDc2RFJDUm51MTVCOFUKLS0tIE1YeklkTTJTKzFURlZnK0pJeU1r
            TS9xcDd6Z0paUzZxNDNWcGxtY1JVTHMK7LnVjy1n3qpi0T5tv7ztlKsd9GxCFzjT
            AvD5qemmONTd7IWmcNeIAPd/JvoupUNqB2tNXf5MP9L4D8r69YxzeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-18T22:21:39Z"
    mac: ENC[AES256_GCM,data:miu2lHZ80URiip91gRBd6xWnqKZNa4/ySnQbjdSpBUY6yOxqkJZGe4rAZJ0gDPU5kcqq1j6ttj5V/+qtBCrWHAxPt2WKkPTj8PgaIE5F4BOBJZsgcM6VWTGLKQdDFE4lxFqmgzU9W66GtIx3R8qOXtJl1eliZa84Bd+Y9c63/4o=,iv:iNifX7AfNDDhu4urze+p0xmjV7fk85oUsLgMAPyUEwI=,tag:V2JUsBWAqx4mtNEWm5rPAQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
