apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:sqmiDgwOtd88tXKiCtKV9L4/Z5XYufQSgQxPnJ91Yjyqc1HNvBGjYeDk1MgcRSOwDb3fuOGjQF/TnPkIprJy6wuA34rz+vgMvqbGhbX7/2EWMu2+XOfC/3OYucIWSy9grzl45LlCg7hUWIXl8R6vCHpbCFph4eN01V9yH62wXszqjyx8/hr53s8NMW+Td5KgvzIBnZWAMqVJ5WwVAluUe1ExRn9oQSmpdRFkI811WMPQxj4Uo7yI1db11BDldJe0bcOHqUX5zkFmIzvaCScHFWuu8OfyCACOhCKM6sTqTuk8h/aSjAwLDVWdcG17w7l3bX6ZXGKoiXWLACV1Dat5RLh4CrM+3zZ/uTieV3uS4vFcO0uuOYFrjj+EDl4VQVK+,iv:2uNl8MhlW32qDXWpHduFEDL39wblldZHKGUpCF+3qik=,tag:kDZfFzOUtaGjfr7VyuYtbg==,type:str]
    identity.pub: ENC[AES256_GCM,data:BZFufWR33A+Hy2fmTX0NVVmHsUHNr6/OAP22ZOGIwim0wqtBZ/lDVCGMtmx3BGYGivnQuZx4+90QRdlk+QZ0mukVkQb4lUqR7lPjfWIv+Pj+xsQH38uMYKOPy4uzAwpMQ/7AqXhpSbrtUl5hwtxeEF+2rbmAb4cJbN0K3lbna3GsEwYbluig3ke+nwNY+GQ1aZ74hMUwgOTM8nqaHX/2NgVGeyM4Dju+0YCQuHj7juhCqlYCRWdUT0tldmIDUls/ZhoFVM0US0YuiIKbdQ==,iv:Qni5+1u4ZlqtnmZ+oMEI8xAbzvxOL5ctgqs/t8Lr5DE=,tag:BX4TdVQ6UGNx2/bLC4SVvQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:4r+hKYXlbyQuYZUSL/4uBOAtSoo/wGwn8x3aX0vggNkLlUicZn2AOftpn4WFEfPP475NTlm4fQ5dfL/50NLlSADquZ1OzLJTZx2PIosifpKPaIfboALnsI0lMh+ZFfe/CIF1gd7U77l/zwztpYCLVnsYgnYpmUEl+zCA+PzI4bnNpops1tkST/OuaVYdqGIBt9cqqiQ1eVQB59rFo/x5ALAKsJMYBivICKJV,iv:smltt5EJJSCS16PpgTjGXUSO4jlMl/zBWsUtaH+FiYA=,tag:RaYVlTo43fnecLuGQxHCGg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVkxDc3Y5NE5wL281citr
            NFRZekRwSnR5cXBHRXIxWUxsU04zREl6dW1vCmZJNU5ybXF6SC81M3JtVFljNVBj
            OUMwdFdjbmp6VlNONjBzNDVCZWJRT0EKLS0tIGpUUDJLZ1VnU3BONWFRWXlJcUZQ
            QnFjd1pmdnFKT2hOdmNRVm9pZDB2NE0KL2gz2xliNJu6vChdMilmuq0Le9EQEE3g
            ZU7N++Q+p6HWWxffmKzFFofPs135T1WDhfPDyvapCJGrguh0XW+hxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T02:21:21Z"
    mac: ENC[AES256_GCM,data:fBcBM9rWWkf8nWo7gpreYwjfftFxamCNHXWJW5joc5aioiYhakJe6QLSN8MD7WFqArEDYVIJv3Rsx9CGfDTpHFKo8BFJ+6KCJe2cHaWqkb1X2k+jSp+rUkMtxoornSStyrBa3winYpNC3BangvUTPEHKdb3myOpciAxBIuSx15E=,iv:8k+I7ohXgKLcaOfE7q6Q6+5UgmzXNRmeon+1t8lHeKc=,tag:arrjkBX+QtzVbiBmZcl+jA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
