apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dQzWe8NA3Ko/4UoLcmYjxGcyKboZpL0WNKJbo+AyxQvFKF9VRX7b/DPUFYvT68Xeo7sc6MGHjDuCfzSUxyEQAVVeYmY8mWVSMxcYz/H7FAta6yfReQ/+2XRQw0dkf9+MxKxfpehy8XJmdegBVtPfSWEAIOq5Rmsvagl6inWuIY3ydtzAQTocichD+wq5N6spRno0+MXVQGx5RCAJZ+Y00Nd1FP2d8op6ItfmVxGZrnmFmxkLZIZsE143Hb2HIJbAG94Z3dKM+2eA3q4G98wPv3pQrIwCAx4r+89MNM7jWMhrDf0Fn0yiB216WoTUeWlCtzJ7ywNmrjZkUVJi3YjJuEdZvrkx+ZNbdMMIKVylxwRFkvtLXSb2oqoRLecdty2x,iv:2qrI+b61Ck9FPcSq5VswuKT82KPeX1yUtARKLDz8Cyk=,tag:JsvDeolOyIGZjFShzRFNSw==,type:str]
    identity.pub: ENC[AES256_GCM,data:wWBNg9MZAiBlME65EU54MOkXxyXUs/gpDGt/8JYgoiVnYXJpBhaZkIk4qf9ScdFjxEZjXEgbGBCDL7ytjjHX5SZawWbb9qg2e81ZOfyuOANNFTvwvIq9aj8X0d8ZWfs/edLwZMvgr2BKgXIRZGRW6PufAP7K0Lk5npvQNRCPm2PX8SPtnVc4131kVcYaXqD1LsOlBqrNnHDeiU0f5RjroSqV3/uSWnBuVX5sstkqTy8G1BAxP86UDqCWcWyMYsNVeLmq1ab4AtVPhuM2MQ==,iv:NgXpcGjWf9zkX6ZFQjIrQV9Ssemq0yfgA07qs1YQBWc=,tag:vlIoU47rlt6piAVR/Fl1uQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:ymbTrVKn6rUu9u8hluvuUDDuMhvgVi5AQV9QKxK4/3WIobtk6/8z98fjN8QNjWdiAFIwF58qKxze48qT1d5K12HYBcswFG3r8F3PYsbaJebgsZH3ZSxogjiUGiQdirdfP2Oj9sgXlUh+9VfA6sGfXPfI5fmjauSX1uI7FF0U+r+loSpWlOU+ay9+4uho7+3k0eGHC8vsd9C9XznpTr1F4S/nAowltN5alPIm,iv:TrIUp2jThvZsGUnPOTeMLeaG9SB2iOfoZxya5zU2/iM=,tag:miv18Ob5corQZaPURYG68Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVWdDMWNjRjFZM05VVzRV
            ajR4UkFld2RQTFljSFVLYzBiYUN3Vk8wQUhZCnJIU0czWGhkMGFnNFAwbkdISDhv
            ZUVaZnFaOUJyZysycHlDblpLQk5NMUkKLS0tIG8rWjdheTljc0RiNWxHaHpEejg2
            aDFscU9zVXNJUnplVXh6QXdrUXprTTgKRpoQv/s0QTABHh0T82LUWNfbPeLpIk0l
            8npxS+ZoaK+4UglMeyA4P3y4bIL1UvYyKcm+p/qbLZBRYzjv37k5Ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T16:36:50Z"
    mac: ENC[AES256_GCM,data:DyhaOp7MSVJmO+qUSUHP6YSsVNHQme0PzhU9MXj302rqFfnT13arIviYRyKD3MXS6PPDiggpMCLgTcFtO60/brTZ1o3xIqCHWeE/8+dnFr7YYXqyPWcB1qkdM8+O2qDcqfQtQZZJth9jfR+wnq3hen+s2hqxqfEG6OArhBY4Wak=,iv:NyecZZrMqYvXEA5w4AwzRnc7I2RneW8tGDLHGX+G2DQ=,tag:xpZl883Af+tBhzwwmfDu9w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
