apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/bauij1yFji0lGot80FtpPQ+j3wPouJTYL5LJkSjrCMsvHCospbYb8065rmPh3mJYsKzu7qZfulKaw0VvCia0KW/78tlwdgutE2GeUZOj3CLJi6KcbvCPMhWTmqUyhfX3bz80Ont9vslBLLfWqklJFFdoxOjNq2ouBZMq17Zl3+6G+8yDnGbMSPUeDHID9spKTZIwhb/6jTN/jGW1GA2WFp52DwMXdFe6RAgZ5ifU14/Aq4xRg/py+cTjYaph+pkTH+CjWxMjs5QQRvE2AWhIyRRrejDDkoPwC5rJSJug0Ryb3yHOVa+p10f3TOga473Df1807kOzXLtla+xTCgtMiIEyXhASgUjNGmD8JvylWVkeJa2K8byNX6/FhwXqvFK,iv:WXbUHwQ5e1x7iMyHi9O7lg/gKGMJ2pKVrRxwHOnGRx4=,tag:47NB+IsA5+ep6BoiXGsCOQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:AWzyfoFsEfYhagNfHa6hfHUNPueMRS6ap6aZSCRN7VtnGenzIRQwk1Fae2Hz4P6dO8oEYUhbKh99mGs4RGN63JU6uIbgYh5r+1KZ5Gx/xtUIqKUq3LqWJdyOKpFJHR5kVBbeGZ3glUPB9XDxqx4cxaGvl0dFMKLojQIThbXCg7tqswkyRt984U3f2jWm5ppuR8fCeatetb671C57FRbhgZhd0sy9rTR4WVdT1FHclCiY5ODb4E51NvpUo22Lw8vtiZQvujFsazXIJOrPyg==,iv:5TPXzUPc19Y8ox3iuRPRX/3QDZ/v4/lihzEpB5YgDGc=,tag:kEHUy8jRarfMksrKbEpMlA==,type:str]
    known_hosts: ENC[AES256_GCM,data:lMidM1l8evQpY05z//BbgxEMLhLhB+hR3k7jNHOnu7FOjm33a88fqNtrFQnrYJ5cdRV2UvyW+9GOs6JpKJABu3KtqWg0u1a7ugD/lnvnT5Bm0Sm/NQOhyiN/h5Tr0A0O/mIrZ2eqMdaPgmFNMqH53U2hBIfpPAJYXq7zuc1YYUhAB10rvQuuUYBXvAV7/MKU+eohY9fJM6ZeR7ejlBrf54LFwiNdCyC1A3tg,iv:+fVvDi0xVJluiFpiVne4XLIsz9pLwgV+3U0koNF2GPk=,tag:k+Tl1v9+LN7m+nt+TmLElw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMnZ6S2hzNnZRY2ROSUkx
            cmFTcGxTOTNCdXNVaUt5bWlnRmRhbGNyNHo0Ck9XcXhTTXEyZDBaUThHdDllSnhL
            Z3pTck0xLzRtQ0tGa1ZYQlRmeWgzZVkKLS0tIEl5UE9TbzYzcE9VeVQybitpR0g3
            VGVQTlRBRHMzaUVGZUY3cDFtTHo0VXMKkkC4nAht1rQOp7tYwKkjXQkwOpJ8FF3w
            eAWw4JPaQIT6DDJuHaXmoFo2k+YCv8FSxBPSKcWFYnY8mZTezDfhNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T03:07:03Z"
    mac: ENC[AES256_GCM,data:m4ngwLHDJtLy2uDGltY+ylUxS1EIjp0yss4xzc7JvJb422i3yvzjNuAVThAX3wHxj8oYeQY98CGSJ+nAaD9Dj4N4bK2NWWQrUH4cqcuri0ty08CYuVgx2MFkMYSv6yWROnR3atU+NRT2LwgK/VvMy2cHqW2zqhiEe347dTh2I6s=,iv:ssi+4fYEWC9YXxniV0rBCysWX3fXZcYGrpWBptnAMCQ=,tag:O4xFSE/tibN25wYH3YfUbA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
