apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hASNldWi8KMcAuKbllTVhlSXiYQ9urey7iRkt/UWQRXoGnfltVGfp/KBOGv3hh4hVt5Wfz0aHHyQsWyvU9fg7Fz0qV9KglV1bIOGxEsCWs+3bjEseS+yZnpkZAv44B+RI6rV6mQ6SCPkjGGusp6b0off+fcLZGrO7RcE3qegLcrvKs9eHC6pM7sbJ93MoLfKvhYwEA4GyhKBWJ+Ip8iWNCve327Ys/S6Y1L1td11P31b23Cjd+ZFu2lnqwdwSpCAbI+OWSk3yPkYHIo62BYExk/NbRnaFBCmVbr5TvXjNiSAJq+YnXHICv920Yx12YEKI7S54ZlwbaSS4vqbK16FWlyix6krWCg2TQ+9F3lwhQaLEy3sZUsQQaJO6VkyQgGc,iv:nmo+DNtohli1xbrt4s7Aoifs1zg4/RXLXpjKdByH4eI=,tag:OvG+JPPmMOaIc/Wih2F7Lg==,type:str]
    identity.pub: ENC[AES256_GCM,data:80xo89zn9yiGwW1REaZu60fwEuSha7fB/g3Un1xNnoaDxtbLzVtMAH8wf14DgI3P7iEeWMcHv+kw2aTWtoPQ5+V3XMr/LEq/v3WTGQ0zADoSXO3+bdwVqTm3bh+eQDRibG+CBNJ5XGHWEAQoY7J9NyfCZuPfBXkLt3wIyGhenrhZ2m/wXBGnWpwLJ3Zgob9IhWDirbMOokLDu66phXjHGQH/qVm1TFHNL6lmHf/2rQvpPa1alQ51M9w1xvWijG5YUekbQZackeVkg1NTcw==,iv:UE8iaGG1+SFzs9nXf4ViZggQ0jXJplfBcormwREebHs=,tag:JHSNw3AX6G9A2xb0LR7FKA==,type:str]
    known_hosts: ENC[AES256_GCM,data:9MvOwfcOFO08AgbeaWkYHze8qEmuyJprP4WsX11U24YJN0XvDr8M6yVgU7L1w0H5hPOg5zPAa4mpp86wmOvO+tMr6yXth9iUu+zJxjdx5TQq/4h+8qdTZTRg15Ap5aiekPLzKZliaapz6b4XmrrdePJ0lDdV9r1OvgV6Y5YqPPOoGfqzLSo5rNWoXJftodVwmgebqztw7GMgUfwKEM0eU31xQ2FelCNMLFQq,iv:Kn+E8MHPNDozS+NVn8dK9kNuEjVZ664Dqlv5jPZ4CUg=,tag:0ZJb9IEG8wOsJAZawC1M8Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1KzRqTStubzZMMU9yd3c5
            TWsySVoxSjZsL2xtOWd4TlZWK3NjZ2VHWkdvCjRBZ1Z3VmF6R0xvY1FNTDI2eEtE
            ZTZ3UE5jbktYSHpiaDE1SHMvZ21ub0kKLS0tIE9JMElQZVJpWnhzazZPNXBmMXZU
            cDZQNTNoeU9QUDZiTituaG1lL3B4VUUKHFfToHy9l2tB8kcQPjGAdr0kpMZDFnrk
            x9OMHzwHvPep23G6nDzAGagOTEj4sPwbgTZ2iYnQO90vrRa4ryqdLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T12:26:37Z"
    mac: ENC[AES256_GCM,data:p4V1pXYEuEHs4bjrQBRaDe9tvJTkFwY1mOF1K+jtvkLFPw14fY+UJ5/AceBs8GXHS/D3MQ3E/lye4/z8VJVk03TmanG+gzPkrHMQCPmDZttLq8kE/a6oUGEsIRwj5khdn4HHoNJbER62lqJO3NM/h7rTAWaLqjVBnY15SLKSTFw=,iv:LUVmfZNV3qxOBy0IkZjDCL8YsjkiTnnsQWZdh8jU/dI=,tag:EP5bHU5xkammLdNl816cqg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
