apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5fO0EZ5fmLYIhXq11iNpXnRvKOkY2dvyg3I3VmWB67M7fM5f+qp1iy93hX+UIO1glxRPM7e8kV5ktQItFdcniB9SfvXkXXN6TElEz7DDGBdE857n5nHGIlHso9FneElbb+qTY0dfrZ39ePlKwYX2heAPuR/uLJgA8GKccd4591+9X6MIlJZsVU1Fspvqx47APxQ0JET6X23Hj4iEyoHlpKv0UwsNKUh4iETUdLp9aQOrV6HgDCBxEBCOng+PLppvYt7bsGYU/pXS9AeYcy1lXQ3ZVHyiu8yBV1rOl0MHcZ+e/Q4WagHCqzKC/3PXneLEAzKArdZCMK7dCfYInB9mCzgAW0/a/4LXGz3Eta1QEIHIJjgDeV4Uahhvysol/JxA,iv:/NlUa3TFTk71pITZdGizVm9MQL+ee4wxF29Bdm/Ov0Y=,tag:NVakNvLJvluYNa02nyKaiA==,type:str]
    identity.pub: ENC[AES256_GCM,data:V7BufGM/V/YVvzOKI3muvPRae6c2SfKjE5pfjcgkco4E4xZtfsYJqRhAS0Zm0ZC1r4A9ViZxqvYtJK/Qh4mFX/bTNMq2OjeADqJ75jgUcTX0ue97pf7v8GqUfU0ZSxravQ/7G8s/IJb7rJSy1WwmNFabZ4UhAsVn+F+z4243p7nAD06+NGCvmTOhxzQv4TrFS8w8iG7DhxbW1U1mx/h5q5yuAIzUOmBPORSvKfbD8jjRZERwtPAWTaZLlJ2/reKqeEtIp2NTjjtTYHyJFA==,iv:BH2H3NeN1XTimzeW9tQ6Yap+hmrA02SAUyU60BDwYaM=,tag:B1fK6uR/wHc02p+5Y+d/nQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:2lq6g7NEGT5lzhpxa2faC+sqP620b+64ahPXkNIxqb8APHfMYHzM/DiJP0FVfdiffhCVv90j5bG4wNa1CvbMm3OLctw81tjlBDnSTYrDm43hHHm1iECNpsLu64PhWNnteTJfaJpKhR1Z0LpiOJ/vZZkK4KfFc3GtWJYWA/JIXLpuxTalsLyCI9jhF/N0/ATsDzLKMgrffoJYkO35vczMEkbCrUdSj9B4zMn0,iv:9Z2hJm0nCioEvLZA7NmnIaOh0BrdpTBjxo4yMQtiVY4=,tag:xGFezeDgbzspVm4eOryxCw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMlVWU3c4c0pzKzBPN0hx
            L2ozWEdMSDk3bnBoQUZ2UVV3WjNzYUlrTWdnCjNpODA4WldSbkVhaUNOdGI1cFdh
            dmxWOGZyWjVRUC9ISWplT2syN2doc0EKLS0tIDJOZitaakxDVzUxellMOFZzU1Jv
            NlA1ekJnRzV5cVgvYmhOcW5wR1dGR1kKXDU6fzRkn0LVUKBH4xjTAVFpYZqq02LK
            BPw9WvINwBxj9KoJj21ZV7qKR49ueyywgxI1i9GryKsDb6NftGx0hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T18:01:54Z"
    mac: ENC[AES256_GCM,data:a2DRQBYS8+dJFNi2XyRosvCbRGg1WHHWWmIrzSqQU7zNopEElXScrkEchf2/Rz9qTIg+vegx8CzwSY9DI8bwOM9mCDkOGcbMdmFzE7GhV9bFAERxfif8B3p+S7jThgkKUGpEg/KhZIclnJcFtrqAWlmCFPPMolgi4TEaVsa9MC8=,iv:j91u/L9SXomMVPqZQTzrFy1ER55Rvsq/4FC/1qr3/DE=,tag:e+s6+UnwbCB2VaYADI864g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
