apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:54lyWte1eYMTbWsy75Hzj772m91ACnL+8Qbnu+O9nmvdCChyZTfssBI8seOxI/akKnfoc9+CV7/inDvjpbsBn/cMev92kEJuosf5+crzjIYRQuxsbCcWDIM2WZYwe4nbj7xsHJdCIYv8+NcCoecrfgNEvJS9XT7nx+DLmpiZ1vbRbSzVcY3rq73KrB/j/JvGrY9hIyotjr6SO6dHfqX+AQh+qfW+lIQcClT32tQYlRTc6rHXIJM3vrlubnkppO4FEgmF6Xl4OIdZf4Nqraecp3n5lN38Av6c3v+p/Dq+nNK9pXqZs0biE2eUkAw426idSTUp9c1+giNAI8Z1qFQZmYKH40WCCvn34cSy96DhdFVeDrEUPZIp5B583pCFYazT,iv:/fi/5JN0Z5izFj/lYgH/gUZ+XKDBoUYWO5XW713z3c4=,tag:Dr3wiCK92UNtT+tYLz6HsA==,type:str]
    identity.pub: ENC[AES256_GCM,data:2kLkg071y8dxbWZw20Izx05Gi8nxxzD6SxM80FM6DutKlmNzsHemmdH4xIHvymvjpdZb3UEo+Hr9IYv94DcT7LhJGbvUSSvnM0QE8nqelaCjl3qq8w5xqgiq4vV8dPflwX6jQBpmVYg2fFUjXvDsU2NKOuAqK7sKXiyDqA58fZcxjn+n3104XNGVWKTTRbaXCiKDATx5vDteVF5+ghyYB5k3pb/VOAwnYPr12DIjdRcsT34eYWQGMU3bLvlbqCKXzhmuC/77RgtORcLZgg==,iv:ze1dlecWVdANxF1DCnLO3LHq1OL3Erx+jYlHf44XUkw=,tag:ZEaEJQd1ZE3Jtd1ZVVZHpw==,type:str]
    known_hosts: ENC[AES256_GCM,data:bedizCLpct/DdC0FQqOtCJa2dPYU8MYex7t7UrrbDqxxcxp1WDIotGtxBBn+UtGOaoj6IYPkXW/c6M1oriacos1H51RjSdtFg/R0aPfngJx6Vy9xlNna6C80pN2h2Om1ov/CauNR9p/7t271KCogy1TAq+fkKbVZMtrmhaCbT0cAUdtcM4gzQ+5JTPMqUdNxnCcI3x3FcuDhR5+zZMgbt3uUWxe9Yy5kO2/W,iv:vJNU6pWvQ+A8mE79uAr/1t186aZFg++9EXRODbo8bMU=,tag:1rYFSlej8+Av/nfuDgDvRQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYUlQb256K3JKSXdINEdu
            SDZFWkxEbVJlbUZNM1RGZmVyLzBrM2hWUHhrClFRcnRhQUpGNGpaeTU2OHdCQWlC
            WXcxeWd5ODBWQUFaMkJYWEJSYWkxREUKLS0tIFRCd0lUdU9EajZJZDhYT3J6c3BC
            VFpXcE9LZDJ6RUJDU0gwM3Y2TUt4OUUK6fziUqyX99L1tGQ8hSJ8e/xeFM83vp7j
            MSbz9gw5RfR/AByaRDrugYJTGM1b8pt1qAYNerQyCc4ftbv7ttn/kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T03:24:24Z"
    mac: ENC[AES256_GCM,data:xew0F/fkphIpU9yyilvCi0l8JaR4IJEOwTvYrGUiqpBcRKMeFlng/6OyO0vQ/zBmH9ydgkdy5IvXcta3s2kMJmv5dNXxuCqC9p127BaWGkUoPY/1m5stvkt42n/Q5R/9QEVj66HFN1tO1w9VjsRtN2wr24aNJTMbCCcq42pq/Zg=,iv:vqvrB5V6FTWEfAQ2H8BaEFMQ2YDbPRWg2c/PAG6FKeM=,tag:6IfeZm6mehSWs9+f6aksSg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
