apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:RNw8/EY0slV0Q19FMImuXMonDhpF1Kv2v1abMi2bseWofyo7lVHhIDe2h+OR0givTnJsHZy/Lo4zsimH5zUfWNV79lAqi1OvaZA2Ryuxzyv7V4Fz67EC485cE54j746Lcx4ZHZMmb/t28vWkXKRh5LREI388wvqR+hHeeJSHobHrHDYlSYWtnYlXplfcxIRRdY/v8s+1FjGcBYN0KpzaNAYbUYwziWinreFR4sOnkGvTsAx1mkY6cjqTkBVADX+9/gN/SVKWAdrnB+uw1YYTBULKst8omJvSPPDyv4tNwmeSMgz1K6XJkE5zNt1t33Scgxm3VdR2Y2hZGhldqJwEuZSGmhIEpLpVYe7UqcEj2wDJd+D0rGeAorNPfCbAwtb7,iv:BuOzf89Q3L77jlteMgfJ5lg/Oi/8QvsGiadvZ+T6dRs=,tag:x8V6GnIqY3DArDDxmmTHzg==,type:str]
    identity.pub: ENC[AES256_GCM,data:ps2O21yoN/zspWJHtUsu+EPeyGtSmA4S79LxYf/S/ecIO7zdDzC7OtVPUGbBRItc3Ze/FFBvzMwD4us76/xgE1S70RxKat2ZemZ7G/iRPSr5Plr2B5f2xbhiIwMCChRrz/LYMihVQ6Vvy+RjiyMQQeKzdmWOlREd5earapr4+matOYHOsNC2Y5cLrLdQYlerhHaMeZm2VQOhQ/WxjqBD1JdF85uDv0hrlS4896iMBduHOGH2UV5kEEOF+P0dFlP7AuDwXaOGrKk7RlMD0Q==,iv:zXEQNLf9RBN5h9fg1W/FvBeD6yHmoBMFE1/TqX8Ow+o=,tag:6xdqyfomf8hboR5r6XHefA==,type:str]
    known_hosts: ENC[AES256_GCM,data:qP9zn56dDEhW6ZjfBAEe3qH5oBH3iCm46Dq5uG5+YHeMDwdnrvsxPEVqwUv+bjFbLWZeGEY9hx2gx2FRESK8/nlm20/axNnZ/UYRvaPEsuHVjHic6NC2EkqpWjldvFVgZWt6LogQ659A2+pPv3/ycZVojwEfZBFEsDVAH8fOSSY6UzihNUASg0o32Q1AHcTFgNz839/fhE3c6Uqi2RYeKRQodavlXAY5+rFX,iv:hhJFKKa/z9wu7LkYggKY2qLEavrHKoWnvN8OSelLleQ=,tag:ykP+hx2H+HQa6sgtvFBjcA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUkZJYzc5UmtjV1N6Qlpk
            K29zeXFGUTYyWmdPOVRrSUlJTWwyU2g4d3dFClVNUDFXWkoyUW02TmFwOW5yT3Nn
            RXR4emUrbmtEVk14N28vaWJ6S3NGWEEKLS0tIDBuV1NEK3gyTzJDRHRMYzMrMVJF
            eXdQcmtQMEZPKzJRSkZxQVYwY056V3MKe6znkdmJYUsilRn5oA0u5kUSTXmvfPVu
            42xD8Ba5PeOSo6iXpgEHQcO5zwaQh0lHYenJP7uAIW33fz3wHxB+yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T04:46:51Z"
    mac: ENC[AES256_GCM,data:DtDqt+ESjhiMEteuCQbJeT3kOH+7fv2DE6Hex3cSCsNSZ+622rvsaBVYwUnskpdFy9VNrTDAkPavWbgUo1AoxOF5NX403dtU1KMrabpqWpa+19s16I5+JQuj8eTNHTP/e5R022PeXds5D4Uzf5WjWyKQK2hMFtIR9scHV2Sabto=,iv:y5cVrqdbadhTQZHBojS1vvI14Zt3BDKrsGodhUU0ooY=,tag:q1pR6S3A1deDd4ynyDC/Mw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
