apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:yBu+FshV3G+2GRvsMllASGTJNzl/1Yy2BoHm+mjdiFvEQZligFe2399Kvy6aR+Wmw2GRVwznaDfpj6OKQdl7GXowWqO5oHXItgaGcCDxtg+8yF+6IYdDFPCWC2aLjQ4qVOGYKqzXJ/yOSdibyI8qOY1p2dgGUQUzPCgRx01DimYmvuEuvSnpbQUgGJzrtpz+1KBC+CvHjqyxbNI7OtlKZP8LDMMd3fcXf7vRzWJK2tRd67OSVzoD6a1E623tnAvwVVJ4NrdvDXOFxizonImYShsBwclwi/v5EnedyurVC8mMWZmd1rRDWUAsPWD05+7Hv4WSF64OHRNR28zB1Z/3pqQQdRMMs2LG5bt/9uAnizDHpvZApxwxsx7AZdCh4s3J,iv:1U571aCP0dIdmYQkp6irIm3UjR6gEouG0yiyDxF5en4=,tag:JSfWK83FPc4YTG6DEejvjw==,type:str]
    identity.pub: ENC[AES256_GCM,data:NEmdi9VrnLZxEPQg7PCkv5Ff50cuHxw/jNtacG7R/g4HvGorHNE/uHLjxLpqEpgRG1j9QWWlYS21/31QsTvXRgDvsVvVadDDfdgzJKBFgHrPGnpQrLqCzG345M2mOTfFnJwzwJde1FP9n2i4WRi+RwkyYxTmdWChWzsQazLPb5olLXmQFnx72+66f/M1QgVyala2pTEsu06WWZomfPYGmNaWAi1csd3W/PHnmTmFPcffK36f52rW3DcbUQ1kSU9lnJe82bImzJVaxCbuBA==,iv:qGM3hEcBQNAlkFJBdxy+EifsTwXlY7LtybYNdCtnQiA=,tag:MVucjKcWd7jf0sNGDXts+w==,type:str]
    known_hosts: ENC[AES256_GCM,data:2dwzlh3YLYts74ZC8BE21dfiM5sJ0ptVpHAyJKgKajv3pO1ZgyjTB0hZxg5CMX7t8PjPU6awzrhyF0PrMFnEdFQ5sCRnGuNAiWs3sZob5GcQ74v/ettZK9T3UbmdOArQyjbl8qP3RS3AGsFapTu4JhWWTjlAtBts2mp98CZNFKj7t5dNUstkL+2YB0QZcZ1z/Up4QkTzgUUDV3joCgktjzNiByiAGx1o27EA,iv:NO669WrBCJrN3YDkJIMQymnuzef97zJs45aetdTyCHU=,tag:JVHAC+e+Z+Q/4hLy1TgL2w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhU0pLQWxFZkkyckhBaUpr
            MHFmb0JDbWVMWmlFQ1NzSHY4SWRLb0tnWG5ZCkZzaHlOT1F4TnVHcmN0RE84NVJG
            Q2Uxb0RwdVBPSzM5Um8yYmtBOFlSeUkKLS0tIHVvVHRyc1NGd0NENHVYQXRYaWcr
            R3hrL2E3dCtoRXZvaEcvazRDYU83akEKFU62qlo4xw3AVJiIX2DKEMXg2/1URSFv
            V3AQsYSMzZPgjBND+Ey/DppGKUPW8UybNWknufhFktHdB7xAMbouCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T01:03:24Z"
    mac: ENC[AES256_GCM,data:PL5+5qgE7yvW14tUQjefOUW6JpYUfG81YPWiMAFaUN4+G/zSK49HFANcwz57cZe/1EKv6UBFSZOeTrELTVdLObmuiGN2SmBVZMyRpKGDKZtt0km7Mov1tF91/6p+z8V66G4E0cCXS0y+2DdhZzwVnszY3WrTNZSonUfUwKcfyIc=,iv:EIsECEXor50nkiCrHlvICYNbz4IxYx0QSEST6pSUAVw=,tag:SmeBrW9T1Ur8RvYXSbI8Jg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
