apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:6n/kDNA6h+Ca0pk8EhTRBfHlu5jJh3vck27k7qSvIVSmY53BdMix2DiQQTLdrUcoV8qKxpyMuxX2W1C9GohdM0Lizg+vAv1MXmOogIi5IhTmxmBeM3qdf3FRBK2Rlvqkz8fn1jdWmtaMpeoIl5Dm/3TcgSMpktAIELMpHuZOvOLQhpadBz49JOZ8ASfyPeAmk25fqq2JMNrw2gsAYebYk+vwK/6CBwmqQcrrnSBBRbjXlowkn14M6iof3LkYxUpHlYqgsdxR4/lh1U4e0ypP39YjfF1X7wrwjMbD+u7Kr2nMXoAIFu0seolEhnuBq2TeGMeVq5eL2zJHJEqzd+BckAZEdRvArB+ggjHabAADWciGXVXPBCVW1/wru1ujqb0f,iv:kWlgBk/3kV/h5npy0v17xgVEf9qHu6qkQdyUoQVhzA8=,tag:RK8AkdNIgSqq7de49NEuRg==,type:str]
    identity.pub: ENC[AES256_GCM,data:g1wPhR6vbhbJ5ngywCiB1R4oDhvhAIqv8ZX1BwtO063II2EqaLqqGjLWKTv+z0j5EkoJ5vT1Ff4yC4EyLU0BSFnMxhAFaYXjvw+/d3jVvgWg/EQ0xwfNYDZZMEmkIWebCWuL0WUX1PjIpyWRpvu+0jQitttH8j/lwnmRQSMQKE7aZMVI7wLaakVtRcy1opeKXDMti8AEiQLXmCAJfgkmqvWiArHXe1REm11piF91J5mzhS7pd6KCi/AXgWKEvMySjV37TJPlTLDFb2eZTA==,iv:yt+1w7hytGi0NjA7DSfjMbahH9REy0243XX10/fCAcQ=,tag:cP91Vdm7M10P0u3lAyj+kQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:3oki77m9R412bv9vSkuIKTET2N+GHmiMwWgwUUgIJ271X8wDwdSFPsgBS9p5SLITM8W/B7adqywsnm98E1o43DyjVltEgt8RDYpymUeqe95dJNwzNhf6jf4f1FwTAe8+k3vCruLltnwSRCQHme7e6dqyHNTP7b8jVvmZNPN6z794l3P+/sWeLc8csO/F+s1YBoPmSaH18XDS0BGo7kEmOSa+CH9nBd4MAu+W,iv:+k6SlXWm7QDt/ShkZneyJ2JzKg+3oRZWPXUp+ad7Jyw=,tag:6fXhmCqZKEixD8AnICCUng==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NEIxQ0JJeEZPNll3UkF2
            MkhBN0Q3d1VHcnNPV2dBNkwyMllxYzVaT0M0CnkvbW8ySWZJRW1LVmJwdEpIQ2Zi
            R0dkQnBKY1h1VmxLR3FHelVnRHY2SncKLS0tIHBKT1oxanZOS0pnUm5YUWM1Tmlu
            NkRBaGtUNkpIWUNqeldKVmhsZGR6Nk0KrYaCm/uoStxO599UXQ6KgeIyojRpFzqi
            xkUC5owNKyUbj0rWk3MVUUoMUPjjC4zAXsX4N9C83qhFKmGFdZo96w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T08:52:17Z"
    mac: ENC[AES256_GCM,data:QGjoAwkPx7yXDRs/BqPRsBSs9FJAKa8wCPdkZHXin/QCwjb/A+0aouxEE669qN3egAhVSyZdnZoR8fDrw8VNwATjUy/ZtU70SXCtjrQN2eD4dRyDlo09sTGmZmXGZJBY+njhn0Dm9y+/mox5pTqBQ+ETuft3WD6V99eVOF8MjTg=,iv:tplbWE0jGExaNguZwGE8wC1bM2rYc4TQ+Z73E53BLwA=,tag:kY2lJN/Ybdep2ciMIKZNVw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
