apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LmC/etnrwWLPTxNqsMFFwQ2xnm70VoGNDXLAHJ3g/V4FkSYY31fZfb8dqgxF6+Wkwt510iwRAkX21wmNAK9fc7z+THdfC8SIHzNLYOYW2tU1yz+ablxkzLXbI/6pZs6mIDFyFPm+E4bbkbzGntWIwC7HzL5+feHdnjKRzauDrJKPeIXK2IrKkkXkKp5BHAuRnlzA94EJmZdN2rWQeo51mEqITeLJ3VDK9Zc6fE1dAXI41uMcY3bUPn/CMMWisZ7wQNV6JEhrzOvRCYRrunGVmKjvsccYMUstsSk6C+HebRkQ/U9tYJ0ta9xR4zAQwf8Uy2OMBSi9uySM65I2yW4Ioe0pslTbDQKBMYP36rRcb2m+Yr2Xq57zCAiTq6yiV6Yh,iv:TveYDGs7fezppnbNPr3I/o2TLn0Ay0UeND78q/O4eYo=,tag:8x0lbwfSulkF1JMUMrimxg==,type:str]
    identity.pub: ENC[AES256_GCM,data:RQTJ5ZvzBI6mgqQwUK+9Cslaz5OopzfgViwl/15OMCq7BcwFGUc79fJ8QpjhpdNwW2v87T07ypHBODKQwKuDOebG1a7jbZL9LBoOCAxeNKqzCFDE29v9mfYK1mXdM2vLf8imh5OCtazXnVQegHjMwyN8wOrCAKdd9DDvxQebkF3cuqhyEpfhVk/v8ibSie35fqbavQYhJIbTZyswtKmNNLTtfN51GiC611KaLq/Zn+4a4KmWWi75OE9LBx4P3sZE2rv9jXsU+3qb5GwzGg==,iv:hydQslZ6MktfV2Xqz1BxQaLOmTn8l2i7quJX5Wmh8Mw=,tag:4kdA1pVnGH6cyylubJjhYQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:uMAt3qlGTNS27dESVqolewrg+wEAG2HY58HGzmFYparWPCE77mJ6jkwN1IfG+W0TY8eYCjSzFC8qhgd0CHzTTjDCF2Dy2hp/2gaLYC7z/omK+HgspL/kPDfNFLZFor2KkpcwXPRBDKxliA5F6rLI43P/XwkYjTn6NGyXNjdATSB8KQ/qCOM+L2l05OAtnl6AbCznaTye9KbaGhrcFHvlBjV3O4d7q0m/Ydp0,iv:Iycbx2iAC+uCf9eEadQygTjh24DUiLeYWynIyiOI1/4=,tag:xyCYg3pIniguJ4nOtK1g2g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK1h0TVBuZEd2Z3U0QVA1
            bGtDWmVPajVINnBMdkdOOTJRaG4rQW9FOFNzCkpvM3lEZVN3L2xZVVR3bVRSdTJR
            TzZIZlJIYkcxN0toS3lTK3BKZVJKMVEKLS0tIGgvSDNRZEJXeERGT3lLaS9IZ25q
            cTBqeVlURFgrcFdpQVVxdnEvZ1R5TkUKuif2wSU3GMVE1keDw2lfz+QXGGJr7ZtU
            heML1WTgXVrjBRO+eenSNeQs3eBXTENVTYvAK4eLj79PPyvrzjC6kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T00:32:20Z"
    mac: ENC[AES256_GCM,data:vQ9p3pEzg5eVZNBWM0mULh3neqaLiqi+JYu26/ybQCLjVik+RPnBoT/tVI5dmFT5xRslHW4iU/nmyidrLSMDfXH3xz2dUzxaBCjJo/0QBO+rkV+JrowZqbbZs+wPMHJkN/Xh7GvD+XhczjvfClgoiaUyYJioYJZryK1tpirni1M=,iv:2ystLLPKP1Eux45uEoTpsLK7Mu2xjacgUqqqv7o/+Aw=,tag:JEory10UYd4PltQmecWYCw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
