apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vEoKDy0G7jOsjyQjMdIGQ3+zkMIOHGUyV1AW023q7iuta/+uQbnFKJUFiueXL+35RFQgl8rxOb8xXVqHnt7PdeA/60lsZsAmyCU94y6UHA2/33xDzzxVrDe1ppVn4eZn0eYP2G5BbeD+njgg8a3fD14qQRs29xEVNLqAlCZ2Ty5vhvXrX9bWA/3NC6NiatI6JDgFEvEMGqObr4y43SVisKk+b7Kw/sln+bwVMF1ZcwG6HAHi3EnIBGEZprP5EkhELRSzBpRvuXt2U4De9N2FdpMRwlcu6P19IcHFzhBF2Igzk315xe0/6VH4PxtIKqpFSQMCpxHR+SEs0BirhWSJYLYfUdpilgdsryaKYUcuvzlOBCtI9o1w8PBVGk/7td/Q,iv:/p3jVi1dS8+L2BJlGC0pYpjIKWf7uWkTTIczk1YiK3s=,tag:erImzwkjZlp+9CI9KOGkkQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:ogpBwoZzVIKMqdb/LL9os3XIetFyabmRCzbKQ0LS0coKRzQCavwrJwkk6vxAfURGlKneu5hXZ1aJZVIfsG4jvK+ZI/g4tHpgTcZIhHB0k01XQQ5CDbUdPRoMeHD2xrl6aUuxPchNS29ReJ+mhzppszNa6XIlZC1zV6P2BYDtYFCRSOue8AUsLo0GsulIXXA9KBoNc/7kkw4XQ/gpUBMRhLPYDwPX3uJ9aQPcmxRr66lNZjfaGn3Lh8du690N21QGlP2pNeO2VFfcb8MW/g==,iv:qF+v1hl0NSTJQt7tR0zJ3p8f64Yoap9edy6vK+4Loc4=,tag:TT7AQ++bIpMx7RCRgelmoA==,type:str]
    known_hosts: ENC[AES256_GCM,data:N2EOg9jpz4VhmXxkau+vGeIjWENHFQ3TjpbbeS7XxZL/C2M7xvdzb+/FC1GMDHI6ooyz7xZIm5t78a9z0AYEPE/jNJtYEtxvUKnOYb3CUQRGc1lu/pNVZuoHmwipHHAE8pCBYltzMPChgAsrLm3wB1tBRMbopywHZ63wWI9ASh4hTdPa77H/ZbUTd6oYshGnw38SNqkiashFuTr4GjnASRdc0FJqjg3fc19A,iv:gqzsqPTSpBisdQb/Gy6O7wrFryLwl8qActClrwallEk=,tag:W9Caj2FfyvwunK+plXCIMg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZlByU09HSFpWcWwyNkZK
            V2laNmhObnQwc3dMUjJaeHl1ZlZKMnZxV25vCk9SeEgrTERKcUVkVVp2MGVOck5K
            Vmw1TFFDb3EvbDFJVEpNL2UzOFd3M0EKLS0tIDRkRVZBUjdkWmU5aEo3RzJvRGkx
            dHpuL2FMaS9jeWtvSGxtVnBGR2o1a2cKe1FMe3WbcBJXFV68VMB98wuK8NumMXb/
            hL1mwgeEQXHqDFEZgKPx5B+OhcXLwdpfQ8kkgyzD5phjtsU7YujygA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T02:16:18Z"
    mac: ENC[AES256_GCM,data:rmO7w09Zyd996qDdz5EmCGsKXnWtc7bgf1crGvUFL3Qt7S/gINNdckOGwdvuewar28buQWI/10R81a01rW5N/mIGvdkptffvNcUuXxUiclrL3CePUx88nPEDmzKlhNVKvGSfmH/KUlD2MrIkjIfzDTikp/kMSm/EIv7cPs80XbU=,iv:A4d+ByqM37tluZN17OBzvW1lemb/t3OZaPvndIWibTU=,tag:BiOmb26GxL6QCj2kZnFaGw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
