apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Oee1cEblMTT51GXVIYb0I5o/Fm5W0QWFMu9piCAIo0bR0i1sKDGJI3/Pt/94Os2kcwlFXvYJ2e59EqpZK5X+6McsgDyRRTKjbmGGMwbAXNqZUGIBHJprUnGdVElR8crzavwWFs8m9h4zIRn7jXnjq1+yuy/8kH5flEmw/ZBKItBlDVRI+zdx8FhTNI7PVf3eBAdLWudZ9cXewYvBPJRswoCqMHru3Cn+8asxte3PslUHX5K2UDFdlwRM14MZd8NEuvvM0Yhz3ZhHXeqvjyO6hbwcc0ptPhJ21twBanmMU5+nzwo+bdQiwc4gD2Kr29SVEYrfnaSXNP2CldpxIvmIlP4gS4iR7Y3OiYCznucxXBYvP5ZT3UjXGNtHQlGoPu0w,iv:/h0a7ibkhBvAGmqyC+ASJelyw2bbGJ19sgHRRDv6/jM=,tag:OV2kIH7Ob7QJrf1KzLeKsg==,type:str]
    identity.pub: ENC[AES256_GCM,data:PBJdW6Zg3XWLYNGpDFYBE6JaViA3K4h6Nmw3B53ZBksGRh9ZulyPnMWYnCiY5mFEGkqHXQDWiM6nIFGNRnsz3HSxRmYq3nvOuwgiPsezJpwY5bJIdiYYH6V+U3JwnK6QkD0dB+a5aQ8WH/sQiOARisP+fMjQ2YYp/nyiKZmshEOUjjxo8nsmCXAzxMSDSUU01EHPWKPNiKgjW8XC4twECD206QasSbXxYlkMKH5VmXRN4d/M0+kPwvXdgimb60Y6oCvz/VJBEfPVhgG+dg==,iv:FbAKXdiLZBjAPXC5H30Urnjrl4xd15hC66oWHjEdWNA=,tag:jZ8LtVJaaw7R0//dgVIcEQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:SG2nDKYbZx024ZD2mSBe+fCDYJKZrb5iJUxHGnOsY2Dp7vGa0J1Riyj6ndufxuUzVphe8gSJ28WjSc2p7oqZCJ0iZffdHRMVKN4Nu30WLp9qNsjQhDjVqN3otQNwu+jizAAt9kUR3XuWhRF4g5phqGIqiCY7KXSaPe5Ix2FT89x4QMOdUvBHb2eNyIs/VOa4aeWpZjH4UHv09s4OHBJl50Od5u+zIY3OkPqa,iv:CAQW1aOuOifDMmlNA6NmknRzWhCv87zluUqPltvw2ok=,tag:vfQ+5DXMjpgY+oWVptTeMQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUXpzYWs0aE5XZkptUjZW
            VjlFYXNCam1XNkRzU0I4QXl3OXBQYkkyL3pBCkU3K3dDWVJpUjlEQnNKT0JCaDdy
            RXJYc21tUnUwODlxSktHQ01pQ0YxZ1EKLS0tIGNhRGM2a0lVOUs5TmNXUzJkTjRU
            WU9sY0hFSklySVhaTmMwWGppRHhBSkkK1u/s1rZOOmr6IylaCjytpTvQ7khYKLgT
            QZ1DMAtGSCnN+L2GPV995J9M88UBn33EX74XcIfocvVCJ1R2GCNWUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T04:01:23Z"
    mac: ENC[AES256_GCM,data:Zhaef5cgb5KHkO3JemZserPSPYvrNuVPQih/AZFaAnW0xWZAJdulfFiJjtYXLvUgQCBSMYVbXCLXHfJBYHFpPbYWNSiHf2gUDrinJrL3zIVKWDV/AFxdVQ9zGC3NC5GH4lE4z+8n41OOeRGfXGJf160K5onmrHj+iEIvQqUIlLc=,iv:IHfQbINovXh9GDqtxULm8rcRCzka75rZj9byTo8hHqs=,tag:Z+SPcELt1FkOTBcUgEhfLA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
