apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:l92EjTLcZg6bw11KYD7cgVGeQuXFbjXah1/dgmJrCXpEzZUt8jJHtUd/VmQ5spexXA2eoQkUMSF8wxa1r+VoyaLzvaoXhVbQOlfwRVc3v40NpcfYa+SHe3lJw0quU0Pi7apYABscv76UYlcbr1dWE4pyxD8hKOTJtD0+bqP4q1bz4LSukHikp4Euz2eFSxkCByO6fcCPx5SkbwxNWIBjKqcuHUnE0KxmP06eyDDft0GLQyFjkgHy++qFQYY9SE5udrtqBz9sSvFuddKF6yksnzhqXHpOdEcUN5i+jysmxOmfzA1OIxT8S+1pNmfeyJVyHZAedaFq1QTxlh/1nJHzn3T3eN3c6upfZGDRv+UEgPcfUg5jw5F/cyyTxowspdYK,iv:twUP2pW5+TvlrpI+Vmg5OH3s1HDbr0o83JC5oqxZomU=,tag:AIpuIs15J4NZfEltjcqIlw==,type:str]
    identity.pub: ENC[AES256_GCM,data:rtlP2/7Sq+QMDjNZGJz3QZed4BoBLtsyX58bhxeg3ZFprr82pZ5n3fALDyc3V0SFDwRJy+5lbcYsoYQPHSb9NGCPRDOUyZScmPK4icf3O+wW3U9Lt1yai2nJbLMcoP3iRyPXKCFmNYqhEz8N/cRj6v48ZTP4aoGhdIAuWmVkR4xvf/2XTAj6Fwa/Jr2O21cBaAwkN9BcOPMigO899ASL9LcOv6bmpTon4TN8DHUg/eUfhwo13+ujwKuhu2r8ZexjsNzZBsZc0n7rk8v9Dw==,iv:CIDKgsQaxmyw97Ppa+Bd7abN2kTM1RinazP56KMcf2g=,tag:TojUBZOJJ0qTGBrEO/sh8w==,type:str]
    known_hosts: ENC[AES256_GCM,data:oGbfXJkq0G4ss0eiIsf3GYNaUEkVU8FXO6jL1D2u9X8yURke8fafopF5mnUDL2PvEQcaol3bI6bvZ6xNLzZ0+S0jeWMZWuLOSM8bXWi16/VPE0mZnhOE1XwqG82sPlt3il6QfUHNOae2HpQob++yl/eZ1oF1Gv75vDeYTpoTl2xIQ7rfABfnrJFxC1mBrwuw2NSrl4NlvhnOxBCLfWTM1LAeCQup8PWeU0kd,iv:QO6obQcnf9bNTJh9M5bFZesab/o5b0L2SkatSlvnaXo=,tag:RWwL1G7ypcXv9MUYCVTErw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNUxOY3Uya1M4dUxFKzBS
            QnI5QmJRN2VGN1IyODJKSU0vbXRyenNZNERJClJhSFpVSy9SemJUdzcraVJITTY3
            Ri90aVJBOVk3RkhRb1YwWHdIKzY3QmcKLS0tICs4KzlpN092ZDlnS0ZYOVMweVg2
            RWhQVEdNSDNjR3hYdUo1YUpTd2hkVmsKR872ImIPrHtQJE1Irq4Js4wvt1WEdfJ1
            cXJ1vao4nbEnyJMfFE0FLs+bgM04tGkyrmqB/8/F9juNjFTvmg7q3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T13:02:18Z"
    mac: ENC[AES256_GCM,data:CvlhTZL8CYn68R9yPpiHwDbbMYXvrfrDwqnk0+cKQ483Nw8R4Ipgpm56VdK6cRmpn7kyIaRkb0gUoofEC/3wRnsojRIRzuWyrQn4jWCRTtFn9g8ZDw+uYg+KvN76e9MgtwUaQjtWry1Si8QmSvWvvvNqpaLUoyRvARvsqnTwXDo=,iv:V5f5N5AlOmYrt9HPxKCs1bS1p03m9q0IVXp9+/SoW4g=,tag:opBTnyEEqJ+LU/mTcnRAhw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
