apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4KEDP5Nn+PO690yxrFQhsstMn/u6dOVwibNd4CzkjdPUB7WeQPgn3rrEqkYCZMoMGJpu378vtgR0HVu/b0V2jh2MfLu4ADppLe9NY0YlQXIRZkOfsM2Wf0lEdpCtnAmFk6l3OncYies4AVnEcZIhBPRgyLHoeB7s93jQP67eVanlhTYOkIPkSWkQ/PRwXAuKfE2cmiyH4gWXkxGEJAex2UsZUrApugiWFNEJzP6nDgTdO/kRrE3tC6M6LRu1GeZccWg5i1QM3z+dfxnr2vF80Mci5DjJdRoZDpW1d6Vw0IFTXN327Z/ML1ij9RV6YwChNu8NJ7cgxRupCo34Wt95ozhAQfimN/HW5D/5Cny3LI4KR6wdlJwYfOSBJ8N0W+Wy,iv:5ORyz2GznJU7zWbKhLfPsZwjjpnY4ZLvG49cpYTnhpY=,tag:6Pq+R017mUmV+cdCcY3yPw==,type:str]
    identity.pub: ENC[AES256_GCM,data:jEL4CnN8FwTDqHph4NFMLlvKDTXgnIiuNQ/tpLQxUbM9zeckuXgDbB2kwu9iqKOnCb6qOrrZgO1elbsV2eW6OEV1znw/TSnGQ9tLAdlr4M4KZ4xLZ8wJ2wTY0Wq3/7EzCsEL0da5k3qrHn9QqkaILuBzDi6H6DaXBsnjbRiU67T0iMwEgZvz70wpLOAWYfWxrndw3FsYYz/G6fgx87B74BilgBrcp1OwErHkfWicdt43yTjgrq+BHBYwh4T7PBrWDRsQSZWBF1CBdW3kvg==,iv:doKaC3lqbdumm0whltSSfbuIEph0Y8dmc3i9K9UH1Vo=,tag:MXHOxP7TbuITqZZs8i5aNw==,type:str]
    known_hosts: ENC[AES256_GCM,data:Zm7EWsVFz3BdjcXmqrjBWA1k0p1uZ5O9GeSMhYBAdNCi+1zEV7c+yf2WeP4zsrVHeb3r57pd5mtB8x+VeXRnuo08CIkrIUum9Xtp2UmN6K5+Egrt6OheDxvUILUQJ9o33LCS9mh0yA2oFnQ/K4VVBETDFhSMP2qewwHW36Crbk/VhSxChwz1kzv9VsF/XibfXsHS8I6aT3v2MO/AMbx70sKEthVnHi7RXfCn,iv:oIHYwDEB0FHNBw9KaAH4F2efjQKcJBCE00y+MgIsmAU=,tag:OfCYuZHPBj9WGmARlvB5EQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmV2tubUMvVC9RUFJpemQ4
            VFhyMXBoZ2JmMy9iMHJ2V2VqUUZERWJDZGt3CllBTjdaamhjRndXRXZuTGg5WFJ3
            TWZSanNGM0s5MHdiMnU4SitQNU0wNGsKLS0tIEFqOVptVUN6NmhSSS9YcDBvZ2tU
            c0xXRU52ZFVXOFlSbW5hU1Fmb09WSG8Kbv+9jWZ4zrepUHXu8IvrIlYGYkArjCE9
            FnQc94yHZQh9IqBxgk0gABo1Vktu5ZDSPwcGNbbk1SfY/sYQMBGOxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T02:30:19Z"
    mac: ENC[AES256_GCM,data:TK3hxal5EtxqG0daeTA51lpPxegGgmqa1w2YGW2xB3UX7iYdyHycRvBwyRf+ZTc616WXyky1ifGO1o0zWzcT8azbj1qR/nRw1GZ7jy9V2tpp2PU2spX3QqMYd/tORs5vND9PB8QHRuz+NlZeYT1M5gg3UemU+mBFqq4kzYki4hg=,iv:ZX+8N92sQ43YPAeMXDjya29bScccIm6CriS7GLZCu3U=,tag:YtSXFTChGSwui2TD6Kbl0A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
