apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hrxkuCneYyptlIXRhHM8/6P9/AvKj2EnFaGogOa5uLfgevsnfNJmOJihGtAAk48HYDhMONfHIkJFuSb1DfD2uY5sQKXv06j9HrHsz2EjrNuHyt70DUyhfED5W4Cyqx/3MxSrElCS09lDa3tgtBMqk2B7MAYdIMHDnl26vdf+m8UYuyiraEY2nHlBOVf3VFFi2jKhWK7uFLWo9iId+3uQRn7Hkz5T0tbpv2jiBiKAd/gkWD0o2CTJOMVp4s4zOMmyKR/XWwnRBefd+laQD+Llogg0GWZa4qurgoz8SR3FhwwHNg/0JJJZcHod8DdKruii6Eyv6Q9wx4Ws3mAys5w74vkW8KtKexyFkpeRpmsYb7N2odaGgT6S2gijUUIsD+Qk,iv:YwVObKmObkEgC+BWbzmtlpMUCWG4QOIYBDcLZxsOvZc=,tag:Dx/VliDJ/1dpewU+Ata+IQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:6tQ9La5QiRUPLVlIcNrGuO4bTdwuu8JvFIk6qL3YoxeWDzptz/3hSEoaG0F4BSjuudxweXdscbxMm7fz7RZtckIDoQIHGN9VEUNRi4VLoWCBcKYLDqL9dMdlXtR4hjRhzxCCDfNxivdjj4qLWt2IjgCNnNjo/TlJCGDU5ekQq9b8FvndkL9zoXkDucqE5fJ/lLoXK/pDsGgAOrqp3iUWzctnBNMS2JfmrB4dmV1PfmfgR2E2c3E82DbZRa1gpezwjOe/hrxQYKI3tgXkIA==,iv:/tc/+83tUTqY1NuD9T4200Px84nQdhK3iEkDEv3kGGo=,tag:ODa3NMKES/vaVtdgjCAV2w==,type:str]
    known_hosts: ENC[AES256_GCM,data:qRSlDaYKes57Efva0kChd+zpQDTY4+wjzzuMyuxHhgjCazIVyy23oHO0n2/PgZj1nxVLXaGM3Ncfubef0WdyhzILHto0wgZ0938MkQK3texf99u4BUWu7518flY/WeA9X2DTkcRyTN5wgAvLXWkmc64L+XZElzwe39FMo+jPF3iJXXEbZqyhhHSJv4SHEt0PQpAMaEQyyGBceYvVd2RtRQQ6u75BuR3nAhUC,iv:14xjxxC0/aZ3oRRYF5oIyZhpr7gUgkeSlVcl9Tz2Y1U=,tag:06eIktOdeOCdSZxdcyEBLw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmK0xBK0E1NnpCbWVGbVdB
            a2Y3bkZwZHRVRlo3RU1WVDl3OVJsOS9vL0ZRCnBwSURnWTM3OU1YV2JUMWEyYVBP
            WXE5K3ZORWFuckFQcjJqTkFKNks1QzAKLS0tIGxJMjRxTGVBVUZZdzZBQnA5ajVS
            bmI1VUNzNmxHV2k1dnhVMFVQSDVMNjAKq3VTCYLFJhsgW2FXlsK9Kkp+Pz7zn5ot
            oLl0VBpP6YW+r87ZqPk4FV7n9d/wCHIiwwumL6Brhztudm429riM7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T20:48:11Z"
    mac: ENC[AES256_GCM,data:wCCR/kAw0aG6X1ucO7brvlV0O5Gtuq2EAo/dcd8ABB2+F639LDmIs0FwKv+GROLUuGcKqCOeH/QqufTQYj2j5rnrAVOs02ZVvdP+cBkIXDjGTFpcSGVzqO/hOl7O9jWXO4umJ9eWuRVbMQAs4GGb1yWiti7m4KK7YWVp1q5TMtA=,iv:EYRsO/ZvD+HAC+XNzYHVpq9jUFDdNe0LTpldS1fOicg=,tag:WcrcIot05YPPIIVNbE3zog==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
