apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:QU/Se+edkC0HdVESzmw0xY5UmFcK5UCMCFjKGJpchTZwd5sF1Pti1uRn9QN4IiGB4uxzgC95+xh8XvROBSTSKvBCw3USWf+BgaAXK/9p3m+Bn0P+Kp6uXvonVHZOeSt0c70mpV0vyK9mpYEgFr+SeT96lMOmuX8mFoPXuDWO5hLBQ7gd4xbExIV4NZ8Y6zZb9hX9qnSFd5l/wQzVdwLGvwYDaSgGMhzLB1xppnSyPcsxF3XxROFSASmasv2nsq5h4DYwewFhmnoisR1QAgwOv7HUuQMc4JI0bcfO2cfuToJ6VbF6zAKx1rOgBm3dm4rcIFP86/53FT0FOQHgSs+2XogQnLCTysukUHIa2P4pieJIFmOAbHldgAkBmCgm/XT7,iv:LBr/RRMXQchsX32GqL/xO5AZHUxYl7cxoM6Mspp0tI0=,tag:vD2PL/6WxaKwlZVKNjRyyw==,type:str]
    identity.pub: ENC[AES256_GCM,data:WJT7zS3DyAvNjW7drwwLfrTROXFGTraMVly2vhDaSqMqFA0LMWN49foKKb73uPHSlF2i3eanawzTxQjBynxC4d8TZBHPjU5wPFJv2/AHIuI2tP0wORbI0fyIQaCwl+oLjCzFZ4KijpOCGuq0n5L+53d+D44P8yBCfiy5Oj6G/19F32E47I2KVhTo0y45eNczvPzusVY+rdYtp62UmSonHMR53T/2wXbccH3grrWQb9RIc9zEVZqfjSMpmfcmyWdrM0fB9UQ20Re6qJVb3g==,iv:/SldJrrqp+7wo+nRYr9qMMRtBLkNU88mh0MGzDPm+TA=,tag:b7vmZxNQfjwziXPLXTD0ng==,type:str]
    known_hosts: ENC[AES256_GCM,data:WE6bX2BUMYDx4yyBEBv9Z0Ro3dOJ5Rz/Ou0mkhHWehl9AoBbGm4sokMll+VcOhiUrJlCkW+wn8XYLF+fryPzdKHJgahO9eOT6v02pFueNa6hys0pLEx7Y1ZIAGU289hTUxEpyVGbitPBZ3XmB07ooOxvZti0a1iLYCFynxZQWlmkZR8BzAhmjOjITLH/NmPMg6YERnwBSxxKSOI8X2DXphCIaxo4+G/SbjWF,iv:XEmlsXPZ7+ruD9YqeKt35ia6lDZHfAz6RegKcsAtfHs=,tag:9xjbOTr++74CuznWuRJhEg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVHVkTFErY2pWRXZTem1W
            RUlRUDdHeG1rNzBTbForRG9aaHFkV0JoVFd3CmZIaEJIdC9CdjEzcHkrUW5kOHdJ
            YkdjMXltdytNZEF0RVhZUnBlNUZadXcKLS0tIFAzZER4eDZZUFUyYjNRU0FMR2xR
            QlozUzdjaXVnSFlXYTZuSnoyWnROUDAK3jXkfK2K1vr7wMXg8ItZt79/+ea3n99p
            mbhXhvncigIq7dAurwYvHhOeVU0L1t4QTGIDgHNBFbgqZNlGj+YYOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T05:18:28Z"
    mac: ENC[AES256_GCM,data:rSRLuJIJ5MfrcXmWLRnhLlCYFM2ouqhuZju3eawJ+wZinYmSmZgLgX1bY0HJP288Fj+6t9vuEa7EGbzwaB4XVEv5K+0dVXDJnGvEBAfEh7nf3At4eo1bFWnwcfqrY92/a7nl6svNy4/kS7AAMof5qHw7i0Gq8EjlZTZVIFNFAjo=,iv:5eAY6zn7dvUhX1rr9mu6FJ1RmDyPducu7rinHWiX4OM=,tag:NVxfXn8uwVLAFsYw9nwhBA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
