apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0e+//pH74a9duECLe3ULw5VENNcapjqwo+Ff3S5x9ANNGlV74kOgG1M08vOd6V5CVxvG3f2R/67xNwL0I1dyS3Psn1Fhe3ePtp0v0nnFhQ6pa+kN9isTEa+ase0naqS9236iYwWfnxFoWxFeqHONaJhXViYBik5I2whEvpYZmCVkU6mwv28eHD1KVkIdVDhphWCLrKPTutP7eK93M2jsiToCcXcW4VU9q2rCxxayZ+jyLIXkxtKh+jPi0JPLmeL+ribOCz2D1n9P8spJhPu5Ob+ueTU6Y8aRZSqR6J1c+xXFnCoRCWQUeSI3nACSDZzLbv0X62guy1BB2v7dm38UH8yVW1lF9c9uzKEFrNpLTcU8X/QXb/fJtYewc/LYHmQY,iv:dYHebWOrHrxG0QE5R9emScT+wcgWLmmTBn1ZG8KYlDw=,tag:cEvF7tiCahOktRL4/2lz1w==,type:str]
    identity.pub: ENC[AES256_GCM,data:K7vJUdDpMzYVsBXz5YQ5E6b26P3rjM/NbwLKU3GSWIP1Feiivp9M+jyc/FDyEw7KzrP0aVPYOv1IbBtrbjFtVGXfGTDahjg/fzEXw30QE8ea1duvQJfhfWVASnEzD2ZcMFfORxilTWDdz9CsfUQs8XCKgzsYFFvaXPxG8YBnScULHXq+fUPh/XxPpHpubduFNYrjZ0EmYuteMAuzxKH84qqwOdhur+LQvVnr1GAZDG+7qDwxncdhvfhzupSUAPWjhxtNauL6cKlYwt1O8A==,iv:+x3zeJJASlgV3ydZcSU9ZCLFIzvuNu+CyK3een+2X5o=,tag:M5UA7LmL1ahFQM3wvGrzPQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:gzMtBb2xoijOJWWnZ+8eOQtv2qikyoLqu51uhDJeyaHsOofpjPjEulVtNjlRkKmVsZIiODvV4vLIdDUynnQJqglEitvYagMgcq6YOOwwr/ISQGxjfvkU3QHzEEjy6wV4ffAuqg2yeRjbcLHbVCsqOF57Vyf+GAz0FKWZeR4tlG5RH5Ff489qtpqCIaCPPolVclm/lCiMt++Jq74i1t+omqTgplDPfLGSQoBg,iv:RK9c03c7cB+2/dyOHBiSgqr8JLmKbvYjMnmXJWAXnLY=,tag:3mBalZYN2naDBaHBBeOYWw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEL1ptZlpoMXg2VitVR2VN
            REwwd0M4WExCR1V6ZzF6aG4rZXY5S0QzVWpRClpHejhkcUl6b1ptZ2Qva29kMGdw
            aWszSE0wMEh6cWloSHA3VVJqWHk0RFkKLS0tIFVRek9GSU9KR09BQ002YVZNSXJZ
            aVpaaTJKaVRXWHhjQkdwTTkyN2pVVzAKjCRIBwGV4VXSUMLOgYvSQKrIxKNn5qHP
            Hd4iRCMqFb0hRVy89kcLJ8STMsjEh4FQypUkMmWRiOFGP3WrKoYagw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T04:04:28Z"
    mac: ENC[AES256_GCM,data:O47bbA4MVg/OXxdeA/S8n4uwqYkl6PkKiKtkzOzwwf3x2gK2jmf9pp8hJCZi9WCtycq3ynYqPscubl00xgXMdzgSY342nRZ6hshC9pBo0DJT5VhQbF2rYa9wZQJwfLG+wrZQ/6ZtDnit8whiy+kR1cO9xEk37is63fBQGyn+Rlo=,iv:eBbavQNWJmSFCDcC5jJ0YMHa53LRa9lGY2Nmy/DLEr0=,tag:f3Q4kIStdP/cgiohfsk9ZQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
