apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:EH58/+qZJX3Ny+8XBRC/dc/nlb5b5ciDhVct7Ko3wygzAkLarOtP/a5W80tJtDzb4K/UCHXskJaBQqDEjki3ClZKzrnJDvwHOlDvw73OF9ZHkygWIj8sBw/kwNBUz7papnNpsPHZoGPi49YU0tCq1FOjv1YmmVV6G/BAzK+y8xfpoEohLR/LkaeBbAbEA2SdeGmsblVxoQ2xiNRTmWa6VQuzEUj347XHTJvkKQ5zFI6cHKAwjL+qrTrNY03j/bUfHlOaGOckoEHAEd/IktjEdn1b3Yn/hhmbkHcbztUNrZxc0b4/c5Ef9fhwIcmR9zwliUejI4l98JEmxunMtJmlIOSvoa46uOigBWlMeZPYGdFbXDaCVtDIa29SUG+dfo+K,iv:xu/OtW/sg8y6vlaQQ7AJV/8PXNrot+aX0FoMDNcacuQ=,tag:MedBKM1XiSBQlmFgcTII/A==,type:str]
    identity.pub: ENC[AES256_GCM,data:ilsHjnPe4KBjuBZrZHptak+eJ6KrxkY3A6UeSdd4d3NkJUC4zCVucajo2dd3j6QHfjXa6nv574ZnvlBjQx22BJ0/ELQb0XW6eCIFy4qJpm9KU4nFQf0puEy62zmo99qxKBYVihi5IgOjqZJLwmIm46OL1vF9Y90H8C1H+xpzgrU/AKtEGsT7eEzFdLcT8JUkqIHr+npH8bXIeFGZnALJOa4lkm5YjnRXD+1HaDuDKE397/w6j9W0QmWbGrijFkg9HkcPvf3QOuUjYhyp8w==,iv:jqm7RVu3eCRISdEAYU3JCRo4y6c0Y+v0tcyshcOn1u4=,tag:gK74B7StjaNSLsnghv95Tg==,type:str]
    known_hosts: ENC[AES256_GCM,data:FK43jzEgHdysSeM/5y0GlO3kQhb7+zKPQmd4XsY3Sba472elFROJdL3vFaQbszX9eTNE5IiS5jPn3RXG1O1oLnohrAv+szfKpf/0AdiTTw/mIPcpXbLlmiMrM0Y8F4g4aKHl0shtjpNBvJaR4nzQLsCDdeeZVrpya0LRbdY2MPJP4K9B4xAfSLjRF38GGQ7hoxsQnpAIYgoXnEp5HIWsbjAor2XuFFfvH9hZ,iv:XTW4dQri3VkkS0i/YIaElNKKw9LTb1pLvkELIuOST+E=,tag:jWKeL55ys3zr5jwLS6mn6w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZ3BxMkdMWTNtbXgzdGhO
            ZHNGR3Fmc25RRGY1V2RWL0Zybkk3SUUyUmdnCmljNnhQd0QwMVk2VTFwTkZhWnNI
            b3BaWU55YWFMSEh2K2JsdG1yenIyL1kKLS0tIHhuMXhGVjBKajhXWDNuZmJZZDRC
            LzZ0N1lkbXR0RUwvYW55TkNWSUxBMmcKE0mHuuJv1BmBc9m/5Kp1UtyFLlKcU9rT
            CSBTnyrwSACi8PjMmji5hlsuf9pkyrkHS87Vh5SOJJpBLHU54m+LIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T13:15:21Z"
    mac: ENC[AES256_GCM,data:qC07pcMOo5cn+9QzdW1o33ec6n9+C1S2MPIeydq2gIKvHjRYNERCO+lKKZ+QNwP8R+DdnQpWjZmJk73U/dlXk6o4w7daxNC2YoWN/EXkPN+uJ6cP0P8gj0RfgJVIYAW8eiAtpHTAoKosHyP2mIE5aSdlKJzKjIDhhRgBchXjrSs=,iv:6LYyELGqwB3YFVjhVu0RRlDGwlW3YZG/mdrrP06BNRE=,tag:USlNyBWdD1/8Q2cJfNuIiw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
