apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0yYHzfuTW+Z+gCKonAsHUffdpGMCJHgLh85Bl6NpZ9fLuZk8ldNn/pYfQPRLD5had8mdgR9GHJ+FNZTXgNRwOzdZN2sj2QOsJW8COBjkWf8oa2h1p1rpPYiC3e528Wd3r2fbjK8xvM64CcdQ4fmjXkqaxrRIbwl1gmwCETjfpmmuTWtcO/p2aqQ0KyhM1O8AFKUO0oSG2iel/cKk/1ELExGN6sa7VOITMjiXNxd/FYgDlW2lAl7SZgBJUFedL9mkX1L0r8MBH4fjr5pT3u0Mn5OQCCDgyLxmmY+wy6NDs/8IaEOD9OzrKbky1Re0B+Ps7Vvxpgtp2ZtJzh647xhdU2XQ1CJ2AkR6Xf/4fF6gAKfiwlzpWco9+fDDLFaROp1U,iv:MjODdWavFeM+6D2pDOHChow8s4iy1lBRIhPKGeDXf3A=,tag:rvjuz/+RMcBs8RLFDKxtjA==,type:str]
    identity.pub: ENC[AES256_GCM,data:P0KGQpHonsBGSbl8xiE3DvmzehDL1jf2rWzhl+r8jGDPH0gfSZW9NtlEX1ckKUBHgsqNoO47ypJVaCWtgum5hddXOhx5zbgyF8kmFSKmWvcxt2y4KxOPtdr2ypqbJz0e+OE13BQ6fZ8NK3hb8MtincXy9bV18hwB/5ZFLyIQmcn2zOioTx2oCBXh/2SPpjQXKBJfRndpTrCTqs+qDfcFZ96JwoUpvoyP3sYI0iU4BDU0DVEQKqruQyu9t7iWYMALsU2g1BlbyBrCFgsGTw==,iv:w+ZD0tuEd8EbCkb2RbdoElTYv1HyAw6r4SqfECGq2KE=,tag:P6CQv92c6yY6Wci0BYJ48A==,type:str]
    known_hosts: ENC[AES256_GCM,data:TBR/cwYplo3ZNPvV/hXRBoS2gQ8bXCjOyxXX3m3xs+eVIxl+P3aer35rOPDZwuqB5TW9as6qJNf8wgKaFrXrVByE8AVPFYRBTn7hJhBuXKzRUhCpNohC3kd/k/AxLW1ZBnwUxYwRrmEle2xotmEN7AgAHQ4eEL09Oc9akc3AMUbt5+xQiVSdOvpgCCE8oo1t/YqsgG/tLEeVcGcmP6dwJ7W7FYaON+ngDZVk,iv:TDA6+J63RUw8Kyrir0iTfmh0HoKAFEeyKdupUwEcsB8=,tag:qIpcrM9xVnwq9YSxGQkaCw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYkhCZWNrb1BmWEd4VWdj
            MnNsSUVGam5QZ2pQU0F1Yks3R29vamd6em5jCnJvMklscUtiZGpOemNybGNzMFUw
            Q2pneXluV2M3MytuNW1JcmlxdUhhZm8KLS0tIENxdTJ5SUQzRlA2aWdqVVZkbVlq
            UkJOeGFCS1VBVVk2QWdkNVNVdEQ3QlUKEAUiilCTZulMDKIDRvPtTdHQf3PkPJs0
            aBwuxIQuVPcJlJbzHju4v+ruzCTJJ7Rioh/C9Ok6oTYbewQ1zsISaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T23:51:10Z"
    mac: ENC[AES256_GCM,data:w22yFY1/kejAN7JItH77PegYUjIXITB6dtmY9aBFUk1/YHxWcfQrHLRBygU1pa3vqSl9pcwDeBODaNfXLM1eZMcfmwuLus/LRRUo56/tLDwBaM7mz0OHIpxqOVwHoXkj0cuBQ7KyY/7NkK91Iy7uwM3KORszuXFyPH7dBhrTZ98=,iv:7fxOpVgq/AYlUylwCiV0KNXUIv8qqoVhAuipdod6uC4=,tag:i05k/0eRTD269qDUlGhiGw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
