apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:GgFnpCANdqL/lMFyrc0vg4gG63i9rq2qyGhwACZ7Ulq7woBf17Eax+7bQvscngkcwrSgxIdMG1mcCcSkXpOCUU4aZqd0fU49J/MkXvRJa0PIvdILfM9lL1f7Bjnar0O8vhuz4vZMpFivJNdKwOJgULASHxoe2uc6o6/7A80vds3rrtV4R6EgT0kwVJuHY3Gg9coSYIxqtKPf5ezsi65SDJs/jWF0Aoc4jsI2nVuXb39bxWfITnyeFh+IcGiTeS4rE/jgwoKXQ3HSdERZ7paxRRseMihqNtXPEQRGAXCf6mli1KYt7P6fF60YpobiPVSVIyd1QMz2NMpL0aGnO7MulgSpQm0w5vJwEExTrtIOOeagfHVul5XspHyU7bgC6DLO,iv:Ebk2spr1A12f0Igky0fpqkZryaVTzUQxAFSotlMeJZM=,tag:1Ob/rja32Gi7FHAQCWq+qQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:G/t0Sj2YANUZyIdL2MFnO/lJoSoOy4RWjNQCz7ZUN9RGeRHrnE60jylCFsvoDV0/moYWgGNx5Xxb4u+xKTPwUB2DB5N64uZUBdOARr5IRV7uvr5GNDQk1HkYXF0j4QiT+u+GU2d3I20ow6gTlbPCWBaJbb39hdojw2LemaCyJw8lqcQR3pBATMjuLlTUBDph5Vfqem7ZybBnKlgafXg116rktjf41nGDtu7e5mUIBihhyGwdnDuVXUBjepHesLgA5ZyqHnAsY1LSVMH9ag==,iv:4LkIVl4Do+PejDFIzvoJYImDs+P6H+lnoSrrdSsfD3s=,tag:ybyHThJ7RJ4pbGvZ1YfP3Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:9dnhKgOsbhzAkpMM1yKzzCEEqrKa0WVbrqxDj3dimUYMtyUfg9vwCeGGthC94cjKv5k7cCXk52f7gwLdZdZ9leyd8tN/R6DN49H/TXyijXf8fSKVaIZds3moMdaMmGZnMavaMyEHcyA2QxyCNWhKCxGIqFR8iw9Fphr92gy9lwcoTNI/uY7Kf1/YUjB+hfi7LYOSqFuLMDjAceGA+Wv5GrJWRVBycq7Xs9PV,iv:mYzNQytFbUM0aQE3WYT8lhAPoJjADTmbqmpkfEQsDaE=,tag:bd2YmUrrlzbueDqY3nFGmQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OTNBQnUyS0tuODlVaDAz
            T2xmSUdxV3lVb2VBRVdJelorQ0Z0cm53WVZrCkxNNE96TW1JVFFjcHRGT2ExYnRO
            eU9jY3JBT2pObmJsQzMxOGlOb3pNNUkKLS0tIEpHdWQvbG5BZjZ6U3E4aS9xa2tX
            dSttbkxaN0ltSnBpQTNKTC9qVThLcjQK3Gvb+dlHRKZGmCE4IIU7b+o6XGpqh9q8
            enHth+4JgDP7xd3tLtd6j+4t8qx4jsp/jabw1wWTAjBt+legV5br8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T03:42:00Z"
    mac: ENC[AES256_GCM,data:XkYOhXjFOrat7Jx9LbYnkOyTLIpH4frHvPmPSwfHCH2OQwgX2574x1pBzf8vwaj9g3govt4yhNMxLrR2YXyCsaQ4YV1Yuyt6GGVLyerHoC0xaY3Cm+QTAovUQq7r9Af92iVSawDKrS/qs1w5c/xqcYEQcp4MDb+lzzQQCNYmYPA=,iv:iXDW+rlaIC0aWyZW98yQ4+BNYyt9d8fiwstBwgLRO7k=,tag:6F4pXpKFaGVk9VCl4H9Z2g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
