apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:7IEBocKOs5v5WUssNkjCnF6+9PBHEbCE2KbvIDSyv2u+7cXs/33yVXO3VbOC5sad+knOi+BCtr81cQw+VoY3crBE0Ti0r9119ljVMJnYLjeOKt8H36fWI00jl0+1rKB+d4SiiFBOr4RIe3GTw1MCgWJsWvAJhGpxIpEzzto9Do6NrTTS78rklIr5SbRWCDC900UN6zy0VVPHQa/ysmoqaU8pTENtvenHGeBDqegJJYbu5OfIMcvPPRIGO0/1DMykjsQvXIhOHgRIrOYZ0qFk1dBOJ1ksIIeJz5+AXxTsk44kGcGA1ZGyAGKqWNd1R72GHqnN/uwdygcUojIeFBoJq6UuRZMlvnZsZt0IP5lz+fJ4q999WDa0v/uOIr3lnalE,iv:Njl8nk1GHHvHNR7SqzhtpxM5ypv/PPJvGeS+bI449GA=,tag:WZ9bsaclHNqJthFgix/p4w==,type:str]
    identity.pub: ENC[AES256_GCM,data:I9p+wHUonAAI/YHESz3wbEDigRrePopBThLqwiVb0hc+9Q2BvE9yYgT9P48486LMxAIJXpU8zis1yvc4qZTVCsRhO/Wivyu38+4+gw5IbeYSy6wmmryA/U52BohhhWMnlAsFRHtsi+CDAr/kJqPD5b8uU6NOW3WBQUxMr3Y/4uw/GU4wGYSx7CGPJhkPluTQrU7uxZr/gSE1ME57rpOAZXAmUwTih+fJPrjHjZW9GKAlwWcdNujeapvI+5wY0AZyRWPELSIiAllNzDiPcg==,iv:uOYI8FCgcqHClP3fdcfWBHVhlrP5F3shuBzE1IXl0aU=,tag:8tXJsmO8MpP8aKeFSNkItQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:2+C7u7MKfc/QKmjBtJ+KYAlUcJds7n3MlO63mZ1RHo+A4pruPgwXP1ZFWyN1nPmr1sZc/fKPwFBnC//lDCiDnhh+pxOJs/gVwXLqV0rf21HfTomRQ8Nu5jATHHw3rHA5BZBYvWIjJHPThkuVO5i72lyt6UmTke+RJ98ypTpq5DjqYLQUFoOBqdvu8gXTf5G8WzTSKjqqIy4acBLiTbfNtNakQQUKbILE9wMC,iv:n9GJWlYj9HKhLfo+PuWZqefu0JIyV80cgOgTweOtK6o=,tag:e4RiXHwqYpz6XMddQFm14g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHL2RQNEhIYjc2WWNXaVJT
            TTJLVGhOQmlIL0MxWC91VGt4aEJJSUtLV0FNClhxUzYwb3RrWFRENUhoYzd0NkVm
            SDc1VXBNN3JlY2dhY2crdDZ1TzJXR1kKLS0tIDBTQkZDVVBXYUhheVAwWVF1VS9s
            MHY5bFRWcmhJbFBkZEcrTXV2Qys3elUKuirV1AqKu12EPJYPXaGcD6MqkSLHBdf8
            mwgUhE3NrLVFpJiGwTlfPSo398pEn1quyQfuHF0ExdZtUDYarF5gxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T16:08:29Z"
    mac: ENC[AES256_GCM,data:rwUhE5ET27wrPtS937SmDoOLU0ct7ViAxJWEm1MAWQmIJSym3AUfgM2k0OmCTdXbVJhzyjQQmqQAi6vu89/Yl2BhEg6UzNG0hz9y7wDvrJEsMVpYnCpubs2II0mAomaWG82K+sbeQOdSAxSIJCTeNVSGfrseXov4owNyK7w7rbA=,iv:WtF8fVJkVPWp9fWm4YBSNodK9dyi4R/Um6NtHPupa5E=,tag:KZd7uQZASotWvuOLLTsLjg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
