apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5w3LYVhdic5GmNnLP8xPUVKgyA52yazLWDdVDkc+/iKApFjFhCxMgTQf+meOystZL27mGK71hLgjtt3TGe+uWUmKMEau7kuMn4eljyj1A3S8qf3LacALGUBlIebfwC9KylV1ZOguS1I2bGUE2KH3Q32fXYTeBGcAdYHGcPxrz/mFOxhLXvgAP/yiyCYBxw3kNZITCdynI7J8lD2QTIbnXn0fRgKglqsrAGNOW4MDtlj0Pl+B+hM8M+UU0RITjzJZ90gTw2rtpNCX7xBHDIzTkuhysHtyImjx+lzC37HZz2sPyHx/dSX3nSQVPEMoHXnhcII3OMYJd8WBONvC3ifkMfpF7FIY2i76YEhRzhcHim/NFM+oNbA4mxsrHnJ8v3w+,iv:Enm66lRwO3Vt03oqp4/OpSEE/+Fl53OQv6Zx9oDtloE=,tag:40FXI001MBZSWz3+LkDxVw==,type:str]
    identity.pub: ENC[AES256_GCM,data:PF2CwpSO5VeXbsfK6/TZhrbm4w8XlBu59jwwkVvENoqF9GwdVnH5lHUVhLeQdnHVVsHCQYAXLPKlOPe4rXMJxlNkxju5opHGnMdF2S+P3xcTzM5mjei2ZBqTYW+6D79uM2yhAoK9IwQqz3xR96wHHuikV6W1FsEpAdYr5KyWiSI/cSfSlVjFswL6S0cjfP+Qacoq2OUbxxL/7e3ZOK1s73vzWIfWwktjxR/Zvu0nMJ/az+6imghkG+CPqByIAQAzknHV0eMpFs7eAnAFrw==,iv:+9R6AIzZFEbxCzzniiJviwdTp6EAoMzOyEqKRcdGveY=,tag:27y77GdGfGtLShQ/63Ur/w==,type:str]
    known_hosts: ENC[AES256_GCM,data:Qj+V6WP3VOTFvzzudetTuiMF4PPRkzebNv9a0mKP2xjflW8gwxOilVOP0XZ4geLr7lfMUJqKH8K1PlqXZuIiCMvyD8kOfJltjPPFPWT3CuYaONuux1opcqI4UazO4RXawd94XwCaFE4sSgbBFxv6nwslmSckX6VAg9/tmdXYx5ZGKFKn8+nsE5FjYzsldL5/ml1IeLpJoBV5RRb901QhYEekKWEdIGqvbN8w,iv:ukxRsNHhj4AM/glXyrJtUgYoNFnDq3xlwJsDFbwqCSk=,tag:piV47FIlKsyuqO50/fbu6A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaCtLTEhndHg3UU9XRTdl
            QlNkUHppV3l0YWprczRsSXd4MHpiVlRTT1gwClNDcjllWVhXMStycW9waW4vSTZl
            T0FvUllGd0NyRktQVmUvUGs2RURGelUKLS0tIHRIUnNaM2lrVnZrV0pJYVBVcWFN
            Z3N2VWJndDZXaDh6ZFVsTXhzYVBVVlkKteaSLw3jex1XunqdR9BAQ+/s/mCa9uDH
            XJ8tKmNPdmRCy8InEBa7cG6qDPEiyR9yk9U+++PH1rda3eHW8kASXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T19:12:37Z"
    mac: ENC[AES256_GCM,data:COzRtPmmSsmzcnXCuP3ek0Wgd27yuC5Thwmh/szJyp8ZY/f8BSq6VZCwgjnytqUcJVmedRP5iuemgXF8cGPJyJG+jH78VE5dcDlkCKutRq/MgS2z43bt9Zp6GjMELmekSgaTocJzta0JpVHJ/uElWF8YvZcsrWnJ3rulzJ9icNQ=,iv:dJIz7PLeLBwmHdPrU4C4g5ohfuWmB7x20qmU6NlPCM4=,tag:HJfrzfnhQdfenYkcwyHYgw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
