apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/tlIwew/bi8K2eS3F2qvm9NMlZgwpsITnz5ZYA/vVc1uGZ4zQ1KOP4O/lcEsAlPlOSBnmQuqLM9EMJ2q2KHxIc5FklLLJiYDD449mD2G6E5QdHQ1LoDdL+cRwxSMF7MnpR5wmxjzZNYbwLV1j/Jaro4OaBNtp7oeVeBcZHh3XQLzAnDHdNtZLCftSznGUonwAlZlZyNpniCaoaBcuDxg22dp4IJp66oYDn/+aEc+Ttq+06+UmIR+2u+8zzsYefIfxt+Vu9ObsLvdAXbhEht1ySRLLHWILYekFq8D3lG1Rt0xN4xkD+Jrv0sfmIXsTgSXyBgpB9EC0cu6nkOHfN1CqF3s7p1DargQu9I0hZNkz6I72rCr3mPfAzfOdSPmKweJ,iv:Jnwr6/IbPzYHCIFEqluZKnng0WiSabxRi1HtVMCQmt0=,tag:g7k5NXPnKujwDTe9uTkOiQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:nEO6L/W1uBSa6jMyxaYcgXF8D6FlF1zleZzbZm86BAK3Czbvx0FzYfZ6AMFFvrSexEBnVj49qrEJqGcfeS3G1WvQaCxKh+dtH4ZgQYP31F5xObz2EnAXlTrCvMZTtinHKnj8irl1YAuZKCa9hGyTOUzRWVi41VoDvN9RyDfTkRa83xHpEl7LKGb5ofM5Szkn5gcKps+Spwb0ufZ0zGY9uvtWD4cIwL2WqmZoI5QrkK5thNh9S5p4pWFEpKdcbNzKtU4nnpTqonODyybA/g==,iv:NxR48E+jR07Zeafi9uQMnd4L+y+uSj4mNYihkJqZR70=,tag:BNBc/PPNjOVCqioCBmcoCA==,type:str]
    known_hosts: ENC[AES256_GCM,data:FkrBBkg5B8xbBnnF90Bi1QzE9B7PmDr5OcN6oT5gGG5z8kcs6YuSxAGlaIYD/6G85dGNrUh9p6ZVAmZJrnqxyYSDQX+YSp+jVXECEIo1w0jFSyBtPY0N+s0Vs1zM7iy6pjkmbWMzplkL4BJcnECUITd/1GEAvjXdLZzLYnV81pc7/ANY93P91//I8HkPQuh3DICAfgSE3YF41PjbN6Ldqq8SAu25jEGhPwlR,iv:mSZe+ePektFRbJiS3GbcYJzJUW8vTl9N+FznNvN3WiQ=,tag:/jNRFUDuKKblPpIIhtemuQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dVF1WTRWdkVJdm1KZTlu
            TkhQVXYwUVU3NDliNGdQN2NoQWJOWEJ2YkhzCmIvVWxvNW9tbml6d3RPdlNQTEw1
            UTVtQ3ZKU0h1Z2xDY1hzdmYvS2FPS1kKLS0tIGZrWHVxc2lDNVYwOTBMUkZuaDBU
            VG51cnlGVXhyOFkvaWw4Zzc3VkduVzgKz5ihaSjnEgUVp+CirDo1QzXah/0zFvfS
            3X4uiuZWxtdYyAttH/AyCNaT+rUOAicC8bMr77dDhcWTpQQUTT3yOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T18:39:20Z"
    mac: ENC[AES256_GCM,data:pLGpoxUu1aESIHfrKsORbzhtukHdcv//hvKtr/TInC7xIh6u3iWp5NwKykXlvz9rjsK4TXsKvN1MlHZcbZtb4ou8gx1Uu8DFtlX/6CwCW0g96qOi6ICX3HzzbsBsC4krwvLQJ4n6T99Pa/RkIG7RQGoiWBV4NwFUYzLSwviboBw=,iv:6ZpuOvv23MWdY9KWTTtK0yJAIo28MFwM+6TarvhbWq8=,tag:dAWM7JHo5KqXFJa3uxJMrQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
