apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:mFp7aL+5UeuwODiIdK/TzB2KRha2N1N6MXjlwLctk0s17aB48rbyY62PEsIMQmD+wn4u1Vt3biB4Pd4Vb4+vB94G6nG/wtZYUbPUx4LgQxL6X3DZt2YKkMsxgVlo/mUYcVbj+kLV4hDjZCb445mOZLJ1Q1i55uQXdlDwcDx34vr4a2J8eNwF7XdtZ4ZN4bvsT4FT/qQCK51WS1kT8f+lyalBaq8VN6lPmUKEsWh9WkGIGPYkx1Z6jItv/vLaqfkDl3/MqdBnf9FgjQv8tjcmRaeoJu+56Ap54yfboipn+lqKaaPc3cgKZl5J1R0jzPyfWs28wdMRbjipXT2doa18YvI00Zzh3Hl1FRqoxcofIoCBdROF/IKjHK6gQdVbg9XU,iv:3tCSTSfFZpe7NhnF8MNVVZBXthJbo3fQ0CMKh8ip5tU=,tag:m+TtEqBujtw2JosVFIM83Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:G8/35GbNUYw7h4rZpQRKZRBO5rJh+AqY9v355BckJ7dD9WegmJguKqJXGpIogW74xG0YyBzrCdJZ16I/aSFJK1SVzB1XepMMA9nDoH9f7N0RHJKjS4YGS/dFCRzrpEBAZCMEIOYVBWIX6yaYvpjA2J/XzCyQRLCedmGuHsMkwY3Udzxf+YPB48sk735W2IfhUv0CokKU14UOSO75queoG2nHwj5/TaID3TkacqKIMov2CKF8utueYmM3Vhzk3yzU5scL4qmiRUNEshokWw==,iv:yq05VvSifIT+zTxNlwkWJ6f+oI4lPtIGuYogMD3b9Ts=,tag:og2EV4qVb5/spwqZ2GHOYA==,type:str]
    known_hosts: ENC[AES256_GCM,data:yRh4pDQTEGtTwdAohZFUfQW/uuxo5Q0BhFC2v6/iJe2G1s73LXnRUOZxThV0XXDW0ipG8iHJ+lJCxHh0v11qdFfFp57KjXaiZa+nTNanyn2gJAB9Qw+y/LeT55Fxz8VgXyZMvCJTkEtT6+n3bKaLPiXQOPX2ieXObRMcULpoG2DX4by20AvIoeUXQts4AOW44Zob8lL2szD7Q5UY2f/kodx36DPP4e/tLh5Q,iv:seoYg+lrXAgmRHOJ9XtOqvuXlJIpwDGYrdxansWUuPg=,tag:e7QQ8f/UnNtP+1V2HJ93uA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeXNaR2xnUU1BdGhkY3du
            VU9ERFVPYWxpQVIyQU9Eelc5ZDBtVk5oKzFVCnVFd2lmUnoxeGJmM0ZjbXhMZTVn
            eWFyU1h1Zi9seEltSFpPaUFPM1UxaHcKLS0tIDdlUmo4aVNmQU5ab2VOOU5FRnZC
            OGRIRmQxV3V2UkRaNFF0TlRWVnFJa3cKjwDOnz2wK6vK1CAAbbm/Z6uDykJsXx/X
            3Bg4yYoC59uBezu9QJELwJrwoYtkWq2MvHlfpvzaVxbjw3/c8mwYsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T19:48:07Z"
    mac: ENC[AES256_GCM,data:0ejvRYYGNtyOpf1/hlTGGMW+kZnW/jQ1nnEMSi0jHQpMlk+H5JCMJbYtUP60ih0rDvYaeYr6w45iLuP2OBoTNVF40wcKxIS537JI5iFVXjIf/c0fxQYCSCpyJAw+9BiZ1pQ2L0k0cWKXJFQ7WUG2EkCfRCQxAhAbMItBBVFXJQM=,iv:8oj5NnpiG4Kw2Gaf93/O0BB0syM6h5oBrh9SkXENTY4=,tag:Y0ZIuJZhCvb989PT+H1PUQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
