apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:s5qohXkg+JW0fNOmIGabWYiw367utw2SoQkGS59MDj6OkVOh0mpPAdUolQsqBByEUx7Dy/WxOc2Qry7YS51G91FFyA5nEdKXREOey45L9hDAlA/JDOadTyQ+HOkuz9ImTtAU0k/5y0UXDVHRmyO9W4/ON+JTCq2Y0+Qt3wjZ5Yk89b7/zHnTL9dYiwBm6u+rcp8qwb0yb/cFKF/v8GkjWvIYGmUJHOe5T9KVTbFi3Yu5a+arXZ8tqCNjby7aLpyuqDfeNSv1QWob4hdBRM7zxfK7ftguq+eZTEFYuL8zPiQmrxiuFQ/zZ0Nn6xBPs9u7B3xB91epYKGg/Ok7TzsqDpncnv/gHXut4UB2/DaizdETLdcDsJFxvNPuoK4z6fJW,iv:iPNMw2zhs2uYJadxRPMtRVmFlEus67BqHpnXgBFjXqE=,tag:luZxST056T0VKcJ7DtYNXw==,type:str]
    identity.pub: ENC[AES256_GCM,data:AHrmR6PVcFvQLCoO9WMYWBtc1exvy88vwf+VQa07+vTdscaNJIjBE9lmqSW8opjgo8uTlWvLXeSeLKwyAAh+sEoynROdS0pSXohDv/ZcKbuFU/NisdbfLQvXRUhh3qWjJ9NMgtow78UF/OyyQCIhTuOwyyPHrSr4BJo/LpxfvV9Tp0ZyPlMdCjRBsiM9fgcq++9ob4tqN+q4jJoCsqRaUJvGEcZoMJzzJJU8Q1qzty7SfqhBQgBhrYR/iKtxbOWhmmmTkVz5o+l4VIHxTw==,iv:bFrKHaTrV6mD17IDkYtcTNp9QC6/LcPjIIowB6x8Dno=,tag:lABM9+yi+DTtBIpo1mItQA==,type:str]
    known_hosts: ENC[AES256_GCM,data:CbGVjJEtt3CYycNR8DSROr1UaLnHw3QijixC7N6EmSklEjv1ydCnOn+ViY6Z02HhOKTLjMn7FmA/tuCxXjTs2Yc0hXw/yfdUJj7/GqTk1yzBoq5cQ6tpERwORaqbOYnu0cy/a1UFUEcIRO8k5ou8EDihoWcHFUG9Vsze28bRa1vql7TBuEZKyIotPssFc0q2qkTPfcquCFvdG9cmsdCSwKMExtLlR2M2g/ui,iv:yi9uJ+ldumx3KiSeMAi/MXyKmj+sdOB4oVxo4gAG/RY=,tag:zJciu/sESN2v7BLmXm1wqg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxaGcrZ3JjZTRDK3crMVNE
            L2hmWmlySHFqVlRMbnRkRDUzUEhjZklmNUFjCjdUTWV6dXppRlFFWHJEL1BaZitU
            TmVmejhsOHI0bGZEM1haRmJTM3hTMGMKLS0tIFhZb1d4MjExRUVVSEFmMGxoV2x2
            alNlZEVNNlFHSVl2am85THFyL0puamsKmt4/wK3ozOJ/Aa5QP6TpJoKVUCSw7lgV
            YiiLzR/GfrSBruTLgjDBuGm8IauVUWTqSFVZvxgRu4akUqZdM349zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T01:11:58Z"
    mac: ENC[AES256_GCM,data:6z+SzSqW2qeZQcRQmlXyLkjPGDe6MlyJQKr70KABEK/+fGyV/jlEsjipeMun1vvqI/SQZdNRrJjMJsTVGYI/b4Be8HKf/ugLi+5E7k+79lKjyNVeWluHZiSsDe4G8UxH73jqK6kJCPdpjsDrZaTtBBmPhujAKohMVuv2nYF7RVI=,iv:j4+1Hj1TcLnOj9JaDgJwiZLPa9+IkR6An46dL47ZxGw=,tag:9QFatzVFJ8HJ0wqI1IGZAg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
