apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:TaiCgvzZDJ07oSgFhk9BQT5EkliUC/4fZyEUs5bJ0X7HtBOevROaf4YYGi7mhO79R88R4S7lUJpMIFh6O6i7eSH2dPOjbddzvrYtoBXt1zOw36nKslqLBMldeP1peQDMPOllrYUZpsP4jH3s387QZMHRordPXGx2isONcVqKcy2BH7L+M20RvmvgKHWIOGhtINpniBijziMrgR652SIH9U9wNrNnJRlo+Z6mIRbceDf2qHLIf5c/CkwsDQcizQDNL5IiMxtSbWx3uLqr9+RTeiXk/p0zJLKg2FUIXqhJ8kygU2QMky7EshbuWoMr2jgHBXEOMyoxgV3AZ4rVBtuvfXKWZUkZs77/Yqm6GvjtjzhDqjnFI57jw7x+wax6qEsr,iv:d+d20rcy1lhE8Jy7qJ+JJYjRwAcbUU0bRoZBj3VKhZ0=,tag:C/2/xq+rASZUJui6KAcHtw==,type:str]
    identity.pub: ENC[AES256_GCM,data:qkkmXk0sSWwcExFMg/va0xZEHhzUawyAVlQmaiuw7bnkzUyHQnq8imfw6ceUUrAC6uWe2lmIWSerWl9nYXN7lvtlvi7qqJM7+pdq7nvGcUIkEjDaiilOFNt2A+fHNHFWXkWvhdt0gKInInhmYbyIDRatkJPLgk3L7O4T7JkvqsqsND7F1sCG9ht9nUaS/tXiSOaDCkgpAtNTLYJwIgnaZ/yAoLXAbA6K97eYJTnW32spjaXR/ycDKskIyJsN9/ny5/g/tBPLsq9f0OuDYg==,iv:4aJH0W3GjuIXS2zQKNx/umxCE8RUVSWmZOIceH3Rhck=,tag:Wkuj5gxJ3mGfQTci0dwBfw==,type:str]
    known_hosts: ENC[AES256_GCM,data:PPRemRX+A6rrGqwe7i0egQJWMr+Sf9iS5DTZG6TdILZUJ1Gf48tQvEku1cq7Gjg6DP4114hV5c/Y6xN6v40zBTX2B3s5MCnyZFdm+DD+l4I/6Hk1d+1hRLkYUwdiI6nvvmHgyMLo3VUdUXsmWEqu86mDguw78Z42sXlrw0f16yZjM4TYqwf4hsUW0r/2Y1vAn86WnYd2XfMzLB6u2gcsLl+1QZ78GOkwOayJ,iv:trbzbTwDdkL/hp35h5JdZVhTP3RMVChc3yGb+64rUew=,tag:YgFfIymy+H1vFYYCbqBSaw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQN1Y3WUFPTTRhSVhmdk43
            V2JJQU1xZElRd0drZXFiMFRDdXd0dG9OQjFjCmRnS2JIS211c21QV0RFVkNxNTFk
            bWI1UlB2TmtnUkpySm9IY3VocUJMc2MKLS0tIDFxY2NwT0FPamd6bm9HSzFnL3Iy
            WitsUlM1bWxhU3lVTDN3b3dxWHV3dVEKP6eHtVKF3hCidRSvMwAZR2o0kmBacAUb
            RmhHvJm0r/qozxMeysP1pJhhycmzzpLjlddlFg1Hns+BOFWAbwX+Ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T21:37:21Z"
    mac: ENC[AES256_GCM,data:6xcWkglfVvzD2cCpivF0UrLZ20SYQqkI7M7z+4ugkRZBIEvnN8YxPrCAKeiRYjJkE5fDOF3ej6l+ZtigeiqN9eN7BlFsGUgBx6B92OEkufA6+BUZ/swXKqbhoWI7lvY6JudZK5LXmWvmH1LDbcTIPzuMXIujcsqxdGQWgneRWUk=,iv:wRefLJC7goYdEdsjq+7OU9zIKAslI9p977GViiNFNhw=,tag:jQk6gF9lPVlsybRxXU8CQg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
