apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9KkQduZWMs2OwFVVmcTQJdewX+6BdWEzVZ3me4FGG0Iu/ni/+xqLcgYC5ROr9u/hs0p+hwpNzsLGiYeHwZJmAQdlmNdF8BJGDn7IYDBCcIRVzUcxM6kyf3rK5ZMKkI6VOisWseb80W/xCPFv7bGV9atOKieMj/JQPyZMzWElh1UlZmWo1MN4ewOl1kNqkRZsLpe5rntSNDdRpYcfOgglanx68KEjZLp7blwtLTIup0i041e1DWJA6PNUzKASkz5SiNgsnGTxhvKaFGVw7iFE1vJyI5VhykTOfQk5OFnDgDmq32tLpXyWKlPo+Maf9CCDwZCepQI380eLGL+Y/wJdKYWMeRzz6EYXL48n8bCrGc1LGjDHGDWEp78OpLue32E1,iv:4A4acu6XBt+Tv9bb2vdxo2gZeZyVL5FPW4R32bp8k4s=,tag:YoI6QypbV+Fg6ZxCigLSIg==,type:str]
    identity.pub: ENC[AES256_GCM,data:4qFhJ5g+8sxrcEl8jZ0tGIBdZUUs+J/1LJ32diDKfaaavZU+omZ/rSBTAAplkj2tUOYnMip/lXu2FzshUynje1r/Ctar1ICvaCc13mqauOu9yB9n1+beJ9DHLR4XtdcmEZcIjq5C/IVdmu2+VkG268xSCphKCm0tia4JReg4k2RjkOltgdLRO027QfGo3U56kCAHs1z0bGExOIYwfVfqKJWx7ajbguuyp9FIN6UyrUSDmlqxVh1FXTeeBgozHj07OmMqskQDytPC5Eihrg==,iv:OUGN84aq6hUhT8EQK3Ooz66cPPKnG3upze6GllU0iF8=,tag:VJ/TLGgUvIcfPmry3TohVQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:2l6E1s/VRIoVtQWSGgqIADdmzMu6YE/8PFNATDhkdBdLWAqTjCIyJCj1bgbcyQSiiKaqV2Zfrjc7cTc5LeTIaF7PII5lyykLge+XceLQh7eFG0VNws2vplWZQteL2cQAfsKXl2QAS/9sYusA8svqbQgiBZbAUDjJaLJSypcq2X1+dcjkj7pLuonFul/XZb6jTQsEHukQ9eEokW5cJ3/6cSmlQJ9Zj1K3d8nU,iv:pDDhq/lfjKKUDBE+Hg4L/PzmEKYNQ/EkV1pW1tmN4eQ=,tag:K91yCrKUW06PnCty3c9JSw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NkQxYVRxamY2Z3hFaVZT
            bDlpMmVNRFR1dGxHcnltSkd6bGVZamxlUGdzCmtzdFdMQ2pweHB3K0tDYTVCVWdj
            NGV6YXdRWURHZ2hEYVNnQnJ4YmNJd3cKLS0tIEF4eDdqRzBPRW9qRVQ4bWdWa21n
            MDlydEJLY01XejYwdXZiK2c0ZzRQeUkKCkickuYNCtUv0bNVKkNLyRtWIXRRdv78
            XUZ+VQwtFLAZ+1w5m6yLH8i9CdwhTZGsrDbt4CuOJ34L0g26F6BDzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T18:52:13Z"
    mac: ENC[AES256_GCM,data:+yUSgkUYcaUgOtm7aDeyxjqctMI0qavupBMhipb5U47jPWC+B2mUId7bj/+0+BsDg5QjkB3Gw52YUHaTHDJjfmbzVA08DX8Rb5q7HCxR7PGMoZ0IeFe+f1Ja4XGx07qrRi9pBX8xDJVdxC41Unokzkf1T1No5/ne78dJFR4z70c=,iv:tNQxuv0RBxjklUBhXuF3Vo2SmhDlHvYn518UDHvddKE=,tag:A2qIwKBkpovkZhAiSFsqsw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
