apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:b/NjSSQx9JueW09F4hXiFKtmq6lFuMTaVQJJluypEhX0ut2vMSfrFkL0EqbwNDe5UgBfGJRnMwDEhbF6YX6AYFTbSka2cHKq6zL96CWYp48OOYOYCMwshUiC8+w8Za88cFDV4hLaaKTOThZTerO3NJ+VVbrzenBggYXRQndq3zftk7lxD0Qw7kHBtPiIaO+DUf1LreJ987aexE7799iQF0FpXBpFM4Bp9+WCknnrTE1ioxLXKnw5Tpl0Q28iX6S7iAFHX31s90byClzjlrOLI0vTMYwQIWLd14HwgHZUv1IqYJYlwxThK3zHAd10UiMWHSz88uVwGxQTMdTzhMhQibpty/a9DyAJp//WpTgao8xPAx+6J9LbeT2IsuHBbWwP,iv:kW/0h4VppUc8luFqbPcm860FtpkWktuHtGlvLIVr/CQ=,tag:8zaKLlPvF0Ej/u3piLvnkQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:1SfFFsGSFHiPPgphWd97KQE3/PWzuOsJ7YUhtQGUW5Qar0cLuyP2DtOv89laZyeOp2V4sYtgRLceNWBO5mJwXzQQcYQx4MwyG1kxV/IrQQPahsiLxKY3TeHgt2/CFjyfjqXtIqI74wrFDEw7eV3A8Vb2VnuRfHlC2PxlPj3GOgXmkTGhXElqGUXUDlRr0aYPDhOdsDFuSfSNsV8As2zdZSi4uYfK0Y1GbwP0mwHWaeaYOmyDIuE9U0aHspP8v+4TMwaRDcLBYRxOxg4J4Q==,iv:iBFX5jH65yroMz6RzUxphRE/Ixo7BorAKSSMaMpn6MM=,tag:PgHx8w2eS4o9PbajJzr8rQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:VR8hn36wYDpuYDfruvIbjU6oP3uz+kiKvQ7WXJHv6UnaR5UkNmAxQn6gDaJi2wg2xRb9LI5hOZHPI9W8OBZuJ8XV5vKcIun0kNmv+60Qgpb4+xNdLyKtC/crKwIlTl47xKrGrERbfiscIDpHRF9vrVEgeh2PNMzCNxNvV1gGarNsWVoCbokXA8PcxpAUWhn6kEmSl96Tj2o+mG8+mSwWW0kLXEMy7A2ZHyZP,iv:Sn5c/cl/WfHbPiJRD5dI0tFNtt2Yd4CWQ5Nrr528X3s=,tag:+eyhaV2ObvEXKvCQbpvARw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZGZYWWtWV1RRanpkT056
            V1ZtS2MwU3MyVGczWWpselExWGJzdnZrMWhJCmsyT253ZmhCQWd1ZVRvUEljdTBB
            Q1B4c0tidEtpVkNUV3dha1RNbmdPRGcKLS0tIGs4dWxqYnkzRE1wdlduMjF0VEg5
            R2VuM2hVZk9keElNQ3NadCtsam54dkEKSrGXllQ07stmTqRT+JfdwnVCzNZNL7xV
            r8Aoj9um33oK6hR99uXgXVQI5t/eYjddZ+h7EqUzllCDujgw/CP15Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T21:40:45Z"
    mac: ENC[AES256_GCM,data:mYbFDJ8abByiR/WZHMS7jdqegierZSsD8i60//STME4eZWvpnvsXUhw9GRBT1J0WFa5nahdyACUn8wru4Wfu5u0O27D/kTW1Tomm8L8Gl9ZyEpP/XCqL2K7muWQJyu3M3LJiyj5TNA2byHHpBiy7KC8+ZFJ84uQxpTHHWk0IT48=,iv:Fg4T2Er+nl7YYhd6IfbNyJvFKMHcn3s8sCZixd/rs/E=,tag:SlGLfNw9AGKT+e7TbPP9vA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
