apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:3Tjd/kNe0T2E9p7nohXwETh15SbbO26RAHr8bl3e+oOYfVR6YMVahqtvluUUmT/IjwmDInbFBFLJmtchbslUTF5QYkggBr0pPmlQ3Gii0NQBAFgtG6mZZ3lBJClSe/UJJCdEKcrlx4rT8k4OxIOtOSZFEnKDHQs+yEkD3SsSUWVRPEpUG5gdxwWlFPexkJEnv8i8hXloDE92NwVR38LCc+L5oOKsvGAqdwxIDOPsnC51r4ZzaDZ9NY+pYR9dOcTndlbUQgWZGd3vdtxmwF9JaSNRk0CBSB823IyhB1FBYUaXBmgk+YzuGvc01lzAuKqD+31BF+2ztfP7xQDkgMHEKLMT0F7aiWDX2fDgi6tcd9CKCGUo5zX67+0eDm/lZPWH,iv:E2zkx035rJA2r67301zVaVhsMZqrRGxCBWiGmDtuZfs=,tag:EuVC1EX1heRJirg7VYX4rw==,type:str]
    identity.pub: ENC[AES256_GCM,data:vNHnCexR74gnaokiuj8jLSuD9znuzDqZXY2aCQz4TNvb7Y6ehzm2bQ6qoiYm1yj8xwgPYs4NpmXWE9IzTg1P1Y0nyZOr8/Gb8a+TMlsbptyzxL7/Jg+KwbwmavMxz2y6t5kqFayiIdp0R0Naf6QHyaZnyFM7RuAeBoyJWtZnPIpVgrrIPEFMcHts/ylDmb1UD8MwUBZThVmzdATkaJO/nVb3p4wIGKoVtEgo0eqfXRv/pSA5Xh58cq3YjkHvU8pbjLKqVP3lmyTRyZx2lA==,iv:cNuehTN68atR466Y3VgdTLi94gqL0fdVgpyMyxxPD98=,tag:cP242axfyQLbQ9MY5hBRHw==,type:str]
    known_hosts: ENC[AES256_GCM,data:18tSr1BTz7waLkeWBxOkVCMG/m3faurYoLTKG3sZXzIGq6nrBu4iCcNYLWaOL6LJcUOTTRaktDZs1jcpetfTUqqEt0OjO6Uvjy2/41Ffa7ciykEf/9hNzRH4R5Fo8DiFW95MeT3dKFz9qHBEPdD/QIO5DyqNAVZ6exu4SXoArat9oMWJ6zSM39F62+2YYAc7StIeCcLs37ejK8pVmeaa+A1aSuik/2Cuuk3j,iv:RZRZTrxYSXtaXcpzE90P8lRsAl4+mFX7Q1rLCrDdONY=,tag:RiBWsawzz5M8AbscGX17sQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcENYbkFkZkdCWUxtS1Fa
            VXpFejhHSzJkQUZHV3VUZjBteWFiZXA2NVNZCkkxSEVEM0ZtMHREaGFpNkZQQWtu
            Zk0zeWJmWGNQellMVkg0OXZJM0cxVTgKLS0tIEdheFZTcEQzMUdEWGlVVXgvbkow
            WWk3dUtOYzg1Y0ZJTFlORzgzSmtEWjAKFrPNVyNw/F5Yrz3t0jUQ5QKHuYsKvP9L
            2C59G2swvoWwmX2l2euJYjExN1x8hjJLdin/GBcjaGXX5BaJD6dm/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T04:21:55Z"
    mac: ENC[AES256_GCM,data:/OULyrhEfYCLl0kO5xwkDXJBKflulut3ToFguAmWTHkqLA0IdAXWZL4Qf2t8iyJirWZ225Uva9NBtRa/VTxjHuBUwBg3eZrx9b+sLvmjpq14xY+HdTtZW+3S3onD19qWTLcmp1/57WdTSPIK9Ov2naARrphGGphfbAfEaEMjapA=,iv:2BHy7JF7ikg9S8yioH/Q80agqJsOj4BvY9MDp9KBX5I=,tag:Etc48UDKQKnuO7q8F/REFg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
