apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:l3CJm0Zns0hjhq+GMq0dJzKe8ms75XRb5mchQmmSgP329FJ+FtDW5S9w6eVXf8NSlvLW7U1tXawIJGatSk1Gr6oKPf9d9tlHQICzOXgOfz4TCH/CRqvorO2SxB6W4diaejvXDwnm2XS2GbNwa1g2clgX2BjtdApxuChdb0Vwa8KBWdpFnBIfDXNQ5nwFXgHctm4sQLRBY9ALiJxX1F3oatR6AHU5rd2oK7P6RVVbzaIxC1mvcnudum2JBLbb3WeZZzyn+r62srsFIp9FmCwHI372b/z48xG0/9+xSII6J+Bj5CwOxCdpQRgb/ZU/KLR6oRHmySsFNc/ZP9wKtySDMxUyoIwQKOYBEzLGhN67VZbKnUKxEuXVNq9cihaMdfKZ,iv:E02PGtnPzbc+Nd+zBlEhZ6kTVDrVsQFXsGzqhc+eV/0=,tag:0s/eyStT0y6F/YNjUnjDIQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:en8iSFrrRV3UMfD08/qBE2OX777BerSwJMKG1dRhN6l5IVPIXCX8vbU4YbF7qvVFS5PvTFG/znD1KepLi358kXvGkutI2GuKZiZ+UgYsdoONvrce1Z94AO9y49XQZnQF1bwZlgKKYAnfgoRqcUUOUzkjIW6HhZvcknQ55g1aIl4C9XA6jIYzZG2V9zaxTgbWenFqKo5x5PvU/XMtxo4bcAVfNkcKY8tPpHkOptVWTDrShcmGHc04Y9qZMX/jTqCGV0vNL3Fro3jjb1SmXQ==,iv:CZYoXGYuuegRlAB+hWcj+IznU65Op+m4jJMa4VkytHw=,tag:c8YB+tmd740LSgtbZjWnbg==,type:str]
    known_hosts: ENC[AES256_GCM,data:Su2W/B1UstjmmIZW0uMbGFHueIabq6bCAw48DzZWm+qbefCqy63AW9l+CNYPGlNpsd4qpM8BAfP1TnGWB0eAPcVSH6+HFyOzRdkmBcyM3Qf3Ax5qXFaGnrC3qJw/U8oQdrIyp0ibijp0T9hZzHmvAZpTWqj2FQXSlScIM8IfqEn+XAi+/R37pqLi6uP6H+7O6rNqy9/j1W7pBXlru7g5Sf/Jud2dc+gyX1Ea,iv:rmxW/p542H2wt1aS1qt/naDEWUxd6t2S1Uy0HJe1AnA=,tag:1GXeIOGlXS7NgDJvmMlBEg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNmM5ckx5M1JhOCtia2Y3
            aFJZVzNRa2c1UCtzZXMrdHFuMGtEL2hGRzJ3CkY4RGo0cHBEV3pXeWhUZW1DSlN1
            SlpPeTYrS05yZ2NYRytJSmN1Q1Q4a0UKLS0tIFM1eHdOTE5LN2Qwa3d4Y1NYQ3g0
            dC9vNzV2UHJnNXc5eWQ0V3RaeHVhSDgKgqYLpM+vLHxZczOh2F6eYWx+Fg/Lb6ai
            ikTvp0YbdC+5pWd+FdSO2fuDg/9IwqLtlXo1St9a5oRzwG6cMcyCGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T01:57:38Z"
    mac: ENC[AES256_GCM,data:Zc7y8SXbZnGDc7xSj7+8KhCb6TPBiwgLbP+WzvRv2dzuPlZETr7onUmGULz98uGDdL3xjJ2LAv4qio8NBoHWt7IjayH9AltBfGCEzgXuFOMxI4BMPxazMned6c7uQ6JG7OX4/6I7iSM0mDQ6KOnskJL92KWj2MJXcctEphgIT50=,iv:jgUvCZukYxvkfkyvrN+wHe780NXBbtS/Z2Lfzi5XSoI=,tag:jPfOWc7jku6J9SYbTjiuqg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
