apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:AVnCwW9CUg15DlMWGrdSGyjXtb/W5+oRm3rKKmXYMy0zDWytLy1Qhb0GNxtwDcURfOS1WYnxX90hi8FHC7b/+NgB+2EmSFyHx5Xfn/1S7QofbzyTTm0nSRfIdoNtxoOoC+95sdoSxjBvDddHyQV1lkGEO2rSckhlAchd2jAmQ7smbUqzEhih5247WPKJQsRRdg7Jr3GGLUVKIjIpZf5wp4EBkKnFHV4Rwc4EgfjUErQrp8ldKZuHIV+AO8NIKOZcaFVQjDUhrJKorMB2TMSR59X5KiRklhZ7S6Dx7fzGrVkARsAo+HzUApXND5o3QhxDefeJ8JUILfI/slY1K2GC2PWoctISCZY8ZcL22bRugfsB2cqdeow2SJrK/o+A8bs3,iv:qeZYApw78QZrFMKFCdZQHzWAFSPDzg5jXFZu435xUFI=,tag:SWg/EoSaU8TrpqK0+lfkYA==,type:str]
    identity.pub: ENC[AES256_GCM,data:MugZx4Fs2rzFGY/A4gqdEvnjgFEHXyTtrTegGfcAjn6HxQdN4lfx67chstJj9qYLhE7FDyu+Mo23dqmapHN2MkYvlhu8eACwaJh/zq7IHOam0/XXMUaeYaQUHSYOd7Q6YcI4s5nVpP2q5ePCDOunO5VoQIW9mowQGSYVmT5hcwoTmiipkb4/lLlm0VudC2fQePf1NlpSECoBI8c3lX6glA7FmV8uGFPPHVR5EWnJK88opJVY5pOysxO7fcIjI1eof9OhJIvQcMUBcz0STw==,iv:cX3dpgne5BKw2hJ2Zyu+P6YZtBofyMj+2FqURMPUYPA=,tag:vunF4pkdNI/i2d3tHBCGAQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:BHBeHtcV1MbJ6HEXXFzrk9nHXLOnq+o2z9FLxbS/c5C5+tz5YSkd43/ZVt84rCCAmmyby4latIYxFBTB/DsdyROnjvs59LKbkfNiPUmL5sAgSjjEIhc8cq/gOsdBrwlMI3e5L1TRCRFRlNeX+jo/fu8FSadP7jIeAKeVJuwa8iwJMim9gcAL11Bf/k4I7IKlkSbcoCTg+PNMrfRdDAbZZloUDm8p3KgKm6re,iv:MB9APyPrhs8R25+4yV9wFdfs6zqB6OyY8yzS5o2mVQo=,tag:FwFADQ53vvRcG2fyc33JOg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWWtWdWQ5dHJMTVl5c1dL
            WHU3T1BmVEp1a2haUjdxV3lpZldSL1hERVVzCjJuRmtUTkpaelUxNGZJSjBSVWJI
            OWhpak5FZXVMZ2dqUkl3b0RjVDVHWlEKLS0tIHVzMHZDcHRDTTJ2Qi9OaXNXZGhi
            VFg2VHJhTEc5VzNlQk9VTVdxWGNISE0KgGhMziIE2jrVxJmWELMBloKGwsl/sC5O
            bfUvQvVvd8A3SVGbtWmPSUGjYp93VtpaOUF9xJZoOfMdr3yvtgWs4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T04:06:21Z"
    mac: ENC[AES256_GCM,data:2i8L9kXh9Bcmn3XwHbiV+rSp2vyNqHcRvpCJnqGtFWbjOqbDmCxX3fNMYf90jPpop1AznXy6K1L8YshZQq+qBTBhAwkekYL4xoj1jd7biN13g1ZRqwX+FyNGUoOgNRqa7eanZD5Y9q5YTZ8RaDls+jer6Wxtujm24DaGxXuT0cM=,iv:z/48wWaUDLJji49PbpF4HwY1CYFdlvE0hZ6OvxkCLno=,tag:aAsE79FZ03UbSZdEEJiJOA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
