apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:KYLmrxlleqNC9udxEMpPnI1rFdRNSA8geubjn3Mk3sjLr5sQd+UGBWK4gypkBK3Q+a7i5RPH/KmLbaRthZzcRbmIYi9D5QldSWBh1tVa2oI1qIUaUrRGubgMtv0se32V45+4TblJhMb+9wc9Y7965MRBfAGTp9D5ROWcU5GtRRzEEm9vYw2CcplRcFnA2oiaV7dqrW0m/fwhg5DTObdwH5gsAZbrgqBofy2sH6RP7PAYrFA8nGH2Echo9WB357bt69e5ITLjtuEybvpFs2qALO4l7zTTH4RqVtAJBA2ypQaxZfRlMBOpo2+GpzJMpm6OlU7yFGfiraIfSNfJetGHL0Vjz+4FG4LKsjmdLiNfeX6Og62M3NE8sb9VDJdtEQyC,iv:w/fsFJa9oJJvhX6cUA6ZUTsNhl9Ac4+SX4GzV454Qh4=,tag:v6YLv+4ymmJeZNy9+xfKYQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:78m6qUqDWWLevBnL5wcxV+OAkBRdZAzTUWBAM8S4c6TCh06+Jd6cfL/Nk/UGe67dpQZKES2G+e03sP9uaVo3FVaopjYjspT0PxUx3svxEEg4URll2EuS4UjaL77zw2y4slfAZBgqHFjGfvhbm5gwdq7XJ/9axHkqA2/cd3Lkw7JALA4Z+pQVLDbsdmtEEwGBD8/JowXp15bGeA+5T2Oxv/s5heyeC9ZAds6DgD8Kvio6TYcxRkKHcsn8ZwuCtfOLVMq8iYiEsHvSyS0P8Q==,iv:nu+Q1zorMu7B0y9RIJbtfb4+0MRIPQG+LVU2pyGMwmg=,tag:Ah29XYOnCzdJvSRUpdVGjQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Eo54Rk41raapx8lk5+Scu5mMXKxtwR/47HN3ij2SPOjHL2YamYiBHvpWEC+3DjFvUFOjGayI3HRsTxdu6GZ7miqnYXg9fQOp6i6SGwKD1UB9Gk7LFvfpleaxXo2wdgI0NH4NbmQP9wsPe3MN+slLUDSn97M3cr3lipr1xJHtKkL3y9m1tQwGlfZN0tdikkHRbxmy4eoS+qgapLk9sZAhBp2ZBMkKdBVmKHuv,iv:6LTIy0YDy4VsFa6Janc0pm+vt5P4MOV3kBydS2teKEk=,tag:Iaihy6sicIF7NmCM3onNuQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdTRFTExqWjl1cy9wMmgr
            TVBhaWthdzJSUXJLZTZmcGhNUC95N0FwZzN3CnBaa1ZKVTFDQ2xiV2F5TlU5QTl1
            Z1FMY3dOQVozSHZjRDBzdkVxbFdGTUEKLS0tIDBRSVY1dzlDWDNJaVd4ZlowMVU5
            WVdjdkc0aXR3YXlIT24yaHNPbnltR28KSKoyfLCvL7jaPvizwW8T6SxNbDzm8CiY
            54rJ2SCNWuObk5+hl7i1vfVy7Hb1hrm0Ayfv0MNW5T1Ov2+j8k6GRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T07:54:50Z"
    mac: ENC[AES256_GCM,data:aCVP7nWf7zKtPGibq3+havgx9ZsqhOKs24XI8KZA5bjd+y7tDORKSDmks62E3cWfm9rYuVaC+FPFt/mkIkjIsTyStjp0AmLiL7dITRH8Qy/jwiVHOV58neP/Ipl2XSHf0srXuBWh9W3YZIFMg5IxjFwgu7/7VgdWWLJ8/Oe41LU=,iv:6veLDNNfh6yzYr9pnSVwX2xhlqC52jEC1//jNhc7Xp0=,tag:3HePqwQMHDULOVyLKiSauw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
