apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:smbfx4iwpB5R7u3mMvrkewTi2hArwc5ktXhYdzx5+w2NzztzXLp/GP4ErsvRqLGV771OAQo3LV7tHKMvboV/+vnhssBSdDR/NJymA+jWLO78ye1/Ls3kLKqNKD1Vk62f/MThZJ8x8IKixC6RSGpuD6DglpFYp2TucYVE14JMzKJ/c5gGMpz5RiKlFKBN5J/Q+PXDAzxLmuCxdn0QoscAsjYB5eU5KX09+DvTdq2472sUSrBh+d32KYLwPkYIqtH9Npr72ZjCU5WoXJqTozJmH8cAFX/sMCvg6yYvhZ8Bw9a2pLEAmoMTf+/NX3lMqVS6l4U8gYsHxkgaGRSRs5BsTKOGwQK++Q82Kbj7BMsi0LQs1qH/D7vaHu+/1UWK1O2z,iv:sx+d/S3htnKVXj1pEs3TQHVjoiOVrzFC5yF0OdHv2Fc=,tag:enj7YYMhgMZ9IA78N1+J0w==,type:str]
    identity.pub: ENC[AES256_GCM,data:vOYEOvkKpGdziFs+3n1re00MSEKM3Xuvq4c1VwCgCbHs2BloWn5wCHErNzATe+gUVnQUTZlZgHQQEOn0YtuEimB3AdCiI1JZji6VHjiWhmj+Mu8j9RC9rKp6LNdnK65GyAmfQ0sFwvW9rd/CfCeBoqUW72DwIvO89cAUKOsAJaVK3NO8JD20UhOMlgjZPGQZgSv/bPd1NWvSPervmyPYUgJlyFivHI0ZvQf6b/xtteLU49/iEUj+t7RNHWn1EeygOIEc+Xx/5V6so3xWEA==,iv:AHXVVgNelKxPaPuk4FgwiylhB/dLPC8JwbIthA1kq4g=,tag:7QSVaKmYkB45Lg8kM2oCQA==,type:str]
    known_hosts: ENC[AES256_GCM,data:9zCN/xdL1WS6F9A0cq/N6gwUL03yFC/i4VknRxmd6/ZA8kQtZ9XHpm0GbGoK1VH5Y5g7vNDxtpIafT3KYoD9+qRoLc2SZnHnVr6yS3QTXLnbPVDqX5C6yfxjmrzCYR7/TD232uQN0B8ZcIBmXk24gNDVfMrU3PqCFWqZhtl03ySP2AaoNA4ehPHhrCPfVN4aBN+TQUfTNyXBUTUUqVmcN+nN540hsL93RIif,iv:DnN/jp23Zu21UQSQqWpzk6cmNdN/htAuQP+nUGZZri0=,tag:f22g/E5UDHVrkCsdJsnVbA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0OW9MVzIvOGZuWVdFaE9E
            cFEzUHJwUmN4OEw3cml6dTBFbGRSbmtvTG5VCjNkaUJQWGtoUkJLdnJSZGdTUmcr
            QkZ6b1hqN1R6OWdJcnlLQXJ1andqVTgKLS0tIDBuKzNLOVN3L200cUhhOEhQOVFQ
            QkdpRlNiT2VXY0kzTjZrWWZIWG1QalUKZAwBpQM03/xCebPd1faKGDCGGRRL18C1
            qRqHR6I3dz4qvR8wRIIau/OrDhuym7IhTE80REbMnh4vnIVKr1t59A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T12:49:06Z"
    mac: ENC[AES256_GCM,data:vaGyylfwF9PTzN2LhaNiE7vCsY5NnCKdU0/bZ7sB67UdlQgFEYoB4pw7xvMH1/XA046UQK7buABfOte0mZwerxHgwvOGWrweM7MgLn+aA9ctdH8STEPGRlwXoTlK4kaIDFXuwAle0IQk7VvspNBQ4H6/qiYVRNYz69Zyw1LUGx8=,iv:xmYT3b1liJiMKDp28gvLRog6ttn/udGD8ieHlO0jJmw=,tag:7E/3GakM4IQII6CZXPBHcA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
