apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:V1+eBLLYzWVsIVwTfN/s4gc4ozu8ytyqqfG9ptt9zZW780ygGBfuDRRxCIYDqgiaqgKs0QdLdQEUKfwyU8WmrdTNbLzM8kbgmSSrLzq0xnNNbKM8NRYmxItE6smNULHj8bLPIPdJ0f8OAhkCvWWrE3kf80kxZY4kpqXYN3ltBzhVpXJoQvjD5jpzEQwZheu/pfgonDdDlH1j17wglZuY+gXVD3lZgczfIRDte8yWzdL6F0N81VfRkwFIQCLFgz8O5VeAvgdZgYGACATqZfV7ExXE/CojX+iQQdw+QfhhJ16cvuJPdbeMFO7EIn9Ka5G/JbgJuU633tyiV3bA3SKD5Uq4GWM1J8k8DqOpPwabG6NIPMcR6HEWxmotbbWYtvEg,iv:Xc5HsF14l8WqtL9n1rKStdrUOsn5kU1s8rPOedrQbXk=,tag:LieNxge6llGma3KC8BSDqw==,type:str]
    identity.pub: ENC[AES256_GCM,data:wk87DL8EchEYw/f6IRFUkkHrFbC7WA2RQja37iGAQ1gKtWOA1esp41pUJuyt6ne31vmPH2XeueB8rXid1D4TYiH77a8PN59Khh8gXGe42HoGK/lYk32vmEptpmlCWdwYC0howrXx1ZetEwePv9u9OXTe3WFly1l8tUzRofp9N4GcNtPWgUiHva2irrPbBx4uOLxDm7ug1UPUUX1UHc7b9g2+1rx0GKRLts/JAc5J1EP+pGsgitDq4md+Uqxb7NFioz0RwGB+2UdegoYBDg==,iv:sTI9VRB817gphhM0hw5iACFU+du5KOf+awa91+b6qf4=,tag:fSOY2bZ2xFA63vEPEk+JrA==,type:str]
    known_hosts: ENC[AES256_GCM,data:TQ82LYpLe8laEx2QQEdR8vtY64JOY+QyMB0hETI1yfSSd2mV4nQwT3Jo8BOLVWNUIRVnV97tl0t311/TEnXPT7Dzo/GCqLDLi+lXE/JMWpQQKXiRFIA6RcNAUNQ+Qd9fxuunCjsKnbnxc3tbxKbT0NWCiY2OnZ92dDDXKlHH0mhYhCvFM1ea45Oj6QTm0tgaEADvgLQ+O4oDjb4JJ3dEv9an/uI7doFg/YvW,iv:2DPvjyoxGIgJjqb64tNQfQ9q8imidY+fjLNBr3aeCvk=,tag:5jk78o9rWWdHhG5ptoSYfA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWjhrN1ViWjdGYW9UZW9U
            eTJKd0JXUTV2aE1yUS9QMkN2YkkxL2w0K0UwCkVDUEhWa0tFbFZXcGtIZGs2c1Zm
            WlEyaHZyWENKNGtoRE1MK0FPSW43Q2cKLS0tIDhRSFNQSHVMUjgrTG85MjBJdGFm
            OUowdnQ2ZmxndllIbmVibiszN0ZLaTAKbOg/bzkQqzTls7hPcRVn3siek1WT4LC3
            Kb/KWistkwfKKey+1B0RKhBgEWv4wEpZ5oIbgMqS+A5OPGu2JUt2cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T12:46:41Z"
    mac: ENC[AES256_GCM,data:mFczCfOQ0Ef+KcgzulYi2CYDot8/tmmxWNe2+EK0h04F2XjPw9kF+uNhhSoU/JN3JC2NDkQFl+WNrhOdn0PF/yebDgYrDGrw0MswmNDMIcSWU/G6tCKvDRG5zM8vLrGdEERsjdE8ajFuabKk4wdlFlHsnAedpPlTQaE9gewErxY=,iv:MfVbZvCvXjaunxzzLj2n85hHHqcTwywP4TyXcEC52P0=,tag:6MS4Wwb7EnVMrc/n5eun7g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
