apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8axvkiDzOBl4L1OHVpyD64+DNzdu5ZlgXtWEVU4oQHDsbxELd/B0yp8gzsdKpzkEFy07f4xpE0wo0xzThVpKybNfzgP1js6FqiBpXpNjiyXXHbf9k4UZo8usLP2H3Dp/44aHcG0z8CTGv69dKZiGwo0DrPBv0sNBaj1lMLk7U9JKfyx9UWaFfjo8eEqWMRRTk5rAIhKEfSD8OzqBlxkRBUDb1ol9k5GprGHRDE0hMfZPs/vifklq2lCCdfTmYeGYfD9Jg2YkbTvymCkajDy3LJz1DzHBzYU8KJ5zRMG/uYf+ehIGyqyOQsc5/Kg0E6w+K+Xhg47n5pSENY/P5eSnILIZlgEnZSzWgMLuKbfVFIQ05X6YdcLAyfPCIxrZUJnY,iv:yZeN9qHda6oihcd72KbEXqO5Xc9n3SMS911tprQgje0=,tag:NoZIMGQRBMsXu6IoG0hLfg==,type:str]
    identity.pub: ENC[AES256_GCM,data:2FC+mMpI+ThomEo/7RnZ4Bfq/KP1nyi+1IhOwEmJXkHsJhaFsK56zuRjEIBHIyVKAGqqkzPWRo9H3t61yqZsFbyE21vdjMAr8yI0W3Se7CuJ9Nx8NxrCTp62X2xR4QbdoafdNGncsbaFdeAirflhG/nvcQm2RNuKSFYDreEDHcMzSuGzebvpPoOspBRRt4Nt8O+v96aCYvod8fotrRj42jkeZ5SVIm9aI9wvT8DSrMpYoypRqkh30WVrPPl3KUgaLDaSmQ/S3OsKz/8kDg==,iv:ZV01aQT6GxJMjPGN7dBXllwCSB7x8E2FYHOjq1dlrvA=,tag:bEQlKehaJD3riw4WJaqv4w==,type:str]
    known_hosts: ENC[AES256_GCM,data:J6HtYrYHOiYQvkTozjafTUBMKAAI01GaPf+SZPrfvh2/YMBG0CYs1YuFXiNid7Bfv2p2Rmgv//Go5ZxeviKc1rRl0xMKNI++acUF8VM0kDetJwLi48CgPd4k0+1Fe3hgYYnTXt5Eby2Zf3VdyzTjjSQPplOoAz9CrbTLy1R9rq0WmVXS67cwVOb/E0PMMiZSIaiOIvBO0vZv6A4xJhXSxW2ZC4ouYRkn3bYO,iv:D0y5Fy1bAILXxivVpvvnqyIapz7k+2jmJoaQyQpBcEg=,tag:purKuDGaXKHdqMyRJdRy4Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsK1pxLys3UDM4UnU3QTgr
            Rnd4REtsbzVwTm96Myt6bDZ0V1U0cHUySG1vCm5JaEcwK05KbERCVVNvdUthYXl3
            ck1aUUJQK0M1ZnJaVW9vKzU2aU5STzQKLS0tIGFqVi80ditybjBQNTlUa2VJYmxJ
            Y3EvUW41RHczR1dYbnJqUFlsSzVQbTQKazWzKdYsL0wKQ3RwX8opyd4zA0OAo5uD
            zcSOyrpdCjp4OYcKUS9WrQt5bG0hVcL9g9v7g8wozKYDAv8y63v1sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T21:44:12Z"
    mac: ENC[AES256_GCM,data:WMP2cAU5N3mfFqv0/4+hoLs00l95Zkc7Ir3PsG0ehKkBW1IML4lNiGZ4ZN+sVPnKCa5Up6J33uqnSxdobVfebyWZ8MqLDMFellAXxuutPcclkbRdVpvVYaddSOlfU8aSiKQUEJQVhsd71YmL5YCdw/A2EAd0ho61TdDENcVkU38=,iv:2WJ20sc5NwSIb8pNpOc0V/Rt7qyHjDMR8NpFAbcaV8E=,tag:sRLUcZ31Jd7JmVlk5IOBSQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
