apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - clustersettings.secret.yaml
  - deploykey.secret.yaml
  - flux.yaml
  - upgradesettings.yaml
  # - sopssecret.secret.yaml