---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest-tracker
  namespace: speedtest-tracker
spec:
  interval: 15m
  chart:
    spec:
      chart: speedtest-tracker
      version: 8.33.6
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gatus:
      group: networking
    global:
      stopAll: false
    apprRiseImage:
      repository: caronc/apprise
      pullPolicy: IfNotPresent
      tag: 1.3.0@sha256:e365025a7bf1fed39ef66b5f22c9855d500ee7bdea27441365e5b95ea972e843
    credentials:
      cf-restic:
        type: s3
        url: "${CF_S3_RESTIC_URL}"
        bucket: "${CF_S3_RESTIC_BUCKET}-stt"
        accessKey: "${CF_S3_RESTIC_ID}"
        secretKey: "${CF_S3_RESTIC_KEY}"
        encrKey: "${CF_S3_RESTIC_KEY}"
    service:
      backend:
        enabled: true
        ports:
          apprise:
            enabled: true
            port: 8000
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                APP_URL: "{{ .Values.chartContext.appUrl }}"
                ASSET_URL: "{{ .Values.chartContext.appUrl }}"
                APP_TIMEZONE: "America/New_York"
                DISPLAY_TIMEZONE: "America/New_York"
                SPEEDTEST_SCHEDULE: "0 */3 * * *"
                APP_KEY: "${STT_APP_KEY}"
                # inital install only
                ADMIN_NAME: "${STT_ADMIN_NAME}"
                ADMIN_EMAIL: "${STT_ADMIN_EMAIL}"
                ADMIN_PASSWORD: "${STT_ADMIN_PASSWORD}"
            apprise:
              enabled: true
              imageSelector: apprRiseImage
              probes:
                liveness:
                  enabled: true
                  type: http
                  path: /health
                  port: "{{ .Values.service.backend.ports.apprise.port }}"
                readiness:
                  enabled: true
                  type: http
                  path: /health
                  port: "{{ .Values.service.backend.ports.apprise.port }}"
                startup:
                  enabled: true
                  type: http
                  path: /health
                  port: "{{ .Values.service.backend.ports.apprise.port }}"
              env:
                APPRISE_CONFIG_DIR: /apprise/config
                APPRISE_ATTACH_DIR: /apprise/attach
                APPRISE_PLUGIN_PATHS: /apprise/plugin
    ingress:
      main:
        enabled: false
        ingressClassName: "internal"
        hosts:
          - host: speedtest.tracker.${DOMAIN_2}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: true
            auth:
              type: "authelia"
              internalHost: "authelia.authelia.svc.cluster.local:9091"
              externalHost: "auth.${DOMAIN_2}"
          homepage:
            enabled: true
            group: "Monitoring"
          certManager:
            enabled: true
            certificateIssuer: general-le-prod
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      varrun:
        enabled: false
      apprise-config:
        enabled: true
        targetSelector:
          main:
            apprise:
              mountPath: /apprise/config
      apprise-attach:
        enabled: true
        targetSelector:
          main:
            apprise:
              mountPath: /apprise/attach
      apprise-plugin:
        enabled: true
        targetSelector:
          main:
            apprise:
              mountPath: /apprise/plugin

    cnpg:
      main:
        mode: recovery
        cluster:
          singleNode: true
        backups:
          enabled: true
          credentials: cf-restic
          retentionPolicy: "7d"
          scheduledBackups:
            - name: daily-backup
              # https://crontab.guru/#35_0_*_*_*
              schedule: "35 0 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false
        recovery:
          method: object_store
          credentials: cf-restic
