apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - doublecommander/ks.yaml
  - plex/ks.yaml
  - fileflows/ks.yaml
  - fileflows-external-node/ks.yaml
  - kavita/ks.yaml
  - metube/ks.yaml
  - posterr/ks.yaml
  - sabnzbd/ks.yaml
  - tautulli/ks.yaml
  - qbittorrent/ks.yaml
  - pasta/ks.yaml
  - plex-auto-languages/ks.yaml
  - theme-park/ks.yaml
  - tauticord/ks.yaml
  - starrproxy/ks.yaml
  - muse/ks.yaml
  - checkrr/ks.yaml
  - calendarr/ks.yaml
  - cloudcmd/ks.yaml
  - reaparr/ks.yaml
  - jelu/ks.yaml
  - lazylibrarian/ks.yaml
  - cwa-dl/ks.yaml
  - booklore/ks.yaml
  - sonobarr/ks.yaml
  - guardian/ks.yaml
  - ytptube/ks.yaml
  - streamrip/ks.yaml
  - listenarr/ks.yaml
  - utilities
  - indexers
  - managers
  - requests