apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - doublecommander/ks.yaml
  - plex/ks.yaml
  - fileflows/ks.yaml
  - fileflows-external-node/ks.yaml
  - posterr/ks.yaml
  - tautulli/ks.yaml
  - pasta/ks.yaml
  - plex-auto-languages/ks.yaml
  - theme-park/ks.yaml
  - tauticord/ks.yaml
  - starrproxy/ks.yaml
  - muse/ks.yaml
  - checkrr/ks.yaml
  - calendarr/ks.yaml
  - cloudcmd/ks.yaml
  - sonobarr/ks.yaml
  - guardian/ks.yaml
  - utilities
  - indexers
  - managers
  - requests
  - books
  - downloaders
