apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nginx-internal/ks.yaml
  - nginx-external/ks.yaml
  - cloudflared/ks.yaml
  - omada-controller/ks.yaml
  - adguard-home/ks.yaml
  - gatus/ks.yaml
  - uptime-kuma/ks.yaml
  - myspeed/ks.yaml
  - speedtest-tracker/ks.yaml
  # - nginx-proxy-manager/ks.yaml
