---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: magicmirror
  namespace: magicmirror
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 15.29.80
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 30m
  timeout: 45m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gatus:
      group: tools
    global:
      stopAll: false
    credentials:
      cf-restic:
        type: s3
        url: "${CF_S3_RESTIC_URL}"
        bucket: "${CF_S3_RESTIC_BUCKET}-magicmirror"
        accessKey: "${CF_S3_RESTIC_ID}"
        secretKey: "${CF_S3_RESTIC_KEY}"
        encrKey: "${CF_S3_RESTIC_KEY}"
    image:
      repository: karsten13/magicmirror
      pullPolicy: IfNotPresent
      tag: v2.34.0@sha256:5ff351aca1f136acafd04d4a95c104a9fb6451cd79c59e94d45df72b2a0a7ac8
    mmpmImage:
      repository: karsten13/mmpm
      pullPolicy: IfNotPresent
      tag: 4.3.0@sha256:c73c35215c2e2f1768a57b23322c318fc532d5a1af23f4b3bf1b08ae4580044d
    securityContext:
      container:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        readOnlyRootFilesystem: false
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${MAGICMIRROR_IP}
        integrations:
          metallb:
            enabled: true
        ports:
          main:
            port: 8080
      backend:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${MAGICMIRROR_IP}
        integrations:
          metallb:
            enabled: true
        ports:
          backend1:
            enabled: true
            port: 7890
          backend2:
            enabled: true
            port: 7891
          backend3:
            enabled: true
            port: 6789
          backend4:
            enabled: true
            port: 8907

    magicmirror:
      mmpm: []
      config: []

    configmap:
      mmpm-env:
        enabled: true
        data:
          mmpm-env.json: |
            {
            "MMPM_MAGICMIRROR_ROOT": "/opt/magic_mirror",
            "MMPM_MAGICMIRROR_URI": "http://0.0.0.0:8080",
            "MMPM_MAGICMIRROR_PM2_PROCESS_NAME": "",
            "MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE": "",
            "MMPM_IS_DOCKER_IMAGE": true
            }
            
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                NODE_ENV: production
            mmpm:
              enabled: true
              imageSelector: mmpmImage
              probes:
                liveness:
                  enabled: true
                  type: http
                  path: /
                  port: "{{ .Values.service.backend.ports.backend1.port }}"
                readiness:
                  enabled: true
                  type: http
                  path: /
                  port: "{{ .Values.service.backend.ports.backend1.port }}"
                startup:
                  enabled: true
                  type: http
                  path: /
                  port: "{{ .Values.service.backend.ports.backend1.port }}"
    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        hosts:
          - host: magicmirror.${DOMAIN_2}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: general-le-prod
      mmpm:
        enabled: true
        ingressClassName: internal
        targetSelector:
          backend: backend1
        hosts:
          - host: mmpm.${DOMAIN_2}
        integrations:
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: general-le-prod    
    persistence:
      mmpm-config:
        enabled: true
        mountPath: "/home/node/.config/mmpm"
        targetSelectAll: true
        volsync:
          - name: mmpmconfig
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      mmpm-env:
        enabled: true
        type: configmap
        mountPath: /home/node/.config/mmpm/mmpm-env.json
        objectName: mmpm-env
        subPath: mmpm-env.json
        readOnly: true
        targetSelectAll: true
      config:
        enabled: true
        mountPath: "/opt/magic_mirror/config"
        targetSelectAll: true
        volsync:
          - name: config
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      modules:
        enabled: true
        mountPath: "/opt/magic_mirror/modules"
        targetSelectAll: true
        volsync:
          - name: modules
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      css:
        enabled: true
        mountPath: "/opt/magic_mirror/css"
        targetSelectAll: true
        volsync:
          - name: css
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
    addons:
      codeserver:
        enabled: true
        service:
          type: "ClusterIP"
          ports:
            codeserver:
              port: 36107
        ingress:
          enabled: true
          ingressClassName: "internal"
          annotations:
            gatus.home-operations.com/endpoint: |
              enabled: false
          hosts:
            - host: editor.magicmirror.${DOMAIN_2}
              paths:
                - path: /
                  # Ignored if not kubeVersion >= 1.14-0
                  pathType: Prefix
          integrations:
            nginx:
              enabled: true
            certManager:
              enabled: true
              certificateIssuer: general-le-prod
