apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: requestrr
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/media/requestrr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  targetNamespace: requestrr
  postBuild:
    substitute:
      GROUP: media
