apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sortarr
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/media/utilities/sortarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
