apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: guardian
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/media/guardian/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  postBuild:
    substitute:
      GROUP: media
