apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fasten
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/medical/fasten/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  targetNamespace: fasten
  postBuild:
    substitute:
      GROUP: medical
