apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: es-octoprint-pi
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/external-services/es-octoprint-pi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

