apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana/ks.yaml
  - peanut/ks.yaml
  - gatus/ks.yaml
  - myspeed/ks.yaml
  - speedtest-tracker/ks.yaml
  - uptime-kuma/ks.yaml
