apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actual-ai
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/ai/actual-ai/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
