apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sonarr/ks.yaml
  - sonarr-animes/ks.yaml
  - lidarr/ks.yaml
  - radarr/ks.yaml
  - huntarr/ks.yaml
  - profilarr/ks.yaml
