apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snippet-box
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/tools/snippet-box/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  targetNamespace: snippet-box
  postBuild:
    substitute:
      GROUP: tools
