apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dozzle
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/observability/dozzle/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

