apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: home-ops-mirror
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    gatus:
      group: core
    defaultSettings:
      # Increase to 3 for a multi-node cluster
      defaultReplicaCount: "1"
      # Overprovisioning might be needed when using volsync
      storageOverProvisioningPercentage: "100000"
      storageReservedPercentageForDefaultDisk: "10"
      # single-node
      # v2DataEngine: true
      defaultClassReplicaCount: "1"
      removeSnapshotsDuringFilesystemTrim: "true"  # auto-remove old snapshots on trim
      snapshotMaxCount: "50"                        # max snapshots per volume
      orphanResourceAutoDeletion: "true"            # auto-delete orphaned volumes
      orphanResourceAutoDeletionGracePeriod: "300"
      recurringJobGroup: default    
    csi:
      attacherReplicaCount: "1"
      provisionerReplicaCount: "1"
      resizerReplicaCount: "1"
      snapshotterReplicaCount: "1"
    persistence:
      # Set to false to pick another CSI as default
      defaultClass: true
      # Increase to 3 for a multi-node cluster
      defaultClassReplicaCount: "1"
    longhornUI:
      replicas: "1"
    metrics:
      serviceMonitor:
        # -- Setting that allows the creation of a Prometheus ServiceMonitor resource for Longhorn Manager components.
        enabled: true
        # -- Additional labels for the Prometheus ServiceMonitor resource.
        # additionalLabels: {}
        # -- Annotations for the Prometheus ServiceMonitor resource.
        # annotations: {}
        # -- Interval at which Prometheus scrapes the metrics from the target.
        # interval: ""
        # -- Timeout after which Prometheus considers the scrape to be failed.
        # scrapeTimeout: ""
        # -- Configures the relabeling rules to apply the targetâ€™s metadata labels. See the [Prometheus Operator
        # documentation](https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1.Endpoint) for
        # formatting details.
        # relabelings: []
        # -- Configures the relabeling rules to apply to the samples before ingestion. See the [Prometheus Operator
        # documentation](https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1.Endpoint) for
        # formatting details.
        # metricRelabelings: []