apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tuppr-plans
  namespace: flux-system
spec:
  dependsOn:
    - name: tuppr
  interval: 1h
  path: clusters/main/kubernetes/system/system-upgrade/tuppr-plans/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  wait: false