name: Weekly Tag

permissions:
  contents: write  # âœ… This grants write access to push tags

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  tag-weekly:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        id: tag-check
        run: |
          TAG=${{ steps.date.outputs.date }}
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create tag if it doesn't exist
        if: steps.tag-check.outputs.exists == 'false'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.date.outputs.date }}
          git push origin ${{ steps.date.outputs.date }}
