apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wallos
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/financial/wallos/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  targetNamespace: wallos
  postBuild:
    substitute:
      CHART: wallos
      NAME: wallos
      GROUP: financial
      PROT: http
      SVC: wallos
      NAMESPACE: wallos
      PORT: "80"
